'use client';

import { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { adminRepository } from '@/lib/admin-repository';
import { currentProfile } from '@/lib/auth';

const requiredHeaders = ['Name', 'Phone Number'];
const norm = (value: any) => String(value ?? '').trim();
const phone = (value: any) => norm(value).replace(/\D/g, '');
const toDate = (value: any) => { if (typeof value === 'number') { const parsed = XLSX.SSF.parse_date_code(value); return parsed ? `${parsed.y}-${String(parsed.m).padStart(2, '0')}-${String(parsed.d).padStart(2, '0')}` : null; } const parsed = new Date(norm(value)); return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString().slice(0, 10); };

export default function CrmImportPage() {
  const [book, setBook] = useState<any>(); const [fileName, setFileName] = useState(''); const [sheet, setSheet] = useState(''); const [rows, setRows] = useState<any[]>([]); const [action, setAction] = useState('skip'); const [result, setResult] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const choose = (name: string, workbook = book) => { setSheet(name); setRows(XLSX.utils.sheet_to_json(workbook.Sheets[name], { defval: '', raw: true })); setResult(''); setError(''); };
  const load = async (file: File) => { try { if (!/\.(xlsx|xls)$/i.test(file.name)) throw new Error('Choose an Excel .xlsx or .xls file.'); const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array', cellDates: true }); if (!workbook.SheetNames.length) throw new Error('The workbook does not contain a worksheet.'); setBook(workbook); setFileName(file.name); choose(workbook.SheetNames[0], workbook); } catch (caught: any) { setError(caught.message); } };
  const headers = rows.length ? Object.keys(rows[0]) : []; const missingHeaders = requiredHeaders.filter(header => !headers.includes(header));
  const preview = useMemo(() => rows.slice(0, 10).map((row, index) => ({ row: index + 2, name: norm(row.Name), phone: phone(row['Phone Number']), valid: Boolean(norm(row.Name)) && phone(row['Phone Number']).length >= 7 })), [rows]);
  const importRows = async () => { if (!book || !sheet) return; if (missingHeaders.length) { setError(`Missing required column${missingHeaders.length > 1 ? 's' : ''}: ${missingHeaders.join(', ')}.`); return; } setBusy(true); setError(''); try { const profile = await currentProfile() as any; if (!profile) throw new Error('Please sign in again.'); const lookups = await adminRepository.crmLookups(); const batch = await adminRepository.createCrmImportBatch({ file_name: fileName || 'CRM workbook', sheet_name: sheet, imported_by: profile.id }); let imported = 0, skipped = 0, duplicates = 0, failed = 0, updated = 0; const audit: any[] = [];
    for (let index = 0; index < rows.length; index += 1) { const row = rows[index]; const name = norm(row.Name); const number = phone(row['Phone Number']); if (!name || number.length < 7) { failed += 1; audit.push({ batch_id: batch.id, row_number: index + 2, raw_data: row, result: 'failed', reason: 'Name and a phone number with at least 7 digits are required' }); continue; } const existing = await adminRepository.findCrmLead(name, number); if (existing) { duplicates += 1; if (action === 'skip') { skipped += 1; audit.push({ batch_id: batch.id, row_number: index + 2, raw_data: row, result: 'skipped', reason: 'Duplicate lead', lead_id: existing.id }); continue; } if (action === 'update') { await adminRepository.updateLead(existing.id, { gender: norm(row.Gender) || null, profession: norm(row.Profession) || null, reason_for_enquiry: norm(row['Reason for Enquiry']) || null, location: norm(row.Location) || null, remarks: norm(row.Remarks) || null }); updated += 1; audit.push({ batch_id: batch.id, row_number: index + 2, raw_data: row, result: 'updated', lead_id: existing.id }); continue; } }
      const source = lookups.sources.find((item: any) => item.name.toLowerCase() === norm(row['Lead Source']).toLowerCase()) || lookups.sources.find((item: any) => item.name === 'Other'); const status = lookups.statuses.find((item: any) => item.name.toLowerCase() === norm(row['Lead Status']).toLowerCase()) || lookups.statuses[0]; const temperature = norm(row['Lead Temperature']).toLowerCase(); const lead = await adminRepository.createLead({ lead_date: toDate(row.Date) || new Date().toISOString().slice(0, 10), full_name: name, phone: number, gender: norm(row.Gender) || null, profession: norm(row.Profession) || null, reason_for_enquiry: norm(row['Reason for Enquiry']) || null, location: norm(row.Location) || null, source_id: source?.id || null, status_id: status?.id || null, temperature: ['cold', 'warm', 'hot'].includes(temperature) ? temperature : 'cold', remarks: norm(row.Remarks) || null, assigned_to: profile.id, created_by: profile.id }); imported += 1; audit.push({ batch_id: batch.id, row_number: index + 2, raw_data: row, result: 'imported', lead_id: lead.id }); }
    if (audit.length) await adminRepository.createCrmImportRows(audit); await adminRepository.updateCrmImportBatch(batch.id, { imported_count: imported, skipped_count: skipped, duplicate_count: duplicates, failed_count: failed }); setResult(`Import complete: ${imported} imported, ${updated} updated, ${skipped} skipped, ${duplicates} duplicates, ${failed} failed.`); } catch (caught: any) { setError(caught.message || 'Import failed.'); } finally { setBusy(false); } };
  return <section className="space-y-5"><div><h1 className="text-2xl font-bold">CRM Import</h1><p className="text-slate-600">Validate a worksheet before importing live leads.</p></div><div className="card p-5"><input accept=".xlsx,.xls" type="file" onChange={event => { const file = event.target.files?.[0]; if (file) void load(file); }} />{error && <p className="mt-3 text-rose-700">{error}</p>}{result && <p className="mt-3 rounded bg-emerald-50 p-3 text-emerald-800">{result}</p>}{book && <><div className="mt-4 flex flex-wrap gap-2"><select value={sheet} onChange={event => choose(event.target.value)} className="input max-w-xs">{book.SheetNames.map((name: string) => <option key={name}>{name}</option>)}</select><select value={action} onChange={event => setAction(event.target.value)} className="input max-w-xs"><option value="skip">Skip duplicates</option><option value="update">Update duplicates</option><option value="new">Import duplicates as new</option></select><button disabled={busy || !rows.length || missingHeaders.length > 0} onClick={() => void importRows()} className="btn btn-primary">{busy ? 'Importing...' : `Import ${rows.length} rows`}</button></div><p className="mt-3 text-sm text-slate-600">{rows.length} rows · Required columns: Name, Phone Number</p>{missingHeaders.length > 0 && <p className="mt-2 text-sm text-rose-700">Missing columns: {missingHeaders.join(', ')}</p>}<div className="mt-4 overflow-auto"><table className="table min-w-full"><thead><tr><th>Row</th><th>Name</th><th>Phone</th><th>Validation</th></tr></thead><tbody>{preview.map(item => <tr key={item.row}><td>{item.row}</td><td>{item.name || '—'}</td><td>{item.phone || '—'}</td><td>{item.valid ? 'Ready' : 'Missing name or valid phone'}</td></tr>)}</tbody></table></div></>}</div></section>;
}
