import {supabase} from './supabase';
import type {Employee} from './employees';
const db=supabase as any;
export type Department={id:string;name:string}; export type Designation={id:string;name:string;department_id:string|null}; export type AuditLog={id:string;action:string;entity_type:string;created_at:string;actor_id:string|null};
function requireDb(){if(!db)throw new Error('Supabase is not configured.');return db}
export const adminRepository={
 async financeDashboard(){const r=requireDb();const [accounts,transactions,invoices,payroll,runs]=await Promise.all([r.from('finance_accounts').select('*').eq('is_active',true),r.from('finance_transactions').select('*,account:finance_accounts(name)').is('archived_at',null).order('transaction_date',{ascending:false}),r.from('finance_invoices').select('id,status'),r.from('payroll_entries').select('payment_status,basic_salary,allowances,deductions'),r.from('payroll_runs').select('id,period_start,status').order('period_start',{ascending:false}).limit(6)]);for(const item of [accounts,transactions,invoices,payroll,runs])if(item.error)throw item.error;const rows=transactions.data||[];const income=rows.filter((x:any)=>['income','invoice_payment'].includes(x.transaction_type)).reduce((n:number,x:any)=>n+Number(x.amount),0);const expenses=rows.filter((x:any)=>['expense','payroll_payment'].includes(x.transaction_type)).reduce((n:number,x:any)=>n+Number(x.amount),0);const accountBalances=(accounts.data||[]).map((account:any)=>({...account,balance:Number(account.opening_balance||0)+rows.filter((x:any)=>x.account_id===account.id).reduce((n:number,x:any)=>n+(['income','invoice_payment','adjustment'].includes(x.transaction_type)?n+Number(x.amount):n-Number(x.amount)),0)}));const pending=(payroll.data||[]).filter((x:any)=>x.payment_status!=='paid');return {income,expenses,net:income-expenses,balance:accountBalances.reduce((n:number,x:any)=>n+x.balance,0),accountBalances,outstanding:(invoices.data||[]).filter((x:any)=>!['paid','cancelled'].includes(x.status)).length,salariesPending:pending.reduce((n:number,x:any)=>n+Number(x.basic_salary)+Number(x.allowances)-Number(x.deductions),0),recent:rows.slice(0,8),recentRuns:runs.data||[],monthly:rows}},
 async financeOptions(){const r=requireDb();const [accounts,income,expense]=await Promise.all([r.from('finance_accounts').select('id,name').eq('is_active',true),r.from('finance_income_categories').select('id,name').eq('is_active',true),r.from('finance_expense_categories').select('id,name').eq('is_active',true)]);for(const item of [accounts,income,expense])if(item.error)throw item.error;return {accounts:accounts.data||[],income:income.data||[],expense:expense.data||[]}},
 async financeTransactions(type:string,includeArchived=false){let q=requireDb().from('finance_transactions').select('*,account:finance_accounts(name),income_category:finance_income_categories(name),expense_category:finance_expense_categories(name)').eq('transaction_type',type).order('transaction_date',{ascending:false});if(!includeArchived)q=q.is('archived_at',null);const {data,error}=await q;if(error)throw error;return data||[]},
 async createFinanceTransaction(payload:any){const {data,error}=await requireDb().from('finance_transactions').insert(payload).select().single();if(error)throw error;return data},
 async updateFinanceTransaction(id:string,patch:any){const {data,error}=await requireDb().from('finance_transactions').update(patch).eq('id',id).is('archived_at',null).select().single();if(error)throw error;return data},
 async archiveFinanceTransaction(id:string){const {error}=await requireDb().from('finance_transactions').update({archived_at:new Date().toISOString()}).eq('id',id).is('archived_at',null);if(error)throw error},
 async restoreFinanceTransaction(id:string){const {error}=await requireDb().from('finance_transactions').update({archived_at:null}).eq('id',id).not('archived_at','is',null);if(error)throw error},
 async uploadFinanceReceipt(userId:string,file:File){const path=`${userId}/${crypto.randomUUID()}-${file.name}`;const {error}=await requireDb().storage.from('finance-receipts').upload(path,file);if(error)throw error;return path},
 async signedFinanceReceipt(path:string){const {data,error}=await requireDb().storage.from('finance-receipts').createSignedUrl(path,300);if(error)throw error;return data.signedUrl},
 async financeInvoices(){const r=requireDb();const {data,error}=await r.from('finance_invoices').select('*,finance_invoice_items(*),finance_invoice_payments(*)').is('archived_at',null).order('created_at',{ascending:false});if(error)throw error;return data||[]},
 async financeInvoice(id:string){const {data,error}=await requireDb().from('finance_invoices').select('*,finance_invoice_items(*),finance_invoice_payments(*,finance_accounts(name))').eq('id',id).single();if(error)throw error;return data},
 async createFinanceInvoice(payload:any,items:any[]){const r=requireDb();const {data,error}=await r.from('finance_invoices').insert(payload).select().single();if(error)throw error;const result=await r.from('finance_invoice_items').insert(items.map(item=>({...item,invoice_id:data.id})));if(result.error)throw result.error;return data},
 async updateFinanceInvoice(id:string,patch:any){const {data,error}=await requireDb().from('finance_invoices').update(patch).eq('id',id).eq('status','draft').select().single();if(error)throw error;return data},
 async recordInvoicePayment(payload:any){const {data,error}=await requireDb().from('finance_invoice_payments').insert(payload).select().single();if(error)throw error;return data},
 async payrollRuns(){const {data,error}=await requireDb().from('payroll_runs').select('*,payroll_entries(*)').order('period_start',{ascending:false});if(error)throw error;return data||[]},
 async salarySettings(){const {data,error}=await requireDb().from('employee_salary_settings').select('*,profile:profiles(full_name,email,employee_code,designation,status,department:departments(name))').order('updated_at',{ascending:false});if(error)throw error;return data||[]},
 async saveSalarySetting(payload:any){const {data,error}=await requireDb().from('employee_salary_settings').upsert(payload,{onConflict:'profile_id'}).select().single();if(error)throw error;return data},
 async createPayrollRun(payload:any,entries:any[]){const r=requireDb();const {data,error}=await r.from('payroll_runs').insert(payload).select().single();if(error)throw error;const result=await r.from('payroll_entries').insert(entries.map(item=>({...item,payroll_run_id:data.id})));if(result.error)throw result.error;return data},
 async payrollRun(id:string){const {data,error}=await requireDb().from('payroll_runs').select('*,payroll_entries(*,profile:profiles(full_name,email,employee_code,designation,department:departments(name)))').eq('id',id).single();if(error)throw error;return data},
 async updatePayrollRun(id:string,patch:any){const {data,error}=await requireDb().from('payroll_runs').update(patch).eq('id',id).select().single();if(error)throw error;return data},
 async updatePayrollEntry(id:string,patch:any){const {data,error}=await requireDb().from('payroll_entries').update(patch).eq('id',id).select().single();if(error)throw error;return data},
 async removePayrollEntry(id:string){const {error}=await requireDb().from('payroll_entries').delete().eq('id',id).eq('payment_status','draft');if(error)throw error},
 async payPayrollEntry(entry:any,payment:any,actorId:string){if(entry.finance_transaction_id||entry.payment_status==='paid')throw new Error('This salary has already been paid.');const r=requireDb();const net=Number(entry.basic_salary)+Number(entry.allowances)-Number(entry.deductions);const {data:ledger,error:ledgerError}=await r.from('finance_transactions').insert({transaction_type:'payroll_payment',account_id:payment.account_id,amount:net,transaction_date:payment.payment_date,payment_method:payment.payment_method,reference_number:payment.payment_reference||null,description:`Salary payment: ${entry.profile?.full_name||'Employee'}`,created_by:actorId}).select().single();if(ledgerError)throw ledgerError;const {data,error}=await r.from('payroll_entries').update({payment_status:'paid',payment_date:payment.payment_date,payment_method:payment.payment_method,payment_reference:payment.payment_reference||null,finance_transaction_id:ledger.id}).eq('id',entry.id).is('finance_transaction_id',null).select().single();if(error)throw error;return data},
 async financeReport(){const r=requireDb();const [transactions,invoices,payroll]=await Promise.all([r.from('finance_transactions').select('*,account:finance_accounts(name),income_category:finance_income_categories(name),expense_category:finance_expense_categories(name)').is('archived_at',null).order('transaction_date',{ascending:false}),r.from('finance_invoices').select('*,finance_invoice_payments(*)').is('archived_at',null),r.from('payroll_entries').select('*,profile:profiles(full_name,employee_code),payroll_run:payroll_runs(period_start,period_end)')]);for(const x of [transactions,invoices,payroll])if(x.error)throw x.error;return {transactions:transactions.data||[],invoices:invoices.data||[],payroll:payroll.data||[]}},
 async superAdminDashboard(){const r=requireDb();const today=new Date().toISOString().slice(0,10);const [employees,present,onLeave,pendingLeave,openTasks,overdueTasks,pendingDocuments,unreadNotifications,leads,followups,hotLeads,sales]=await Promise.all([
  r.from('profiles').select('*',{count:'exact',head:true}).eq('status','active'),
  r.from('attendance').select('*',{count:'exact',head:true}).eq('work_date',today).not('clock_in','is',null),
  r.from('leave_requests').select('*',{count:'exact',head:true}).eq('status','approved').lte('starts_on',today).gte('ends_on',today),
  r.from('leave_requests').select('*',{count:'exact',head:true}).eq('status','pending'),
  r.from('tasks').select('*',{count:'exact',head:true}).neq('status','completed'),
  r.from('tasks').select('*',{count:'exact',head:true}).neq('status','completed').lt('due_date',today),
  r.from('document_requests').select('*',{count:'exact',head:true}).in('status',['requested','submitted']),
  r.from('notifications').select('*',{count:'exact',head:true}).is('read_at',null),
  r.from('crm_leads').select('*',{count:'exact',head:true}).is('archived_at',null),
  r.from('crm_lead_followups').select('*',{count:'exact',head:true}).eq('next_follow_up_at',today),
  r.from('crm_leads').select('*',{count:'exact',head:true}).eq('temperature','hot').is('archived_at',null),
  r.from('crm_sales').select('*',{count:'exact',head:true}),
 ]);const results=[employees,present,onLeave,pendingLeave,openTasks,overdueTasks,pendingDocuments,unreadNotifications,leads,followups,hotLeads,sales];const failed=results.find((item:any)=>item.error);if(failed)throw failed.error;return {employees:employees.count||0,presentToday:present.count||0,onLeave:onLeave.count||0,pendingLeave:pendingLeave.count||0,openTasks:openTasks.count||0,overdueTasks:overdueTasks.count||0,pendingDocuments:pendingDocuments.count||0,unreadNotifications:unreadNotifications.count||0,leads:leads.count||0,followupsDue:followups.count||0,hotLeads:hotLeads.count||0,sales:sales.count||0}},
 async employees(query='',page=0,size=10){const r=requireDb();const from=page*size;let q=r.from('profiles').select('id,full_name,email,role,designation,department_id,manager_id,status',{count:'exact'}).order('full_name').range(from,from+size-1);if(query)q=q.ilike('full_name',`%${query}%`);const {data,error,count}=await q;if(error)throw error;return {data:data as Employee[],count:count??0}},
 async employeeProfile(id:string){const r=requireDb();const {data,error}=await r.from('profiles').select('id,full_name,email,phone,personal_email,date_of_birth,gender,address,emergency_contact,employee_code,designation,role,status,joining_date,avatar_url,manager_id,department:departments(name)').eq('id',id).single();if(error)throw error;let manager=null;if(data.manager_id){const result=await r.from('profiles').select('full_name').eq('id',data.manager_id).maybeSingle();if(result.error)throw result.error;manager=result.data}return {...data,manager}},
 async departments(){const {data,error}=await requireDb().from('departments').select('id,name').order('name');if(error)throw error;return data as Department[]},
 async designations(){const {data,error}=await requireDb().from('designations').select('id,name,department_id').order('name');if(error)throw error;return data as Designation[]},
 async createDepartment(name:string){const {error}=await requireDb().from('departments').insert({name});if(error)throw error},
 async createDesignation(name:string,department_id:string){const {error}=await requireDb().from('designations').insert({name,department_id:department_id||null});if(error)throw error},
 async updateEmployee(id:string,patch:Partial<Employee>){const {error}=await requireDb().from('profiles').update(patch).eq('id',id);if(error)throw error},
 async deactivateEmployee(id:string){const {error}=await requireDb().from('profiles').update({status:'inactive'}).eq('id',id);if(error)throw error},
 async audit(){const {data,error}=await requireDb().from('audit_logs').select('id,action,entity_type,created_at,actor_id').order('created_at',{ascending:false}).limit(30);if(error)throw error;return data as AuditLog[]}
 ,async accessCatalogue(){const r=requireDb();const [roles,permissions,grants,employees,audit]=await Promise.all([r.from('roles').select('id,code,name').order('name'),r.from('permissions').select('id,code,description').order('code'),r.from('user_permission_grants').select('*,profile:profiles!user_permission_grants_profile_id_fkey(id,full_name,email,status,role,department:departments(name)),granter:profiles!user_permission_grants_granted_by_fkey(full_name),permission:permissions!user_permission_grants_permission_id_fkey(id,code,description)').order('granted_at',{ascending:false}),r.from('profiles').select('id,full_name,email,status,role,department:departments(name)').eq('status','active').order('full_name'),r.from('audit_logs').select('id,action,entity_type,entity_id,actor_id,created_at,before_data,after_data').order('created_at',{ascending:false}).limit(12)]);for(const result of [roles,permissions,grants,employees])if(result.error)throw result.error;let rolePermissions=await r.from('role_permissions').select('role_id,permission_id');let rolePermissionMode:'id'|'legacy'='id';if(rolePermissions.error){const legacy=await r.from('role_permissions').select('role,permission_id');if(legacy.error)throw legacy.error;rolePermissionMode='legacy';rolePermissions={data:(legacy.data||[]).map((item:any)=>({role_key:item.role,permission_id:item.permission_id})),error:null} as any}else rolePermissions={data:(rolePermissions.data||[]).map((item:any)=>({role_key:item.role_id,permission_id:item.permission_id})),error:null} as any;return {roles:roles.data||[],permissions:permissions.data||[],rolePermissions:rolePermissions.data||[],rolePermissionMode,grants:grants.data||[],employees:employees.data||[],audit:audit.error?[]:audit.data||[]}}
 ,async setRolePermission(roleKey:string,permissionId:string,enabled:boolean,mode:'id'|'legacy'='id'){const r=requireDb();if(mode==='legacy'){if(enabled){const {error}=await r.from('role_permissions').upsert({role:roleKey,permission_id:permissionId});if(error)throw error}else{const {error}=await r.from('role_permissions').delete().eq('role',roleKey).eq('permission_id',permissionId);if(error)throw error}return}if(enabled){const {error}=await r.from('role_permissions').upsert({role_id:roleKey,permission_id:permissionId});if(error)throw error}else{const {error}=await r.from('role_permissions').delete().eq('role_id',roleKey).eq('permission_id',permissionId);if(error)throw error}}
 ,async grantPermission(payload:{profile_id:string;permission_id:string;granted_by:string;starts_at:string;expires_at:string|null;reason:string}){const target=await this.activeEmployeeByEmailOrId(payload.profile_id);if(!target||target.status!=='active')throw new Error('Access can only be granted to an active employee.');const {data,error}=await requireDb().from('user_permission_grants').insert({...payload,expires_at:payload.expires_at||null,reason:payload.reason||null}).select().single();if(error)throw error;return data}
 ,async activeEmployeeByEmailOrId(value:string){const r=requireDb();const {data,error}=await r.from('profiles').select('id,full_name,email,status').or(`id.eq.${value},email.ilike.${value}`).maybeSingle();if(error)throw error;return data}
 ,async revokePermission(id:string,revoked_by:string){const {data,error}=await requireDb().from('user_permission_grants').update({revoked_at:new Date().toISOString(),revoked_by}).eq('id',id).is('revoked_at',null).select().single();if(error)throw error;return data}
 ,async taskPermissionGrants(){const {data,error}=await requireDb().from('user_permission_grants').select('*,profile:profiles!user_permission_grants_profile_id_fkey(id,full_name,email,status),granter:profiles!user_permission_grants_granted_by_fkey(full_name),permission:permissions!user_permission_grants_permission_id_fkey(code)').order('granted_at',{ascending:false});if(error)throw error;return (data||[]).filter((grant:any)=>['tasks.assign','tasks.manage_access'].includes(grant.permission?.code))}
 ,async recordExpiredTaskPermissions(){const {error}=await requireDb().rpc('record_expired_task_permissions');if(error)throw error}
 ,async activeEmployeeByEmail(email:string){const {data,error}=await requireDb().from('profiles').select('id,full_name,email,status').ilike('email',email.trim()).maybeSingle();if(error)throw error;return data}
 ,async searchActiveEmployees(query:string){const term=query.trim();if(!term)return [];const {data,error}=await requireDb().from('profiles').select('id,full_name,email,status').eq('status','active').or(`full_name.ilike.%${term}%,email.ilike.%${term}%`).order('full_name').limit(10);if(error)throw error;return data}
 ,async grantTaskPermission(payload:{profile_id:string;permissionCode:'tasks.assign'|'tasks.manage_access';granted_by:string;starts_at:string;expires_at:string|null;reason:string}){const r=requireDb();const {data:permission,error:permissionError}=await r.from('permissions').select('id').eq('code',payload.permissionCode).single();if(permissionError)throw permissionError;const {data,error}=await r.from('user_permission_grants').insert({profile_id:payload.profile_id,permission_id:permission.id,granted_by:payload.granted_by,starts_at:payload.starts_at,expires_at:payload.expires_at||null,reason:payload.reason||null}).select().single();if(error)throw error;return data}
 ,async revokeTaskPermission(id:string,revoked_by:string){const {data,error}=await requireDb().from('user_permission_grants').update({revoked_at:new Date().toISOString(),revoked_by}).eq('id',id).is('revoked_at',null).select().single();if(error)throw error;return data}
 ,async tasks(filters:{employee?:string;status?:string;priority?:string;dueDate?:string}={}){const r=requireDb();let q=r.from('tasks').select('*').order('due_date');if(filters.status)q=q.eq('status',filters.status);if(filters.priority)q=q.eq('priority',filters.priority);if(filters.dueDate)q=q.eq('due_date',filters.dueDate);const {data:tasks,error}=await q;if(error)throw new Error('Tasks could not be loaded. Please try again.');const ids=(tasks||[]).map((task:any)=>task.id);if(!ids.length)return [];const [{data:assignments,error:assignmentError},{data:comments,error:commentError}]=await Promise.all([r.from('task_assignments').select('id,task_id,profile_id,status,updated_at').in('task_id',ids),r.from('task_comments').select('id,task_id,author_id,body,created_at').in('task_id',ids).order('created_at')]);if(assignmentError||commentError)throw new Error('Tasks could not be loaded. Please try again.');const peopleIds=[...new Set([...(assignments||[]).map((item:any)=>item.profile_id),...(comments||[]).map((item:any)=>item.author_id),...(tasks||[]).map((item:any)=>item.created_by)].filter(Boolean))];const {data:people,error:peopleError}=peopleIds.length?await r.from('profiles').select('id,full_name').in('id',peopleIds):{data:[],error:null};if(peopleError)throw new Error('Tasks could not be loaded. Please try again.');const names=new Map((people||[]).map((person:any)=>[person.id,person]));const mapped=(tasks||[]).map((task:any)=>({...task,created_by_profile:names.get(task.created_by)||null,task_assignments:(assignments||[]).filter((item:any)=>item.task_id===task.id).map((item:any)=>({...item,profile:names.get(item.profile_id)||null})),task_comments:(comments||[]).filter((item:any)=>item.task_id===task.id).map((item:any)=>({...item,author_profile:names.get(item.author_id)||null}))}));return filters.employee?mapped.filter((task:any)=>task.task_assignments.some((assignment:any)=>assignment.profile_id===filters.employee)):mapped}
 ,async createTask(payload:{title:string;description:string;priority:string;due_date:string;assigneeIds:string[];created_by:string}){const r=requireDb();const {data,error}=await r.from('tasks').insert({title:payload.title,description:payload.description||null,priority:payload.priority,due_date:payload.due_date||null,created_by:payload.created_by,assignee_id:payload.assigneeIds[0]||null,status:'todo'}).select().single();if(error)throw error;const assignments=await r.from('task_assignments').insert(payload.assigneeIds.map(profile_id=>({task_id:data.id,profile_id,status:'todo'})));if(assignments.error)throw assignments.error;return data}
 ,async updateTask(id:string,payload:{title:string;description:string;priority:string;due_date:string;status:string}){const {data,error}=await requireDb().from('tasks').update(payload).eq('id',id).select().single();if(error)throw error;return data}
 ,async setTaskAssignees(taskId:string,assigneeIds:string[]){const r=requireDb();const {data:current,error:currentError}=await r.from('task_assignments').select('id,profile_id').eq('task_id',taskId);if(currentError)throw currentError;const wanted=[...new Set(assigneeIds)];const remove=(current||[]).filter((item:any)=>!wanted.includes(item.profile_id));if(remove.length){const deleted=await r.from('task_assignments').delete().in('id',remove.map((item:any)=>item.id));if(deleted.error)throw deleted.error}const existing=new Set((current||[]).map((item:any)=>item.profile_id));const additions=wanted.filter(id=>!existing.has(id));if(additions.length){const inserted=await r.from('task_assignments').insert(additions.map(profile_id=>({task_id:taskId,profile_id,status:'todo'})));if(inserted.error)throw inserted.error}}
 ,async setTaskStatus(id:string,status:string){const {data,error}=await requireDb().from('tasks').update({status}).eq('id',id).select().single();if(error)throw error;return data}
 ,async documents(){const {data,error}=await requireDb().from('documents').select('*,document_shares(*)').order('created_at',{ascending:false});if(error)throw error;return data}
 ,async documentRequests(){const {data,error}=await requireDb().from('document_requests').select('*,employee:profiles!document_requests_profile_id_fkey(full_name),document_submissions(*)').order('created_at',{ascending:false});if(error)throw error;return data}
 ,async createCompanyDocument(payload:{title:string;description:string;category:string;storage_path:string;file_name:string;mime_type:string;file_size:number;uploaded_by:string;profileIds:string[]}){const r=requireDb();const {data,error}=await r.from('documents').insert(payload).select().single();if(error)throw error;const shares=payload.profileIds.length?payload.profileIds.map(profile_id=>({document_id:data.id,profile_id,shared_with_all:false})):[{document_id:data.id,profile_id:null,shared_with_all:true}];const result=await r.from('document_shares').insert(shares);if(result.error)throw result.error;return data}
 ,async requestDocument(payload:{title:string;description:string;due_date:string;profile_id:string;requested_by:string}){const {data,error}=await requireDb().from('document_requests').insert({...payload,due_date:payload.due_date||null}).select().single();if(error)throw error;return data}
 ,async reviewDocumentRequest(id:string,status:'approved'|'rejected',admin_comment:string,reviewerId:string){const {data,error}=await requireDb().from('document_requests').update({status,admin_comment:admin_comment||null,reviewer_id:reviewerId,reviewed_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data}
 ,async uploadCompanyDocument(userId:string,file:File){const path=`company/${userId}/${crypto.randomUUID()}-${file.name}`;const {error}=await requireDb().storage.from('employee-documents').upload(path,file);if(error)throw error;return {path,fileName:file.name,mimeType:file.type||'',fileSize:file.size}}
 ,async announcements(){const {data,error}=await requireDb().from('announcements').select('*,announcement_recipients(*),announcement_reads(count)').order('created_at',{ascending:false});if(error)throw error;return data}
 ,async createAnnouncement(payload:{title:string;body:string;category:string;status:string;is_pinned:boolean;audience_type:string;department_id:string|null;published_at:string|null;expires_at:string|null;author_id:string;profileIds:string[]}){const r=requireDb();const {data,error}=await r.from('announcements').insert({...payload,published_at:payload.published_at||new Date().toISOString(),expires_at:payload.expires_at||null}).select().single();if(error)throw error;if(payload.audience_type==='employees'&&payload.profileIds.length){const shares=await r.from('announcement_recipients').insert(payload.profileIds.map(profile_id=>({announcement_id:data.id,profile_id})));if(shares.error)throw shares.error}return data}
 ,async updateAnnouncement(id:string,payload:{title:string;body:string;category:string;status:string;is_pinned:boolean;expires_at:string|null}){const {data,error}=await requireDb().from('announcements').update(payload).eq('id',id).select().single();if(error)throw error;return data}
 ,async archiveAnnouncement(id:string){const {error}=await requireDb().from('announcements').update({status:'archived'}).eq('id',id);if(error)throw error}
 ,async notifications(){const {data,error}=await requireDb().from('notifications').select('*,recipient:profiles!notifications_profile_id_fkey(full_name)').order('created_at',{ascending:false}).limit(100);if(error)throw error;return data}
 ,async crmLookups(){const r=requireDb();const [sources,statuses]=await Promise.all([r.from('crm_lead_sources').select('*').eq('is_active',true).order('name'),r.from('crm_lead_statuses').select('*').eq('is_active',true).order('sort_order')]);if(sources.error)throw sources.error;if(statuses.error)throw statuses.error;return {sources:sources.data,statuses:statuses.data}}
 ,async crmLeads(){const {data,error}=await requireDb().from('crm_leads').select('*,source:crm_lead_sources(name),status:crm_lead_statuses(name),assignee:profiles!crm_leads_assigned_to_fkey(full_name),crm_lead_followups(*)').is('archived_at',null).order('updated_at',{ascending:false});if(error)throw error;return data}
 ,async createLead(payload:any){const {data,error}=await requireDb().from('crm_leads').insert(payload).select().single();if(error)throw error;return data}
 ,async addLeadFollowup(payload:any){const {data,error}=await requireDb().from('crm_lead_followups').insert(payload).select().single();if(error)throw error;return data}
 ,async convertLead(payload:any){const r=requireDb();const {data,error}=await r.from('crm_sales').insert(payload).select().single();if(error)throw error;const update=await r.from('crm_leads').update({converted_at:new Date().toISOString()}).eq('id',payload.lead_id);if(update.error)throw update.error;return data}
 ,async crmLead(id:string){const {data,error}=await requireDb().from('crm_leads').select('*,source:crm_lead_sources(name),status:crm_lead_statuses(name),assignee:profiles!crm_leads_assigned_to_fkey(full_name),crm_lead_followups(*,profiles(full_name)),crm_sales(*)').eq('id',id).single();if(error)throw error;return data}
 ,async updateLead(id:string,patch:any){const {data,error}=await requireDb().from('crm_leads').update(patch).eq('id',id).select().single();if(error)throw error;return data}
 ,async archiveLead(id:string){const {error}=await requireDb().from('crm_leads').update({archived_at:new Date().toISOString()}).eq('id',id);if(error)throw error}
 ,async crmSales(){const {data,error}=await requireDb().from('crm_sales').select('*,crm_leads(full_name,phone,assigned_to,source:crm_lead_sources(name))').order('closing_date',{ascending:false});if(error)throw error;return data}
 ,async updateSale(id:string,patch:any){const {data,error}=await requireDb().from('crm_sales').update(patch).eq('id',id).select().single();if(error)throw error;return data}
 ,async createCrmImportBatch(payload:any){const {data,error}=await requireDb().from('crm_import_batches').insert(payload).select().single();if(error)throw error;return data}
 ,async updateCrmImportBatch(id:string,patch:any){const {error}=await requireDb().from('crm_import_batches').update(patch).eq('id',id);if(error)throw error}
 ,async createCrmImportRows(rows:any[]){const {error}=await requireDb().from('crm_import_rows').insert(rows);if(error)throw error}
 ,async findCrmLead(full_name:string,phone:string){const {data,error}=await requireDb().from('crm_leads').select('id').eq('phone',phone).ilike('full_name',full_name).limit(1);if(error)throw error;return data?.[0]??null}
};
