export type AttendanceSettings={timezone:string;work_start:string;work_end:string;grace_minutes:number;overtime_after_minutes:number;working_days:number[]};
export type AttendanceDuration={minutes:number|null;isLive:boolean;isIncomplete:boolean;needsReview:boolean};
export type AttendanceDurationOptions={timeZone?:string;workDate?:string|null;now?:Date;activeBreakStartedAt?:string|null};
export const dateKey=(date:Date,timeZone:string)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
export const monthBounds=(date:Date,timeZone:string)=>{const key=dateKey(date,timeZone);const [year,month]=key.split('-').map(Number);const last=new Date(Date.UTC(year,month,0));return {from:`${year}-${String(month).padStart(2,'0')}-01`,to:dateKey(last,timeZone)}};
export const weekday=(date:Date,timeZone:string)=>({Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7}[new Intl.DateTimeFormat('en-US',{timeZone,weekday:'short'}).format(date)]??0);
export function classify(day:Date,row:any,settings:AttendanceSettings,holidays:Set<string>,leave=false){const key=dateKey(day,settings.timezone);if(key>dateKey(new Date(),settings.timezone))return 'future';if(holidays.has(key))return 'holiday';if(!settings.working_days.includes(weekday(day,settings.timezone)))return 'weekend';if(leave)return 'leave';if(!row?.clock_in)return 'absent';return 'present'}
export const canClockIn=(status:string)=>!['future','holiday','weekend','leave'].includes(status);
/** The canonical display calculation: only an open session on its business day is live. */
export function attendanceDuration(row:any,{timeZone='Asia/Kolkata',workDate=row?.work_date??null,now=new Date(),activeBreakStartedAt=null}:AttendanceDurationOptions={}):AttendanceDuration{if(!row?.clock_in)return {minutes:null,isLive:false,isIncomplete:false,needsReview:false};const start=new Date(row.clock_in).getTime();const isLive=!row.clock_out&&workDate===dateKey(now,timeZone);const end=row.clock_out?new Date(row.clock_out).getTime():isLive?now.getTime():null;if(end===null)return {minutes:null,isLive:false,isIncomplete:true,needsReview:false};const elapsed=Math.floor((end-start)/60000);if(!Number.isFinite(elapsed)||elapsed<0||elapsed>24*60)return {minutes:null,isLive,isIncomplete:false,needsReview:true};const openBreakMinutes=!row.clock_out&&activeBreakStartedAt?Math.max(0,Math.floor((end-new Date(activeBreakStartedAt).getTime())/60000)):0;return {minutes:Math.max(0,elapsed-Number(row.break_minutes??0)-openBreakMinutes),isLive,isIncomplete:false,needsReview:false}}
/** Numeric adapter for aggregates; unresolved or implausible records contribute zero. */
export function minutes(row:any,options?:AttendanceDurationOptions){return attendanceDuration(row,options).minutes??0}
export function monthlyDays(month:Date,settings:AttendanceSettings,records:any[],holidays:Set<string>,leaves:any[]){const {from,to}=monthBounds(month,settings.timezone);const days=[];for(let d=new Date(`${from}T12:00:00Z`);dateKey(d,settings.timezone)<=to;d.setUTCDate(d.getUTCDate()+1)){const key=dateKey(d,settings.timezone),row=records.find(r=>r.work_date===key),leave=leaves.some(l=>l.starts_on<=key&&l.ends_on>=key);days.push({key,row,status:classify(d,row,settings,holidays,leave)})}return days}
