import {describe,expect,it} from 'vitest';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';
const source=readFileSync(resolve(process.cwd(),'src/lib/calendar-meeting-repository.ts'),'utf8');const migration=readFileSync(resolve(process.cwd(),'supabase/migrations/20260814071316_meetings_and_minutes.sql'),'utf8');
describe('calendar meeting repository security contract',()=>{
  it('uses RLS-scoped meeting reads and trusted RPC writes',()=>{expect(source).toContain("from('meetings').select(meetingSelect)");expect(source).toContain(".rpc('save_meeting'");expect(source).toContain(".rpc('cancel_meeting'");expect(source).not.toMatch(/from\('meetings'\)\.(insert|update|delete)/)});
  it('loads only active visible workforce and server-approved hosts',()=>{expect(source).toContain(".eq('workforce_visible',true).eq('status','active')");expect(source).toContain(".rpc('meeting_hosts'");expect(migration).toContain('returns table(id uuid,full_name text,designation text,department_name text)')});
  it('returns only privacy-safe availability fields',()=>{expect(source).toContain('type: item.conflict_kind');expect(source).not.toContain('conflict_title');expect(source).not.toContain('conflict_reason');expect(migration).not.toContain('conflict_title');expect(migration).toContain("Permission denied for meeting availability")});
  it('keeps personal calendar blocks self-scoped',()=>{expect(source).toContain(".eq('employee_id', userId)");expect(source).toContain(".eq('id', id).eq('employee_id', userId)")});
  it('sends host and participant IDs only to the trusted save RPC',()=>{expect(source).toContain(".rpc('save_meeting'");expect(migration).toContain('host_profile_id uuid,participant_ids uuid[]');expect(migration).toContain("if not public.meeting_host_allowed(host_profile_id)")});
  it('saves minutes through one transactional RPC',()=>{expect(source).toContain(".rpc('save_meeting_minutes'");expect(migration).toContain('delete from public.meeting_decisions');expect(migration).toContain('delete from public.meeting_action_items')});
});
