import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const source = readFileSync(resolve(process.cwd(), 'src/lib/calendar-meeting-repository.ts'), 'utf8');
const migration = readFileSync(resolve(process.cwd(), 'supabase/migrations/20260811051945_personal_calendar_and_meetings.sql'), 'utf8');
const saveMeetingFix = readFileSync(resolve(process.cwd(), 'supabase/migrations/20260811120000_fix_save_meeting_candidate_alias.sql'), 'utf8');
describe('calendar meeting repository security contract', () => {
  it('scopes blocks and visible meetings to the current employee', () => { expect(source).toContain(".eq('employee_id',userId)"); expect(source).toContain(".from('meeting_participants').select('meeting_id').eq('employee_id',userId)"); expect(source).toContain('organizer_id.eq.${userId},id.in.('); });
  it('creates, edits, and removes only the logged-in employee’s blocks', () => { expect(source).toContain('createMyBlock(userId:string'); expect(source).toContain('employee_id:userId'); expect(source).toContain('updateMyBlock(userId:string,id:string'); expect(source).toContain(".eq('id',id).eq('employee_id',userId)"); expect(source).toContain('removeMyBlock(userId:string,id:string'); });
  it('combines blocks and scheduled meetings without creating database duplicates', () => { expect(source).toContain("kind:'blocked'"); expect(source).toContain("kind:'meeting'"); expect(source).toContain("x.status==='scheduled'"); });
  it('uses only trusted RPC write paths for meetings', () => { expect(source).toContain(".rpc('save_meeting'"); expect(source).toContain(".rpc('cancel_meeting'"); expect(source).not.toMatch(/from\('meetings'\)\.(insert|update|delete)/); });
  it('returns only privacy-safe availability fields', () => { expect(source).toContain("type:x.conflict_kind,start_at:x.conflict_start,end_at:x.conflict_end"); expect(source).not.toContain('conflict_title'); expect(source).not.toContain('reason'); expect(source).not.toContain('notes'); });
  it('keeps management authorization server-side', () => { expect(source).toContain(".rpc('save_meeting'"); expect(source).toContain(".rpc('cancel_meeting'"); });
  it('does not combine parent and embedded-table filters in one PostgREST or expression', () => { expect(source).not.toContain('meeting_participants.employee_id.eq.${userId}'); expect(source).toContain('const meetingIds=new Set<string>()'); });
  it('passes an edit exclusion to the trusted availability RPC without changing create behavior', () => { expect(source).toContain("ignored_meeting:ignore||null"); expect(source).toContain('async availability(start_at:string,end_at:string,employee_ids:string[],ignore?:string)'); });
  it('enforces self-conflict exclusion and external interval conflicts in the trusted SQL layer', () => { expect(migration).toContain('ignored_meeting uuid default null'); expect(migration).toContain('(ignored_meeting is null or m.id <> ignored_meeting)'); expect(migration).toContain("tstzrange(m.start_at,m.end_at,'[)') && tstzrange(proposed_start,proposed_end,'[)')"); expect(migration).toContain("tstzrange(b.start_at,b.end_at,'[)') && tstzrange(proposed_start,proposed_end,'[)')"); });
  it('does not expose private block reasons or hidden meeting titles through availability', () => { expect(source).not.toContain('conflict_title'); expect(source).not.toContain('reason'); expect(source).not.toContain('notes'); });
  it('authorizes updates in the trusted function and rejects unauthorized direct RPC updates', () => { expect(migration).toContain("target_meeting is not null and not exists (select 1 from public.meetings where id=target_meeting and (organizer_id=auth.uid() or public.has_permission('meetings.manage')))"); expect(migration).toContain("raise exception 'Permission denied for meeting update'"); });
  it('rechecks availability before changing an existing meeting', () => { const check = migration.indexOf('from public.meeting_conflicts(meeting_start,meeting_end,ids,target_meeting)'); const update = migration.indexOf('update public.meetings set title=trim(meeting_title)'); expect(check).toBeGreaterThan(-1); expect(update).toBeGreaterThan(check); });
  it('leaves the existing meeting unchanged when the trusted conflict check rejects', () => { const rejection = migration.indexOf("if conflicts is not null then raise exception"); const update = migration.indexOf('update public.meetings set title=trim(meeting_title)'); expect(rejection).toBeGreaterThan(-1); expect(update).toBeGreaterThan(rejection); });
  it('synchronizes added, removed, and existing participants transactionally', () => { expect(migration).toContain('delete from public.meeting_participants where meeting_id=result_id'); expect(migration).toContain('insert into public.meeting_participants(meeting_id,employee_id) select result_id, unnest(ids)'); });
  it('keeps participant rows unique and includes the organizer once by established design', () => { expect(migration).toContain('ids := array(select distinct value from unnest(array_append'); expect(migration).toContain("coalesce(participant_ids,'{}'::uuid[]), auth.uid()"); expect(migration).toContain('primary key (meeting_id, employee_id)'); });
  it('qualifies the invitee validation alias so save_meeting runs without an ambiguous id reference', () => { expect(migration).toContain('unnest(ids) as candidate(employee_id)'); expect(saveMeetingFix).toContain('p.id=candidate.employee_id'); expect(saveMeetingFix).not.toMatch(/unnest\(ids\) id/); });
  it('keeps My Calendar relationship-derived after participant synchronization', () => { expect(source).toContain('this.myMeetings(userId)'); expect(source).toContain("x.status==='scheduled'"); expect(migration).not.toMatch(/insert into public\.calendar_blocks[\s\S]*save_meeting/); });
  it('cannot reactivate a cancelled meeting through an ordinary metadata update', () => { const update = migration.match(/update public\.meetings set title=trim\(meeting_title\)[^;]+;/)?.[0] ?? ''; expect(update).not.toContain('status='); expect(source).toContain("x.status==='scheduled'"); });
});
