import { supabase } from './supabase';
export type AvailabilityConflict={type:'blocked'|'meeting';start_at:string;end_at:string}; export type InviteeAvailability={employee_id:string;available:boolean;conflicts:AvailabilityConflict[]};
/** Hydrated through meeting_participants_employee_id_fkey in myMeetings. */
export type MeetingParticipantRecord={employee_id:unknown;participant?:{id?:string;full_name?:string|null;designation?:string|null}|null};
export type CalendarBlockPayload={start_at:string;end_at:string;all_day:boolean;title:string|null};
const db=()=>{if(!supabase)throw new Error('Supabase is not configured.');return supabase as any};
export const calendarMeetingRepository={
 async meetingPermissions(){const codes=['meetings.view','meetings.create','meetings.manage'];const results=await Promise.all(codes.map(code=>db().rpc('has_permission',{permission_code:code})));for(const r of results)if(r.error)throw r.error;return Object.fromEntries(codes.map((code,index)=>[code,results[index].data===true])) as Record<string,boolean>},
 async meetingEmployees(query=''){const result=await db().rpc('meeting_workforce');if(result.error)throw result.error;const search=query.trim().toLowerCase();return (result.data||[]).map((person:any)=>({...person,department:person.department_name?{name:person.department_name}:null})).filter((person:any)=>!search||[person.full_name,person.designation].filter(Boolean).some((value:string)=>value.toLowerCase().includes(search)))},
 async meetingHosts(){const result=await db().rpc('meeting_hosts');if(result.error)throw result.error;return result.data||[]},
 async myBlocks(userId:string){const r=await db().from('calendar_blocks').select('*').eq('employee_id',userId).order('start_at');if(r.error)throw r.error;return r.data||[]},
 async createMyBlock(userId:string,payload:CalendarBlockPayload){const r=await db().from('calendar_blocks').insert({...payload,employee_id:userId}).select().single();if(r.error)throw r.error;return r.data},
 async updateMyBlock(userId:string,id:string,payload:CalendarBlockPayload){const r=await db().from('calendar_blocks').update(payload).eq('id',id).eq('employee_id',userId).select().single();if(r.error)throw r.error;return r.data},
 async removeMyBlock(userId:string,id:string){const r=await db().from('calendar_blocks').delete().eq('id',id).eq('employee_id',userId).select('id').single();if(r.error)throw r.error;return r.data},
 async myMeetings(userId:string){const membership=await db().from('meeting_participants').select('meeting_id').eq('employee_id',userId);if(membership.error)throw membership.error;const visibleIds=new Set<string>();for(const row of membership.data||[])if(typeof row.meeting_id==='string'&&row.meeting_id)visibleIds.add(row.meeting_id);let query=db().from('meetings').select('*').order('start_at');query=visibleIds.size?query.or(`organizer_id.eq.${userId},id.in.(${[...visibleIds].join(',')})`):query.eq('organizer_id',userId);const meetings=await query;if(meetings.error)throw meetings.error;const rows=meetings.data||[];const meetingIds=rows.map((row:any)=>row.id).filter(Boolean);if(!meetingIds.length)return rows;const participants=await db().from('meeting_participants').select('meeting_id,employee_id,participant:profiles!meeting_participants_employee_id_fkey(id,full_name,designation)').in('meeting_id',meetingIds);if(participants.error)throw participants.error;const organizerIds=[...new Set(rows.map((row:any)=>row.organizer_id).filter(Boolean))];const profiles=organizerIds.length?await db().from('profiles').select('id,full_name,designation').in('id',organizerIds):{data:[],error:null};if(profiles.error)throw profiles.error;const byProfileId=new Map((profiles.data||[]).map((profile:any)=>[profile.id,profile]));const participantsByMeeting=new Map<string,any[]>();for(const participant of participants.data||[]){const list=participantsByMeeting.get(participant.meeting_id)||[];list.push(participant);participantsByMeeting.set(participant.meeting_id,list)}return rows.map((meeting:any)=>({...meeting,organizer:byProfileId.get(meeting.organizer_id)||null,meeting_participants:participantsByMeeting.get(meeting.id)||[]}))},
 async myCalendar(userId:string){const [blocks,meetings]=await Promise.all([this.myBlocks(userId),this.myMeetings(userId)]);return [...blocks.map((x:any)=>({...x,kind:'blocked' as const})),...meetings.filter((x:any)=>x.status==='scheduled').map((x:any)=>({...x,kind:'meeting' as const}))].sort((a:any,b:any)=>a.start_at.localeCompare(b.start_at))},
 async availability(start_at:string,end_at:string,employee_ids:string[],ignore?:string){const r=await db().rpc('meeting_conflicts',{proposed_start:start_at,proposed_end:end_at,participant_ids:employee_ids,ignored_meeting:ignore||null});if(r.error)throw r.error;const by=new Map<string,AvailabilityConflict[]>();for(const x of r.data||[]){const list=by.get(x.employee_id)||[];list.push({type:x.conflict_kind,start_at:x.conflict_start,end_at:x.conflict_end});by.set(x.employee_id,list)}return employee_ids.map(employee_id=>({employee_id,available:!(by.get(employee_id)?.length),conflicts:by.get(employee_id)||[]})) as InviteeAvailability[]},
 async save(payload:any){const r=await db().rpc('save_meeting',payload);if(r.error)throw r.error;return r.data}, async cancel(id:string){const r=await db().rpc('cancel_meeting',{target_meeting:id});if(r.error)throw r.error;return r.data}
};
