import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {describe,expect,it} from 'vitest';
const migration=readFileSync(resolve(process.cwd(),'supabase/migrations/20260814071316_meetings_and_minutes.sql'),'utf8');const followUp=readFileSync(resolve(process.cwd(),'supabase/migrations/20260814153000_batch_7_remove_named_meeting_exception.sql'),'utf8');const list=readFileSync(resolve(process.cwd(),'src/app/employee/meetings/page.tsx'),'utf8');const detail=readFileSync(resolve(process.cwd(),'src/components/meeting-detail-workspace.tsx'),'utf8');const newRoute=readFileSync(resolve(process.cwd(),'src/app/admin/meetings/new/page.tsx'),'utf8');
describe('Batch 7 meeting access and host security',()=>{
  it('grants create and host only through canonical roles and permissions',()=>{expect(migration).toContain("role.code in ('director','general_manager')");expect(migration).toContain("permission.code in ('meetings.view','meetings.create','meetings.host','meetings.manage','meetings.notes')");expect(migration).toContain("role.code='chairman' and permission.code in ('meetings.create','meetings.host')")});
  it('never authorizes Diya by display name',()=>{expect(migration).not.toMatch(/full_name\s*=\s*'Diya/i);expect(list).not.toMatch(/name\s*===?\s*['"]Diya/i);expect(detail).not.toMatch(/name\s*===?\s*['"]Diya/i)});
  it('rejects Staff host tampering server-side',()=>{expect(migration).toContain("if not public.meeting_host_allowed(host_profile_id) then raise exception 'The selected employee is not an approved meeting host.'");expect(followUp).toContain("profile.role::text in ('director', 'general_manager')");expect(followUp).not.toContain("or profile.id=")});
  it('does not let meetings.manage implicitly create or host',()=>{expect(migration).toContain("target_meeting is null and not public.has_permission('meetings.create')");expect(migration).toContain("public.has_permission('meetings.host',profile.id)")});
  it('allows creator, host, and authorized management to edit/cancel',()=>{expect(migration).toContain('previous.organizer_id=actor or previous.host_user_id=actor');expect(migration).toContain('item.organizer_id=actor or item.host_user_id=actor')});
  it('denies unrelated direct IDs through membership RLS',()=>{expect(migration).toContain('public.meeting_visible(meeting_id)');expect(migration).toContain('participant.employee_id=(select auth.uid())');expect(migration).toContain('create policy "meeting notes member read"')});
  it('protects the direct create route',()=>{expect(newRoute).toContain("permission_code:'meetings.create'");expect(newRoute).toContain("redirect('/unauthorized')")});
  it('limits post-meeting note editing while participants retain read access',()=>{expect(migration).toContain('public.meeting_notes_editable(target_meeting)');expect(migration).toContain("meeting.status='scheduled' and meeting.end_at<=now()");expect(migration).toContain('meeting.host_user_id=(select auth.uid())');expect(detail).toContain('Only the approved host or meeting management can edit notes')});
});
