import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {describe,expect,it} from 'vitest';import {generateMeetingMinutesDocument} from './official-document-engine';import {effectiveMeetingStatus,hasMeaningfulMinutes,meetingMinutesFilename,meetingMinutesPdfInput} from './meeting-mom';
const meeting:any={id:'meeting-1',title:'Monthly Operations Review',agenda:'Review operations and agree next actions.',status:'scheduled',start_at:'2026-08-16T04:30:00.000Z',end_at:'2026-08-16T05:30:00.000Z',host:{full_name:'General Manager'},meeting_participants:[{profiles:{full_name:'Director'}},{profiles:{full_name:'Diya'}}],meeting_notes:[{discussion_summary:'The team reviewed the operating plan.',additional_notes:'Follow up next week.'}],meeting_decisions:[{position:0,decision_text:'Approve the revised plan.'}],meeting_action_items:[{position:0,action_text:'Prepare report',owner:{full_name:'Diya'},due_date:'2026-08-20',status:'pending'}]};
describe('Minutes of Meeting',()=>{
  it('derives meeting state without destructive status updates',()=>{expect(effectiveMeetingStatus(meeting,new Date('2026-08-16T04:00:00Z'))).toBe('scheduled');expect(effectiveMeetingStatus(meeting,new Date('2026-08-16T05:00:00Z'))).toBe('in_progress');expect(effectiveMeetingStatus(meeting,new Date('2026-08-16T06:00:00Z'))).toBe('completed');expect(effectiveMeetingStatus({...meeting,status:'cancelled'},new Date('2026-08-16T06:00:00Z'))).toBe('cancelled')});
  it('builds official content only from persisted meeting relations',()=>{const input=meetingMinutesPdfInput(meeting,new Date('2026-08-17T00:00:00Z'));expect(input).toMatchObject({meetingTitle:'Monthly Operations Review',hostName:'General Manager',participantNames:['Director','Diya'],agenda:meeting.agenda,discussionSummary:'The team reviewed the operating plan.',decisions:['Approve the revised plan.']});expect(input.actionItems[0]).toEqual({action:'Prepare report',owner:'Diya',dueDate:'2026-08-20',status:'pending'});expect(hasMeaningfulMinutes(input)).toBe(true)});
  it('uses deterministic versioned filenames',()=>expect(meetingMinutesFilename(meeting.title,'2026-08-16',2)).toBe('BSmile_Minutes_of_Meeting_Monthly_Operations_Review_2026-08-16_v2.pdf'));
  it('renders a searchable branded multi-page MoM with repeated action headers',async()=>{const input=meetingMinutesPdfInput({...meeting,meeting_notes:[{discussion_summary:Array.from({length:100},(_,index)=>`Discussion paragraph ${index+1}: operational review detail and agreed context.`).join('\n\n'),additional_notes:'Final review.'}],meeting_action_items:Array.from({length:55},(_,index)=>({position:index,action_text:`Action ${index+1}: prepare a detailed operational report and circulate it for review.`,owner:{full_name:index%2?'Diya':'General Manager'},due_date:'2026-08-20',status:'pending'}))});const result=await generateMeetingMinutesDocument(input);expect(result.buffer.subarray(0,4).toString()).toBe('%PDF');expect(result.pageCount).toBeGreaterThanOrEqual(3);expect(result.buffer.length).toBeGreaterThan(100_000)},30000);
  it('protects generation, version history and audited private download routes',()=>{const generate=readFileSync(resolve(process.cwd(),'src/app/api/meetings/[id]/mom/route.ts'),'utf8');const download=readFileSync(resolve(process.cwd(),'src/app/api/meetings/[id]/mom/[documentId]/route.ts'),'utf8');const sql=readFileSync(resolve(process.cwd(),'supabase/migrations/20260814071316_meetings_and_minutes.sql'),'utf8');expect(generate).toContain("db.from('meetings').select(selection)");expect(generate).not.toContain('request.json');expect(generate).toContain("storage.from('employee-documents')");expect(generate).toContain("document_type:'minutes_of_meeting'");expect(sql).toContain('unique(meeting_id, version_number)');expect(download).toContain("createSignedUrl(document.data.storage_path,300)");expect(download).toContain('record_meeting_mom_download')});
});
