import { supabase } from './supabase';
import { documentFileValidationMessage } from './document-file-rules';
const db=supabase as any;
function required(){if(!db)throw new Error('Supabase is not configured.');return db}
export const onboardingRepository={
 async permissions(){const [view,manage,activate]=await Promise.all(['onboarding.view','onboarding.manage','onboarding.activate'].map(permission_code=>required().rpc('has_permission',{permission_code})));for(const result of [view,manage,activate])if(result.error)throw result.error;return {view:!!view.data,manage:!!manage.data,activate:!!activate.data}},
 async references(){const r=required();const [departments,owners]=await Promise.all([r.from('departments').select('id,name').order('name'),r.from('profiles').select('id,full_name,role').eq('is_employee',true).eq('workforce_visible',true).in('status',['active','intern','probation']).order('full_name')]);if(departments.error)throw departments.error;if(owners.error)throw owners.error;return {departments:departments.data||[],owners:owners.data||[]}},
 async list(){const {data,error}=await required().from('employee_onboardings').select('*,department:departments(name),owner:profiles!employee_onboardings_onboarding_owner_id_fkey(full_name),onboarding_documents(id,is_required,status),onboarding_tasks(id,is_required,status)').order('created_at',{ascending:false});if(error)throw error;return data||[]},
 async detail(id:string){const {data,error}=await required().from('employee_onboardings').select('*,department:departments(id,name),owner:profiles!employee_onboardings_onboarding_owner_id_fkey(id,full_name),manager:profiles!employee_onboardings_reporting_manager_id_fkey(id,full_name),employee:profiles!employee_onboardings_employee_id_fkey(id,full_name,employee_code),onboarding_documents(*),onboarding_tasks(*,owner:profiles!onboarding_tasks_assigned_to_fkey(full_name)),onboarding_events(*,actor:profiles(full_name)),documents(id,title,file_name,storage_path,created_at)').eq('id',id).single();if(error)throw error;return data},
 async create(payload:any){const {data,error}=await required().rpc('create_employee_onboarding',{candidate_name:payload.full_name,candidate_email:payload.personal_email,candidate_phone:payload.phone||null,target_department:payload.department_id,target_designation:payload.designation,target_employment_type:payload.employment_type||null,target_employee_status:payload.employee_status,target_joining_date:payload.expected_joining_date,target_manager:payload.reporting_manager_id||null,target_owner:payload.onboarding_owner_id||null,target_compensation:payload.compensation||null,target_notes:payload.notes||null});if(error)throw error;return data},
 async update(id:string,payload:any){const {data,error}=await required().rpc('update_employee_onboarding',{target_onboarding:id,target_department:payload.department_id,target_designation:payload.designation,target_employment_type:payload.employment_type||null,target_employee_status:payload.employee_status,target_joining_date:payload.expected_joining_date,target_manager:payload.reporting_manager_id||null,target_owner:payload.onboarding_owner_id,target_compensation:payload.compensation||null,target_notes:payload.notes||null});if(error)throw error;return data},
 async addDocument(id:string,title:string,isRequired:boolean){const {data,error}=await required().rpc('add_onboarding_document',{target_onboarding:id,document_title:title,required_document:isRequired});if(error)throw error;return data},
 async uploadDocument(userId:string,onboardingId:string,documentId:string,file:File){const validation=documentFileValidationMessage(file);if(validation)throw new Error(validation);const path=`company/${userId}/onboarding/${onboardingId}/${crypto.randomUUID()}-${file.name}`;const upload=await required().storage.from('employee-documents').upload(path,file,{upsert:false});if(upload.error)throw upload.error;const {data,error}=await required().rpc('submit_onboarding_document',{target_document:documentId,target_path:path,target_file_name:file.name,target_mime:file.type||'',target_size:file.size});if(error){await required().storage.from('employee-documents').remove([path]);throw error}return data},
 async reviewDocument(id:string,decision:'verified'|'rejected',reason=''){const {data,error}=await required().rpc('review_onboarding_document',{target_document:id,decision,review_reason:reason||null});if(error)throw error;return data},
 async signedDocument(path:string){const {data,error}=await required().storage.from('employee-documents').createSignedUrl(path,300);if(error)throw error;return data.signedUrl},
 async advance(id:string,action:string,date?:string,reason?:string){const {data,error}=await required().rpc('advance_employee_onboarding',{target_onboarding:id,target_action:action,action_date:date||null,action_reason:reason||null});if(error)throw error;return data},
 async addTask(id:string,title:string,isRequired:boolean,owner?:string){const {data,error}=await required().rpc('add_onboarding_task',{target_onboarding:id,task_title:title,required_task:isRequired,task_owner:owner||null});if(error)throw error;return data},
 async setTask(id:string,status:'pending'|'completed'){const {data,error}=await required().rpc('set_onboarding_task_status',{target_task:id,target_status:status});if(error)throw error;return data},
};
