import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const sql=readFileSync(resolve(process.cwd(),'supabase/migrations/20260813213043_psychologist_session_payables.sql'),'utf8');
const component=readFileSync(resolve(process.cwd(),'src/components/psychologist-session-payables.tsx'),'utf8');
describe('psychologist session payables migration',()=>{
 it('enforces a single payable only after a submitted completed online outsourced session',()=>{expect(sql).toContain('appointment_id uuid not null unique');expect(sql).toContain("appointment.consultation_type <> 'online'");expect(sql).toContain("appointment.status <> 'completed'");expect(sql).toContain("clinician.clinician_type <> 'outsourced'");expect(sql).toContain('psychologist_session_records');});
 it('snapshots configured rates and due dates without zero-value fallback',()=>{expect(sql).toContain('psychologist_rate numeric(14,2) not null check(psychologist_rate > 0)');expect(sql).toContain('setting.default_session_payout');expect(sql).toContain("setting.payment_cycle_type='submission_plus_days'");expect(sql).toContain("'missing_rate'");});
 it('keeps financial history, audit, notification and finance-backed settlement secure',()=>{expect(sql).toContain("status='cancelled'");expect(sql).toContain('psychologist_session_payable_created');expect(sql).toContain('psychologist_payable_notify_management');expect(sql).toContain('psychologist_session_payable_paid');expect(sql).toContain("not public.has_permission('psychologist_payments.settle')");expect(sql).toContain('enable row level security');});
 it('validates the selected active finance account and settles from the server-side payable amount',()=>{expect(sql).toContain("from public.finance_accounts where id=target_account and is_active");expect(sql).toContain("raise exception 'Payment account is unavailable.'");expect(sql).toContain("where name='Psychologist session payout' and is_active");expect(sql).toContain('payable.payable_amount');expect(sql).toContain("payable.status not in ('payment_due','scheduled') or payable.finance_transaction_id is not null");});
 it('rejects an invalid payment method before an atomic ledger and payable update',()=>{expect(sql).toContain("method not in ('cash','bank_transfer','upi','card')");expect(sql).toContain("insert into public.finance_transactions(transaction_type,account_id,expense_category_id,amount");expect(sql).toContain('update public.psychologist_session_payables set status=\'paid\'');});
 it('requires an explicit settlement confirmation instead of silently using the first account',()=>{expect(component).toContain('Confirm psychologist payment');expect(component).toContain('aria-label="Paid from account"');expect(component).toContain('Confirm payment');expect(component).not.toContain('const account=accounts[0]?.id');});
 it('seeds only the exact legacy production management roles without rewriting RBAC',()=>{const permissionSeed=sql.slice(0,sql.indexOf('create table if not exists public.psychologist_payout_settings'));expect(permissionSeed).toContain("insert into public.role_permissions(role, permission_id)");expect(permissionSeed).toContain("management_role.role_name::public.employee_role");expect(permissionSeed).toContain("('Chairman'), ('Director'), ('General Manager')");expect(permissionSeed).toContain('on conflict do nothing');expect(permissionSeed).toContain("column_name = 'role_id'");expect(permissionSeed).not.toMatch(/(?:update|delete|alter table)\s+public\.role_permissions/i);expect(permissionSeed).not.toContain("('Staff')");});
});
