import { NextResponse } from 'next/server';
import { serverSupabase } from '@/lib/supabase-server';
import { normalizeGender } from '@/lib/gender';
import { normalizePatientSource } from '@/lib/patient-source';
import { isUuid } from '@/lib/patient-slug';
const allowed=(db:any, code:string)=>db.rpc('has_permission',{permission_code:code});
const editablePatientFields = ['full_name','phone','email','date_of_birth','gender','nationality','preferred_language','emergency_contact_name','emergency_contact_phone','source','status','address'];
export async function POST(request:Request,{params}:{params:Promise<{patientId:string}>}){try{const {patientId}=await params;if(!isUuid(patientId))return NextResponse.json({error:'Client not found.'},{status:404});const db=await serverSupabase();const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const {kind,payload}=await request.json();if(!payload || typeof payload !== 'object' || Array.isArray(payload))return NextResponse.json({error:'Invalid request payload.'},{status:400});
 if(kind==='patient'){const [editPermission, target] = await Promise.all([allowed(db,'patients.edit'), db.from('patients').select('id').eq('id',patientId).is('deleted_at',null).is('archived_at',null).maybeSingle()]);if(!editPermission.data)return NextResponse.json({error:'Permission denied'},{status:403});if(target.error || !target.data)return NextResponse.json({error:'Active client not found or access denied.'},{status:404});const gender=normalizeGender(payload.gender);const source=normalizePatientSource(payload.source);if(!String(payload.full_name || '').trim())throw new Error('Full name is required.');if(!gender)throw new Error('Select Male or Female.');if(!source)throw new Error('Select a valid source.');const safePayload=Object.fromEntries(editablePatientFields.filter(field => field in payload).map(field => [field,payload[field]]));if ('assigned_psychologist_id' in payload) { const assignmentPermission=await allowed(db,'patients.assign');if(!assignmentPermission.data)return NextResponse.json({error:'Permission denied to change the assigned clinician.'},{status:403});safePayload.assigned_psychologist_id=payload.assigned_psychologist_id || null; }const {data,error}=await db.from('patients').update({...safePayload,full_name:String(payload.full_name).trim(),gender,source,updated_at:new Date().toISOString(),updated_by:user.id}).eq('id',patientId).is('deleted_at',null).is('archived_at',null).select('id,slug').single();if(error)throw error;return NextResponse.json({ok:true,patient:data});}
 else if(kind==='session'){const p=await allowed(db,'patient_sessions.create');if(!p.data)return NextResponse.json({error:'Permission denied'},{status:403});if(!payload.appointment_at||Number(payload.duration_minutes)<=0)throw new Error('Provide a date, time, and valid duration.');const {error}=await db.rpc('create_patient_session_with_payment',{target_patient:patientId,session_at:payload.appointment_at,target_practitioner:payload.assigned_psychologist_id||null,target_session_type:payload.session_type,target_duration:Number(payload.duration_minutes),target_status:payload.attendance_status,target_session_number:payload.session_number?Number(payload.session_number):null,target_follow_up:payload.follow_up_at||null,target_summary:payload.administrative_summary||null,target_fee:Number(payload.session_fee||0),received_amount:Number(payload.received_amount||0),receiving_account:payload.receiving_account||null,received_method:payload.payment_method||null,received_reference:payload.reference_number||null,request_key:payload.idempotency_key});if(error)throw error;}
 else if(kind==='payment'){const [invoicePermission,financePermission]=await Promise.all([allowed(db,'invoices.manage'),allowed(db,'finance.manage')]);if(!invoicePermission.data&&!financePermission.data)return NextResponse.json({error:'Permission denied'},{status:403});if(!isUuid(String(payload.invoice_id||''))||!isUuid(String(payload.account_id||''))||!isUuid(String(payload.idempotency_key||'')))throw new Error('Choose a valid invoice and receiving account.');const invoice=await db.from('finance_invoices').select('id,patient_session_id').eq('id',payload.invoice_id).eq('patient_id',patientId).not('patient_session_id','is',null).is('archived_at',null).maybeSingle();if(invoice.error||!invoice.data)return NextResponse.json({error:'Session invoice not found or access denied.'},{status:404});const amount=Number(payload.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('Enter a valid positive payment amount.');const {error}=await db.rpc('record_invoice_payment_atomic',{target_invoice:payload.invoice_id,target_account:payload.account_id,payment_amount:amount,paid_on:payload.payment_date||null,method:payload.payment_method,reference:payload.reference_number||null,request_key:payload.idempotency_key});if(error)throw error;}
 else if(kind==='archive_preview'){const {data,error}=await db.rpc('patient_archive_preview',{target_patient:patientId});if(error)throw error;return NextResponse.json({ok:true,preview:Array.isArray(data)?data[0]:data});}
 else if(kind==='archive'){const {data,error}=await db.rpc('archive_patient',{target_patient:patientId,reason:String(payload.reason||''),acknowledge_outstanding:!!payload.acknowledge_outstanding});if(error)throw error;return NextResponse.json({ok:true,patientId:data});}
 else if(kind==='restore'){const {data,error}=await db.rpc('restore_patient',{target_patient:patientId,reason:String(payload.reason||'')});if(error)throw error;return NextResponse.json({ok:true,patientId:data});}
 else if(kind==='note'){const code=payload.note_type==='clinical'?'clinical_notes.create':'patient_notes.create';const p=await allowed(db,code);if(!p.data)return NextResponse.json({error:'Permission denied'},{status:403});if(!payload.content?.trim())throw new Error('Note content is required.');const {error}=await db.from('patient_notes').insert({...payload,patient_id:patientId,created_by:user.id});if(error)throw error;}
 else return NextResponse.json({error:'Unsupported action'},{status:400});return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to save changes.'},{status:400});}}
