import { NextResponse } from 'next/server';
import { serverSupabase } from '@/lib/supabase-server';
import { normalizeGender } from '@/lib/gender';
import { normalizePatientSource } from '@/lib/patient-source';
import { isUuid } from '@/lib/patient-slug';
const allowed=(db:any, code:string)=>db.rpc('has_permission',{permission_code:code});
const editablePatientFields = ['full_name','phone','email','date_of_birth','gender','nationality','preferred_language','emergency_contact_name','emergency_contact_phone','source','status','address'];
export async function POST(request:Request,{params}:{params:Promise<{patientId:string}>}){try{const {patientId}=await params;if(!isUuid(patientId))return NextResponse.json({error:'Patient not found.'},{status:404});const db=await serverSupabase();const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const {kind,payload}=await request.json();if(!payload || typeof payload !== 'object' || Array.isArray(payload))return NextResponse.json({error:'Invalid request payload.'},{status:400});
 if(kind==='patient'){const [editPermission, target] = await Promise.all([allowed(db,'patients.edit'), db.from('patients').select('id').eq('id',patientId).is('deleted_at',null).maybeSingle()]);if(!editPermission.data)return NextResponse.json({error:'Permission denied'},{status:403});if(target.error || !target.data)return NextResponse.json({error:'Patient not found or access denied.'},{status:404});const gender=normalizeGender(payload.gender);const source=normalizePatientSource(payload.source);if(!String(payload.full_name || '').trim())throw new Error('Full name is required.');if(!gender)throw new Error('Select Male or Female.');if(!source)throw new Error('Select a valid source.');const safePayload=Object.fromEntries(editablePatientFields.filter(field => field in payload).map(field => [field,payload[field]]));if ('assigned_psychologist_id' in payload) { const assignmentPermission=await allowed(db,'patients.assign');if(!assignmentPermission.data)return NextResponse.json({error:'Permission denied to change the assigned clinician.'},{status:403});safePayload.assigned_psychologist_id=payload.assigned_psychologist_id || null; }const {data,error}=await db.from('patients').update({...safePayload,full_name:String(payload.full_name).trim(),gender,source,updated_at:new Date().toISOString(),updated_by:user.id}).eq('id',patientId).is('deleted_at',null).select('id,slug').single();if(error)throw error;return NextResponse.json({ok:true,patient:data});}
 else if(kind==='session'){const p=await allowed(db,'patient_sessions.create');if(!p.data)return NextResponse.json({error:'Permission denied'},{status:403});if(!payload.appointment_at||Number(payload.duration_minutes)<0)throw new Error('Provide a date, time, and valid duration.');const {error}=await db.from('patient_sessions').insert({...payload,patient_id:patientId,created_by:user.id});if(error)throw error;}
 else if(kind==='note'){const code=payload.note_type==='clinical'?'clinical_notes.create':'patient_notes.create';const p=await allowed(db,code);if(!p.data)return NextResponse.json({error:'Permission denied'},{status:403});if(!payload.content?.trim())throw new Error('Note content is required.');const {error}=await db.from('patient_notes').insert({...payload,patient_id:patientId,created_by:user.id});if(error)throw error;}
 else return NextResponse.json({error:'Unsupported action'},{status:400});return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to save changes.'},{status:400});}}
