'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {currentProfile} from '@/lib/auth';
import {onboardingRepository} from '@/lib/onboarding-repository';
import {documentProgress,onboardingNextAction,onboardingProgress,onboardingProgressStages,onboardingStageLabels} from '@/lib/onboarding-rules';

const today=()=>new Date().toISOString().slice(0,10);
export default function OnboardingDetail(){const {id}=useParams<{id:string}>();const [item,setItem]=useState<any>();const [refs,setRefs]=useState<any>({owners:[],departments:[]});const [permissions,setPermissions]=useState<any>({});const [profile,setProfile]=useState<any>();const [notice,setNotice]=useState('');const [busy,setBusy]=useState('');const [role,setRole]=useState('staff');
 const load=async()=>{try{const [data,references,allowed,user]=await Promise.all([onboardingRepository.detail(id),onboardingRepository.references(),onboardingRepository.permissions(),currentProfile()]);setItem(data);setRefs(references);setPermissions(allowed);setProfile(user);setNotice('')}catch(error:any){setNotice(error.message||'Onboarding could not be loaded.')}};useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[id]);
 const docs=useMemo(()=>item?.onboarding_documents||[],[item]);const tasks=useMemo(()=>item?.onboarding_tasks||[],[item]);const events=useMemo(()=>[...(item?.onboarding_events||[])].sort((a:any,b:any)=>b.created_at.localeCompare(a.created_at)),[item]);
 const action=async(kind:string,date?:string,reason?:string)=>{setBusy(kind);try{await onboardingRepository.advance(id,kind,date,reason);await load()}catch(error:any){setNotice(error.message)}finally{setBusy('')}};
 const offer=async()=>{setBusy('offer');try{const response=await fetch(`/api/onboarding/${id}/offer`,{method:'POST'});if(!response.ok){const data=await response.json();throw new Error(data.error)}const blob=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=blob;a.download=`BSmile_Offer_Letter_${item.full_name}.pdf`;a.click();URL.revokeObjectURL(blob);await load()}catch(error:any){setNotice(error.message)}finally{setBusy('')}};
 const upload=async(documentId:string,file?:File)=>{if(!file||!profile)return;setBusy(documentId);try{await onboardingRepository.uploadDocument(profile.id,id,documentId,file);await load()}catch(error:any){setNotice(error.message)}finally{setBusy('')}};
 const review=async(documentId:string,decision:'verified'|'rejected')=>{const reason=decision==='rejected'?window.prompt('Reason for rejection / resubmission')||'':'';if(decision==='rejected'&&!reason)return;try{await onboardingRepository.reviewDocument(documentId,decision,reason);await load()}catch(error:any){setNotice(error.message)}};
 const openFile=async(path:string)=>window.open(await onboardingRepository.signedDocument(path),'_blank','noopener,noreferrer');
 const activate=async()=>{setBusy('activate');try{const response=await fetch(`/api/onboarding/${id}/activate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});const data=await response.json();if(!response.ok)throw new Error(data.error);await load()}catch(error:any){setNotice(error.message)}finally{setBusy('')}};
 if(!item)return <section className="p-6">{notice||'Loading onboarding…'}</section>;const docSummary=documentProgress(docs);const pendingTasks=tasks.filter((task:any)=>task.is_required&&task.status!=='completed').length;
 return <section className="mx-auto max-w-[1280px] space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><Link className="text-sm text-teal-700 underline" href="/admin/onboarding">Back to onboarding</Link><h1 className="mt-1 text-2xl font-bold">{item.full_name}</h1><p className="text-sm text-slate-600">{item.designation} · {item.department?.name} · Expected {item.expected_joining_date}</p></div><div className="text-right"><span className="rounded-full bg-teal-50 px-3 py-1 text-sm font-bold text-teal-800">{onboardingStageLabels[item.stage]}</span><p className="mt-2 text-sm font-semibold">Next: {onboardingNextAction(item)}</p></div></div>{notice&&<p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{notice}</p>}
 <div className="card p-4"><div className="flex justify-between text-sm"><b>Onboarding progress</b><span>{onboardingProgress(item.stage)}%</span></div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-teal-600" style={{width:`${onboardingProgress(item.stage)}%`}}/></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4 xl:grid-cols-7">{onboardingProgressStages.map(stage=><a href={`#${stage}`} className={`rounded p-2 text-center ${onboardingProgress(item.stage)>=onboardingProgress(stage)?'bg-teal-50 text-teal-800':'bg-slate-50 text-slate-500'}`} key={stage}>{onboardingStageLabels[stage]}</a>)}</div></div>
 <div className="grid gap-4 xl:grid-cols-3"><section className="card p-5 xl:col-span-2"><h2 className="font-bold">Candidate and employment details</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><Fact label="Personal email" value={item.personal_email}/><Fact label="Phone" value={item.phone||'—'}/><Fact label="Employment type" value={item.employment_type||'—'}/><Fact label="Employee status" value={item.employee_status}/><Fact label="Reporting manager" value={item.manager?.full_name||'—'}/><Fact label="Onboarding owner" value={item.owner?.full_name}/><Fact label="Expected joining" value={item.expected_joining_date}/><Fact label="Actual joining" value={item.actual_joining_date||'Pending'}/></dl>{item.notes&&<p className="mt-4 rounded bg-slate-50 p-3 text-sm">{item.notes}</p>}</section><section className="card p-5"><h2 className="font-bold">Control</h2><p className="mt-2 text-sm">Offer: <b>{item.offer_status}</b></p><p className="text-sm">Documents: <b>{docSummary.label}</b></p><p className="text-sm">Required tasks pending: <b>{pendingTasks}</b></p>{item.employee&&<p className="mt-3 rounded bg-emerald-50 p-3 text-sm text-emerald-800">Activated as {item.employee.employee_code} · {item.employee.full_name}</p>}</section></div>
 <section className="card p-5" id="documents_pending"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-bold">Documents</h2><p className="text-sm text-slate-500">Mandatory documents must be submitted and verified before the offer.</p></div>{permissions.manage&&item.stage!=='completed'&&item.stage!=='cancelled'&&<button className="btn border" onClick={()=>{const title=prompt('Document title');if(title)void onboardingRepository.addDocument(id,title,confirm('Make this document required?')).then(load)}}>Add checklist item</button>}</div><div className="mt-4 grid gap-3 lg:grid-cols-2">{docs.map((doc:any)=><article className="rounded-xl border p-4" key={doc.id}><div className="flex justify-between gap-3"><div><b>{doc.title}</b><p className="text-xs text-slate-500">{doc.is_required?'Required':'Optional'}</p></div><span className="text-sm font-bold">{doc.status}</span></div>{doc.rejection_reason&&<p className="mt-2 text-sm text-rose-700">Needs resubmission: {doc.rejection_reason}</p>}<div className="mt-3 flex flex-wrap gap-2">{permissions.manage&&['pending','rejected'].includes(doc.status)&&<label className="btn border cursor-pointer">{busy===doc.id?'Uploading…':'Upload'}<input className="hidden" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>void upload(doc.id,e.target.files?.[0])}/></label>}{doc.storage_path&&<button className="btn border" onClick={()=>void openFile(doc.storage_path)}>View private file</button>}{permissions.manage&&doc.status==='submitted'&&<><button className="btn btn-primary" onClick={()=>void review(doc.id,'verified')}>Verify</button><button className="btn border" onClick={()=>void review(doc.id,'rejected')}>Reject</button></>}</div>{doc.verified_at&&<p className="mt-2 text-xs text-slate-500">Verified {new Date(doc.verified_at).toLocaleString()}</p>}</article>)}</div></section>
 <section className="card p-5" id="offer_generated"><h2 className="font-bold">Offer letter and acceptance</h2><p className="mt-1 text-sm text-slate-500">Generated offers are versioned private official documents; signed returns remain separate checklist files.</p><div className="mt-4 flex flex-wrap gap-2">{permissions.manage&&['documents_verified','offer_generated','offer_sent'].includes(item.stage)&&<button className="btn btn-primary" disabled={busy==='offer'} onClick={()=>void offer()}>{busy==='offer'?'Generating…':'Generate Offer Letter'}</button>}{permissions.manage&&item.stage==='offer_generated'&&<button className="btn border" onClick={()=>void action('offer_sent',today())}>Mark offer sent</button>}{permissions.manage&&['offer_generated','offer_sent'].includes(item.stage)&&<><button className="btn border" onClick={()=>void action('offer_accepted',window.prompt('Accepted date',today())||today())}>Record accepted</button><button className="btn border" onClick={()=>{const reason=prompt('Decline reason (optional)')||'';void action('offer_declined',today(),reason)}}>Record declined</button></>}</div>{(item.documents||[]).length>0&&<div className="mt-4"><h3 className="text-sm font-bold">Offer history</h3>{item.documents.map((doc:any)=><button className="mt-2 block text-sm text-teal-700 underline" key={doc.id} onClick={()=>void openFile(doc.storage_path)}>{doc.file_name} · {new Date(doc.created_at).toLocaleString()}</button>)}</div>}</section>
 <section className="card p-5" id="joined"><h2 className="font-bold">Joining</h2><p className="mt-1 text-sm">Expected: {item.expected_joining_date} · Actual: {item.actual_joining_date||'Pending'}</p>{permissions.manage&&item.stage==='offer_accepted'&&<button className="btn btn-primary mt-3" onClick={()=>{const date=prompt('Actual joining date',item.expected_joining_date);if(date)void action('joining_confirmed',date)}}>Confirm joining</button>}</section>
 <section className="card p-5" id="onboarding_in_progress"><div className="flex flex-wrap justify-between"><div><h2 className="font-bold">Onboarding tasks</h2><p className="text-sm text-slate-500">All required tasks must be complete before activation.</p></div>{permissions.manage&&<button className="btn border" onClick={()=>{const title=prompt('Task title');if(title)void onboardingRepository.addTask(id,title,confirm('Make this task required?'),item.onboarding_owner_id).then(load)}}>Add task</button>}</div><div className="mt-4 space-y-2">{tasks.map((task:any)=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3" key={task.id}><div><b>{task.title}</b><p className="text-xs text-slate-500">{task.is_required?'Required':'Optional'} · {task.owner?.full_name||'Unassigned'}</p></div>{permissions.manage&&['joined','onboarding_in_progress'].includes(item.stage)?<button className="btn border" onClick={()=>void onboardingRepository.setTask(task.id,task.status==='completed'?'pending':'completed').then(load)}>{task.status==='completed'?'Reopen':'Complete'}</button>:<b className="text-sm">{task.status}</b>}</div>)}</div></section>
 <section className="card p-5" id="completed"><h2 className="font-bold">Employee activation</h2><p className="mt-1 text-sm text-slate-500">Creates the Auth-linked employee profile once, assigns the next A-series employee code in the database, and closes onboarding atomically.</p>{permissions.activate&&!item.employee_id&&['joined','onboarding_in_progress'].includes(item.stage)&&<div className="mt-3 flex flex-wrap items-end gap-2"><label className="text-sm font-semibold">Approved role<select className="input mt-1" value={role} onChange={e=>setRole(e.target.value)}>{[['staff','Staff'],['intern','Intern'],['psychologist','Psychologist'],['guest_sales','Guest Sales'],...(profile?.role==='super_admin'?[['general_manager','General Manager'],['director','Director'],['chairman','Chairman']]:[])].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button className="btn btn-primary" disabled={busy==='activate'||pendingTasks>0||docSummary.verified<docSummary.required} onClick={()=>void activate()}>{busy==='activate'?'Activating…':'Activate employee'}</button></div>}</section>
 {permissions.manage&&!['completed','cancelled'].includes(item.stage)&&<section className="card border-rose-200 p-5"><h2 className="font-bold text-rose-800">Close onboarding</h2><button className="btn border mt-3" onClick={()=>{const reason=prompt('Cancellation reason');if(reason)void action('cancel',undefined,reason)}}>Cancel onboarding</button></section>}
 <section className="card p-5"><h2 className="font-bold">Activity timeline</h2><div className="mt-4 space-y-3">{events.map((event:any)=><div className="border-l-2 border-teal-200 pl-3" key={event.id}><b className="text-sm">{event.event_type.replaceAll('_',' ')}</b><p className="text-xs text-slate-500">{new Date(event.created_at).toLocaleString()} · {event.actor?.full_name||'System'}</p></div>)}</div></section></section>}
function Fact({label,value}:{label:string;value:any}){return <div><dt className="text-slate-500">{label}</dt><dd className="font-semibold">{value}</dd></div>}
