'use client';

import { useEffect, useMemo, useState } from 'react';
import { currentProfile } from '@/lib/auth';
import { employeeRepository } from '@/lib/employee-repository';
import { EmployeeBanner, EmployeeEmptyState, EmployeeLoading, EmployeeMetric, EmployeeMetricGrid, EmployeePageHeader, EmployeeSection, EmployeeStatusBadge } from '@/components/employee-ui';

const categories = ['general', 'hr', 'holiday', 'meeting', 'policy', 'event', 'urgent'];

export default function AnnouncementsPage() {
  const [profile, setProfile] = useState<any>(); const [items, setItems] = useState<any[]>([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [detail, setDetail] = useState<any>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const employee = await currentProfile() as any; if (!employee) throw Error('Your session has expired.'); setProfile(employee); setItems(await employeeRepository.announcements(employee.id)); setError(''); } catch (caught: any) { setError(caught.message || 'Unable to load announcements.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  const open = async (item: any) => { setDetail(item); if (!item.is_read) { await employeeRepository.markAnnouncementRead(item.id, profile.id); setItems(current => current.map(entry => entry.id === item.id ? { ...entry, is_read: true } : entry)); } };
  const shown = useMemo(() => items.filter(item => (!category || item.category === category) && `${item.title} ${item.body}`.toLowerCase().includes(query.toLowerCase())), [items, query, category]);
  if (loading) return <section><EmployeePageHeader title="Announcements" subtitle="Company updates for you and your team." /><EmployeeLoading cards={3} /></section>;
  if (error && !profile) return <section><EmployeePageHeader title="Announcements" subtitle="Company updates for you and your team." /><EmployeeBanner>{error}</EmployeeBanner><button className="btn btn-primary" onClick={load}>Try again</button></section>;
  return <section className="space-y-4"><EmployeePageHeader title="Announcements" subtitle="Company updates for you and your team." /><EmployeeMetricGrid columns={2}><EmployeeMetric label="Active announcements" value={items.length} /><EmployeeMetric label="Unread" value={items.filter(item => !item.is_read).length} tone="info" /></EmployeeMetricGrid>{error && <EmployeeBanner>{error}</EmployeeBanner>}<div className="flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-2"><input className="input h-10 min-w-0 flex-1 py-2" placeholder="Search announcements" value={query} onChange={event => setQuery(event.target.value)} /><select className="input h-10 w-auto min-w-40 py-2" value={category} onChange={event => setCategory(event.target.value)}><option value="">All categories</option>{categories.map(value => <option value={value} key={value}>{value}</option>)}</select></div><EmployeeSection title="All announcements" description="Pinned announcements appear first.">{shown.length ? <div className="divide-y divide-slate-100">{shown.map(item => <a href={`/employee/announcements/${item.id}`} onClick={() => void open(item)} className="block w-full p-4 text-left transition hover:bg-slate-50" key={item.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b>{item.title}</b>{item.is_pinned && <EmployeeStatusBadge tone="pending">Pinned</EmployeeStatusBadge>}</div><p className="mt-1 line-clamp-2 text-sm text-slate-600">{item.body}</p><p className="mt-2 text-xs text-slate-500">{item.category} - {new Date(item.published_at).toLocaleDateString()} - {item.author?.full_name || 'BSmile'}</p></div>{!item.is_read && <EmployeeStatusBadge tone="info">New</EmployeeStatusBadge>}</div></a>)}</div> : <EmployeeEmptyState title="No announcements found" detail="Try a different search or category." />}</EmployeeSection>{detail && <EmployeeSection title={detail.title} description={`${detail.category} - ${detail.author?.full_name || 'BSmile'}`} action={<button className="btn border px-3 py-1.5 text-xs" onClick={() => setDetail(null)}>Close</button>}><p className="whitespace-pre-wrap px-4 py-4 text-sm leading-6 text-slate-700">{detail.body}</p></EmployeeSection>}</section>;
}
