'use client';

import { useEffect, useState } from 'react';
import { currentProfile } from '@/lib/auth';
import { employeeRepository } from '@/lib/employee-repository';
import { NotificationPreferences } from '@/components/notification-preferences';

const labels: Record<string, string> = { task_assigned: 'Task assigned', task_updated: 'Task updated', leave_approved: 'Leave approved', leave_rejected: 'Leave rejected', document_requested: 'Document requested', document_approved: 'Document approved', document_rejected: 'Document rejected', new_announcement: 'Announcement', chat_message: 'Message' };
const safeLink = (link?: string | null) => {
  if (link?.startsWith('/employee/')) return link;
  if (link?.startsWith('/admin/doctor-scheduling')) return link.replace('/admin/doctor-scheduling', '/employee/doctor-scheduling');
  return '/employee/notifications';
};

export default function NotificationsPage() {
  const [profile, setProfile] = useState<any>(); const [items, setItems] = useState<any[]>([]); const [query, setQuery] = useState(''); const [type, setType] = useState(''); const [detail, setDetail] = useState<any>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [preferencesOpen, setPreferencesOpen] = useState(false);
  const load = async () => { setLoading(true); try { const current = await currentProfile() as any; if (!current) throw new Error('Your session has expired.'); setProfile(current); setItems(await employeeRepository.notifications(current.id)); setError(''); } catch (caught: any) { setError(caught.message || 'Unable to load notifications.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const read = async (item: any) => { if (!item.read_at && profile) { await employeeRepository.markNotificationRead(item.id, profile.id); setItems(current => current.map(row => row.id === item.id ? { ...row, read_at: new Date().toISOString() } : row)); } setDetail(item); };
  if (loading) return <section><h1 className="text-2xl font-bold">Notifications</h1><p className="mt-3 text-slate-600">Loading notifications...</p></section>;
  if (error && !profile) return <section><h1 className="text-2xl font-bold">Notifications</h1><p className="mt-3 text-rose-700">{error}</p></section>;
  const types = [...new Set(items.map(item => item.type))]; const shown = items.filter(item => (!type || item.type === type) && `${item.title} ${item.body}`.toLowerCase().includes(query.toLowerCase())); const unread = items.filter(item => !item.read_at).length;
  return <section className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Notifications {unread ? `(${unread})` : ''}</h1><p className="text-slate-600">Updates about your work and company.</p></div><div className="flex gap-2"><button className="rounded border px-3 py-2 text-sm" onClick={() => setPreferencesOpen(current => !current)}>Sound settings</button>{unread > 0 && <button className="rounded border px-3 py-2 text-sm" onClick={() => void employeeRepository.markAllNotificationsRead(profile.id).then(load)}>Mark all as read</button>}</div></div>{preferencesOpen && <NotificationPreferences userId={profile.id} />}{error && <p className="rounded bg-rose-50 p-3 text-rose-800">{error}</p>}<div className="flex gap-2"><input className="rounded border p-2" placeholder="Search notifications" value={query} onChange={event => setQuery(event.target.value)} /><select className="rounded border p-2" value={type} onChange={event => setType(event.target.value)}><option value="">All types</option>{types.map(value => <option value={value} key={value}>{labels[value] || value}</option>)}</select></div>{shown.length ? <div className="card overflow-hidden">{shown.map(item => <button onClick={() => void read(item)} className={`block w-full border-b p-4 text-left ${item.read_at ? 'bg-white' : 'bg-sky-50'}`} key={item.id}><div className="flex justify-between gap-3"><div><b>{item.title}</b><p className="text-sm text-slate-600">{item.body}</p><small className="text-slate-500">{labels[item.type] || item.type} · {new Date(item.created_at).toLocaleString()}</small></div>{!item.read_at && <span className="h-fit rounded-full bg-brand px-2 py-1 text-xs text-white">New</span>}</div></button>)}</div> : <div className="card p-6 text-slate-600">No notifications found.</div>}{detail && <div className="card p-5"><button className="float-right text-sm underline" onClick={() => setDetail(null)}>Close</button><h2 className="text-lg font-bold">{detail.title}</h2><p className="mt-2">{detail.body}</p>{detail.deep_link && <a href={safeLink(detail.deep_link)} className="mt-3 inline-block text-sm underline">Open related item</a>}</div>}</section>;
}
