'use client';

import {FormEvent,useEffect,useState} from 'react';
import {currentProfile} from '@/lib/auth';
import {employeeRepository} from '@/lib/employee-repository';
import {resolveEmployeeAvatar} from '@/lib/employee-avatar';
import {profileCompletion,validateProfile} from '@/lib/profile-rules';
import {BrowserPushSettings} from '@/components/browser-push-settings';
import {ProfileOrganizationChart} from '@/components/profile-organization-chart';

const text=(value:any)=>value===null||value===undefined||value===''?'—':value;
const addressText=(value:any)=>typeof value==='string'?value:value?.line1||value?.text||'';
const normalized=(data:any)=>({...data,address:{line1:addressText(data.address)},emergency_contact:data.emergency_contact||{},bank_details:data.bank_details||{}});

export default function ProfilePage(){
  const [profile,setProfile]=useState<any>();const [form,setForm]=useState<any>({});const [photo,setPhoto]=useState('');const [editing,setEditing]=useState(false);const [showAccount,setShowAccount]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
  const load=async()=>{setLoading(true);try{const session=await currentProfile() as any;if(!session)throw Error('Your session has expired.');const data=await employeeRepository.profile(session.id);setProfile(data);setForm(normalized(data));const uploadedPhoto=data.avatar_url?await employeeRepository.signedProfilePhoto(data.avatar_url):'';setPhoto(resolveEmployeeAvatar(data.full_name,uploadedPhoto)||'');setError('')}catch(e:any){setError(e.message||'Unable to load your profile.')}finally{setLoading(false)}};
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[]);
  const set=(key:string,value:any)=>setForm((current:any)=>({...current,[key]:value}));
  const nested=(group:string,key:string,value:string)=>setForm((current:any)=>({...current,[group]:{...current[group],[key]:value}}));
  const save=async(event:FormEvent)=>{event.preventDefault();setNotice('');setError('');const validation=validateProfile(form);if(validation){setError(validation);return;}setSaving(true);try{const fields=['full_name','phone','personal_email','date_of_birth','gender','address','emergency_contact','bank_details'];const patch=Object.fromEntries(fields.filter(key=>JSON.stringify(form[key]??null)!==JSON.stringify(normalized(profile)[key]??null)).map(key=>[key,form[key]||null]));if(!Object.keys(patch).length){setEditing(false);return;}await employeeRepository.updateMyProfile(profile.id,patch);setNotice('Profile saved successfully.');setEditing(false);await load();}catch(e:any){setError(e.message||'Unable to save profile.');}finally{setSaving(false)}};
  const upload=async(file?:File)=>{if(!file)return;setNotice('');setError('');try{await employeeRepository.uploadProfilePhoto(profile.id,file);setNotice('Profile photo updated.');await load()}catch(e:any){setError(e.message)}};
  const removePhoto=async()=>{if(!profile.avatar_url||!window.confirm('Remove your profile photo?'))return;setNotice('');setError('');try{await employeeRepository.removeProfilePhoto(profile.id,profile.avatar_url);setNotice('Profile photo removed.');await load()}catch(e:any){setError(e.message)}};
  if(loading)return <section><h1 className="text-2xl font-bold">My Profile</h1><p className="mt-3 text-slate-600">Loading your profile…</p></section>;
  if(error&&!profile)return <section><h1 className="text-2xl font-bold">My Profile</h1><p className="mt-3 text-rose-700">{error}</p><button className="btn btn-primary mt-3" onClick={()=>void load()}>Try again</button></section>;
  const completion=profileCompletion(form);const employment=[['Employee ID',profile.employee_code||profile.id],['Work email',profile.email],['Role',String(profile.role||'').replace('_',' ')],['Department',profile.department?.name||'Not assigned'],['Designation',profile.designation||'Not assigned'],['Reporting manager',profile.manager?.full_name||'Not assigned'],['Joining date',profile.joining_date||'Not set'],['Employment status',profile.status]];const maskedAccount=form.bank_details?.account_number?`•••• ${String(form.bank_details.account_number).slice(-4)}`:'Not provided';
  const field=(key:string,label:string,type='text')=><label className="text-sm font-medium">{label}{editing?<input type={type} className="input mt-1" value={form[key]||''} onChange={e=>set(key,e.target.value)}/>:<p className="mt-1 text-sm font-normal">{text(key==='address'?addressText(form[key]):form[key])}</p>}</label>;
  return <section className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">My Profile</h1><p className="text-slate-600">Keep your personal information up to date.</p></div><button className="btn btn-primary" onClick={()=>{setEditing(true);setNotice('');setError('')}}>{editing?'Editing profile':'Edit Profile'}</button></div>{notice&&<p className="rounded bg-emerald-50 p-3 text-emerald-800">{notice}</p>}{error&&<p className="rounded bg-rose-50 p-3 text-rose-800">{error}</p>}
    <section className="card flex flex-wrap items-center gap-4 p-5"><div>{photo?<img src={photo} alt="Profile" className="h-20 w-20 rounded-full object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-full bg-teal-100 text-2xl font-bold text-teal-800">{profile.full_name?.[0]?.toUpperCase()||'B'}</div>}</div><div className="min-w-48 flex-1"><h2 className="text-xl font-bold">{profile.full_name}</h2><p className="text-sm text-slate-600">{profile.employee_code||'Employee'} · {profile.designation||'Employee'}</p><p className="mt-1 text-sm text-slate-600">{profile.department?.name||'No department'} · <span className="capitalize">{profile.status}</span></p></div><div className="min-w-48"><div className="flex justify-between text-sm"><span>Profile completion</span><b>{completion.percentage}%</b></div><div className="mt-2 h-2 overflow-hidden rounded bg-slate-100"><div className="h-full bg-teal-500" style={{width:`${completion.percentage}%`}}/></div></div><div className="flex gap-2"><label className="btn border cursor-pointer text-sm">{profile.avatar_url?'Replace photo':'Upload photo'}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/></label>{profile.avatar_url&&<button className="btn border text-sm" onClick={()=>void removePhoto()}>Remove</button>}</div></section>
    <ProfileOrganizationChart profileName={profile.full_name} profilePhoto={photo} isSelf />
    {completion.missing.length>0&&<section className="profile-completion-banner rounded border border-teal-100 bg-teal-50 p-4 text-sm"><b>Complete your profile</b><p className="mt-1">Missing: {completion.missing.join(', ')}</p></section>}
    <form onSubmit={save} className="space-y-5"><div className="grid gap-5 lg:grid-cols-2"><section className="card grid gap-4 p-5 md:grid-cols-2"><h2 className="font-bold md:col-span-2">Personal information</h2>{field('full_name','Full name')}{field('phone','Personal phone')}{field('personal_email','Personal email','email')}{field('date_of_birth','Date of birth','date')}<label className="text-sm font-medium">Gender{editing?<select className="input mt-1" value={form.gender||''} onChange={e=>set('gender',e.target.value)}><option value="">Prefer not to say</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="prefer_not_to_say">Prefer not to say</option></select>:<p className="mt-1 text-sm font-normal">{text(form.gender?.replaceAll('_',' '))}</p>}</label><label className="text-sm font-medium md:col-span-2">Address{editing?<textarea className="input mt-1 min-h-20" value={addressText(form.address)} onChange={e=>set('address',{line1:e.target.value})}/>:<p className="mt-1 text-sm font-normal">{text(addressText(form.address))}</p>}</label></section><section className="card p-5"><h2 className="font-bold">Employee Information</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{employment.map(([label,value])=><p className="text-sm" key={label}><span className="text-slate-500">{label}</span><b className="mt-1 block capitalize">{text(value)}</b></p>)}</div></section></div>
      <div className="grid gap-5 lg:grid-cols-2"><section className="card grid gap-4 p-5 md:grid-cols-3"><h2 className="font-bold md:col-span-3">Emergency contact</h2>{['name','phone','relationship'].map(key=><label className="text-sm font-medium capitalize" key={key}>{key}{editing?<input className="input mt-1" value={form.emergency_contact?.[key]||''} onChange={e=>nested('emergency_contact',key,e.target.value)}/>:<p className="mt-1 text-sm font-normal">{text(form.emergency_contact?.[key])}</p>}</label>)}</section><section className="card grid gap-4 p-5 md:grid-cols-2"><h2 className="font-bold md:col-span-2">Bank information</h2>{[['bank_name','Bank name'],['account_holder_name','Account holder name']].map(([key,label])=><label className="text-sm font-medium" key={key}>{label}{editing?<input className="input mt-1" value={form.bank_details?.[key]||''} onChange={e=>nested('bank_details',key,e.target.value)}/>:<p className="mt-1 text-sm font-normal">{text(form.bank_details?.[key])}</p>}</label>)}<label className="text-sm font-medium">Account number{editing?<div className="mt-1 flex gap-2"><input type={showAccount?'text':'password'} className="input" value={form.bank_details?.account_number||''} onChange={e=>nested('bank_details','account_number',e.target.value)}/><button type="button" className="btn border text-xs" onClick={()=>setShowAccount(!showAccount)}>{showAccount?'Hide':'Show'}</button></div>:<div className="mt-1 flex gap-2"><p className="text-sm font-normal">{showAccount?text(form.bank_details?.account_number):maskedAccount}</p>{form.bank_details?.account_number&&<button type="button" className="text-xs text-brand" onClick={()=>setShowAccount(!showAccount)}>{showAccount?'Hide':'Reveal'}</button>}</div>}</label><label className="text-sm font-medium">IFSC code{editing?<input className="input mt-1" value={form.bank_details?.ifsc_code||''} onChange={e=>nested('bank_details','ifsc_code',e.target.value.toUpperCase())}/>:<p className="mt-1 text-sm font-normal">{text(form.bank_details?.ifsc_code)}</p>}</label></section></div>
      {editing&&<div className="sticky bottom-3 z-10 flex gap-2 rounded border bg-white p-3 shadow-sm"><button disabled={saving} className="btn btn-primary disabled:opacity-60">{saving?'Saving…':'Save changes'}</button><button type="button" className="btn border" onClick={()=>{setForm(normalized(profile));setEditing(false);setError('')}}>Cancel</button></div>}</form>
    <BrowserPushSettings />
  </section>;
}
