'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { currentProfile } from '@/lib/auth';
import { employeeRepository } from '@/lib/employee-repository';
import { followupLabel } from '@/lib/crm-followups';

const today = () => new Date().toISOString().slice(0, 10);
const dueState = (item: any) => { if (item.outcome) return 'Completed'; const date = String(item.next_follow_up_at || '').slice(0, 10); if (!date) return 'No next date'; if (date === today()) return 'Today'; return date < today() ? 'Overdue' : 'Upcoming'; };
const localInput = (value: any) => value ? new Date(value).toISOString().slice(0, 16) : '';

export default function FollowUpsPage() {
  const [profile, setProfile] = useState<any>(); const [items, setItems] = useState<any[]>([]); const [query, setQuery] = useState(''); const [date, setDate] = useState(''); const [state, setState] = useState(''); const [number, setNumber] = useState(''); const [editing, setEditing] = useState<any>(); const [customFor, setCustomFor] = useState<string | null>(null); const [customNumber, setCustomNumber] = useState(''); const [saving, setSaving] = useState<string | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const timer = setTimeout(() => void (async () => { try { const user = await currentProfile() as any; if (!user) throw new Error('Please sign in again.'); setProfile(user); setItems(await employeeRepository.myCrmFollowups(user.id)); } catch (caught: any) { setError(caught.message); } })(), 0); return () => clearTimeout(timer); }, []);
  const save = async (item: any, patch: any) => { setSaving(item.id); setError(''); setMessage(''); try { const updated = await employeeRepository.updateMyCrmFollowup(profile.id, item.id, patch); setItems(current => current.map(entry => entry.id === item.id ? { ...entry, ...updated } : entry)); setMessage(`${item.crm_leads?.full_name || 'Follow-up'} updated.`); setEditing(undefined); setCustomFor(null); } catch (caught: any) { setError(caught.message); } finally { setSaving(null); } };
  const assignNumber = async (item: any, raw: string) => { if (raw === 'custom') { setCustomFor(item.id); setCustomNumber(''); return; } await save(item, { followup_number: Number(raw) }); };
  const shown = useMemo(() => items.filter(item => { const due = String(item.next_follow_up_at || '').slice(0, 10); const name = item.crm_leads?.full_name?.toLowerCase() || ''; const group = !item.followup_number ? 'unnumbered' : item.followup_number >= 5 ? '5plus' : String(item.followup_number); return (!query || name.includes(query.toLowerCase())) && (!date || due === date) && (!state || dueState(item) === state) && (!number || group === number); }), [items, query, date, state, number]);
  const row = (item: any, mobile = false) => <div className={mobile ? 'card space-y-3 p-4' : 'grid min-w-[1280px] grid-cols-[180px_170px_200px_170px_170px_170px_120px_130px] items-start gap-3 border-b p-4 text-sm'} key={item.id}><div><b className="text-brand">{item.crm_leads?.full_name}</b><small className="block">{item.crm_leads?.phone}</small></div><div><select className="input" disabled={saving === item.id} value={customFor === item.id ? 'custom' : item.followup_number || ''} onChange={event => void assignNumber(item, event.target.value)}><option value="">Select follow-up number</option>{[1, 2, 3, 4, 5].map(value => <option value={value} key={value}>{followupLabel(value)}</option>)}<option value="custom">Custom</option></select>{customFor === item.id && <div className="mt-2 flex gap-1"><input className="input" min="1" type="number" value={customNumber} onChange={event => setCustomNumber(event.target.value)} /><button className="btn btn-primary" onClick={() => void save(item, { followup_number: Number(customNumber) })}>Save</button></div>}</div><div>{item.note || '—'}</div><div>{item.outcome || '—'}</div><div>{item.follow_up_at ? new Date(item.follow_up_at).toLocaleString() : '—'}</div><div>{item.next_follow_up_at ? new Date(item.next_follow_up_at).toLocaleString() : '—'}</div><div>{dueState(item)}</div><div className="flex gap-2"><button className="btn border" onClick={() => setEditing(editing?.id === item.id ? undefined : { ...item, follow_up_at: localInput(item.follow_up_at), next_follow_up_at: localInput(item.next_follow_up_at) })}>Edit</button><Link className="btn border" href={`/employee/crm/leads/${item.lead_id}`}>Open</Link></div>{editing?.id === item.id && <div className={mobile ? 'space-y-2 border-t pt-3' : 'col-span-8 grid grid-cols-2 gap-2 border-t pt-3'}><textarea className="input" placeholder="Follow-up note" value={editing.note || ''} onChange={event => setEditing({ ...editing, note: event.target.value })} /><input className="input" placeholder="Outcome" value={editing.outcome || ''} onChange={event => setEditing({ ...editing, outcome: event.target.value })} /><label>Follow-up date<input className="input mt-1" type="datetime-local" value={editing.follow_up_at || ''} onChange={event => setEditing({ ...editing, follow_up_at: event.target.value })} /></label><label>Next follow-up<input className="input mt-1" type="datetime-local" value={editing.next_follow_up_at || ''} onChange={event => setEditing({ ...editing, next_follow_up_at: event.target.value })} /></label><button className="btn btn-primary" disabled={saving === item.id} onClick={() => void save(item, { note: editing.note || null, outcome: editing.outcome || null, follow_up_at: editing.follow_up_at ? new Date(editing.follow_up_at).toISOString() : item.follow_up_at, next_follow_up_at: editing.next_follow_up_at ? new Date(editing.next_follow_up_at).toISOString() : null })}>{saving === item.id ? 'Saving...' : 'Save changes'}</button></div>}</div>;
  return <section className="space-y-5"><div><h1 className="text-2xl font-bold">My Follow-ups</h1><p className="text-slate-600">Edit each follow-up number and details directly without losing your filters.</p></div>{error && <p className="rounded bg-rose-50 p-3 text-rose-800">{error}</p>}{message && <p className="rounded bg-emerald-50 p-3 text-emerald-800">{message}</p>}<div className="card flex flex-wrap gap-2 p-4"><input className="input max-w-xs" placeholder="Search lead" value={query} onChange={event => setQuery(event.target.value)} /><input className="input max-w-xs" type="date" value={date} onChange={event => setDate(event.target.value)} /><select className="input max-w-xs" value={state} onChange={event => setState(event.target.value)}><option value="">All due states</option>{['Today', 'Overdue', 'Upcoming', 'Completed', 'No next date'].map(item => <option key={item}>{item}</option>)}</select><select className="input max-w-xs" value={number} onChange={event => setNumber(event.target.value)}><option value="">All follow-up numbers</option><option value="1">1st Follow-up</option><option value="2">2nd Follow-up</option><option value="3">3rd Follow-up</option><option value="4">4th Follow-up</option><option value="5plus">5th+ Follow-ups</option><option value="unnumbered">Unnumbered</option></select></div><div className="space-y-3 md:hidden">{shown.map(item => row(item, true))}</div><div className="card hidden overflow-x-auto md:block"><div className="grid min-w-[1280px] grid-cols-[180px_170px_200px_170px_170px_170px_120px_130px] gap-3 bg-slate-50 p-4 text-xs font-bold uppercase tracking-wide text-slate-600"><div>Client</div><div>Follow-up Number</div><div>Follow-up Note</div><div>Outcome</div><div>Follow-up Date</div><div>Next Follow-up</div><div>Due Status</div><div>Actions</div></div>{shown.map(item => row(item))}</div>{!shown.length && <p className="card p-5 text-slate-500">No follow-ups match this view.</p>}</section>;
}
