'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { currentProfile } from '@/lib/auth';
import { employeeRepository } from '@/lib/employee-repository';
import { EmployeeBanner, EmployeeEmptyState, EmployeeLoading, EmployeeMetric, EmployeeMetricGrid, EmployeePageHeader, EmployeeSection } from '@/components/employee-ui';

const today = () => new Date().toISOString().slice(0, 10);
const money = (value: any, currency = 'INR') => `${currency} ${Number(value || 0).toLocaleString()}`;

export default function EmployeeCrmDashboard() {
  const [profile, setProfile] = useState<any>(); const [leads, setLeads] = useState<any[]>([]); const [followups, setFollowups] = useState<any[]>([]); const [sales, setSales] = useState<any[]>([]); const [error, setError] = useState('');
  useEffect(() => { const timer = setTimeout(() => void (async () => { try { const user = await currentProfile() as any; if (!user) throw Error('Please sign in again.'); setProfile(user); const [leadRows, followupRows, saleRows] = await Promise.all([employeeRepository.myCrmLeads(user.id), employeeRepository.myCrmFollowups(user.id), employeeRepository.myCrmSales(user.id)]); setLeads(leadRows); setFollowups(followupRows); setSales(saleRows); } catch (caught: any) { setError(caught.message); } })(), 0); return () => clearTimeout(timer); }, []);
  const dueToday = followups.filter(item => String(item.next_follow_up_at || '').slice(0, 10) === today()); const overdue = followups.filter(item => item.next_follow_up_at && String(item.next_follow_up_at).slice(0, 10) < today()); const hot = leads.filter(item => item.temperature === 'hot'); const converted = leads.filter(item => item.converted_at); const total = sales.reduce((sum, item) => sum + Number(item.sale_value || 0), 0); const conversionRate = leads.length ? Math.round(converted.length / leads.length * 100) : 0;
  if (!profile && !error) return <section><EmployeePageHeader title="My CRM" subtitle="Your assigned leads, follow-ups, and sales." /><EmployeeLoading cards={3} /></section>;
  if (error) return <section><EmployeePageHeader title="My CRM" subtitle="Your assigned leads, follow-ups, and sales." /><EmployeeBanner>{error}</EmployeeBanner></section>;
  return <section className="space-y-4"><EmployeePageHeader title="My CRM" subtitle={`Your assigned leads, follow-ups, and sales. ${conversionRate}% conversion rate.`} action={<><Link className="btn border" href="/employee/crm/follow-ups">Follow-ups</Link><Link className="btn btn-primary" href="/employee/crm/leads">My leads</Link></>} /><EmployeeMetricGrid columns={4}><EmployeeMetric label="Assigned leads" value={leads.length}/><EmployeeMetric label="Hot leads" value={hot.length} tone="danger"/><EmployeeMetric label="Due today" value={dueToday.length} tone="pending"/><EmployeeMetric label="Overdue" value={overdue.length} tone="danger"/><EmployeeMetric label="Converted" value={converted.length} tone="success"/><EmployeeMetric label="My sales" value={sales.length} tone="info"/><EmployeeMetric label="Sales value" value={money(total)} /><EmployeeMetric label="New leads" value={leads.filter(item => item.status?.name === 'New').length} tone="info"/></EmployeeMetricGrid><div className="grid gap-4 lg:grid-cols-2"><CrmList title="Follow-ups due today" detail="Prioritize today’s customer conversations." items={dueToday} empty="No follow-ups are due today." /><CrmList title="Overdue follow-ups" detail="Follow-ups that need attention." items={overdue} empty="No overdue follow-ups." /><CrmList title="Recently assigned leads" detail="Your newest client records." items={leads.slice(0,5)} empty="No assigned leads." /><CrmList title="Recently converted sales" detail="Your latest successful conversions." items={sales.slice(0,5)} empty="No converted sales yet." sales /></div></section>;
}
function CrmList({ title, detail, items, empty, sales = false }: any) { return <EmployeeSection title={title} description={detail}>{items.length ? <div className="divide-y divide-slate-100">{items.map((item: any) => { const lead = item.crm_leads || item; const line = sales ? `${money(item.sale_value, item.currency)} - ${item.closing_date || 'No closing date'}` : item.next_follow_up_at ? new Date(item.next_follow_up_at).toLocaleString() : `${lead.status?.name || 'Lead'} - ${lead.temperature || ''}`; return <Link className="block px-4 py-3 text-sm hover:bg-slate-50" href={`/employee/crm/leads/${lead.id || item.lead_id}`} key={item.id}><b>{lead.full_name || 'Unnamed lead'}</b><small className="mt-1 block text-slate-500">{line}</small></Link>; })}</div> : <EmployeeEmptyState title={empty} detail="This section will update as your CRM activity changes." />}</EmployeeSection>; }
