'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { demoAppointments, demoMetrics, demoNotifications, demoPatients, demoTasks, type DemoPatient } from './demo-data';

const pill = (value: string) => <span className="status-badge">{value}</span>;

export function DemoDashboard() {
  const [tasks, setTasks] = useState(demoTasks);
  const [notifications, setNotifications] = useState(demoNotifications);
  return <div className="employee-dashboard"><div className="dashboard-welcome"><div><p className="eyebrow">Demo workspace</p><h2>Good morning, Alex.</h2><p>Here is a synthetic operational snapshot for the Besmile portfolio demo.</p></div><Link href="/employee/patients" className="profile-chip"><span>A</span><div><b>Explore clients</b><small>10 fictional records</small></div></Link></div>
    <section className="dashboard-metrics">{[['Active clients',demoMetrics.activeClients,'/employee/patients'],['Appointments this week',demoMetrics.appointmentsThisWeek,'/clinician/schedule'],['Care plans on track',demoMetrics.carePlansOnTrack,'/employee/patients'],['Open tasks',tasks.filter(task => task.status !== 'Completed').length,'/employee/tasks']].map(([label,value,href]) => <Link key={String(label)} className="metric-card metric-link" href={String(href)}><p>{label}</p><b>{value}</b><small>View details</small></Link>)}</section>
    <section className="quick-actions"><Link href="/employee/patients">Client directory</Link><Link href="/clinician/schedule">Clinical workflow</Link><Link href="/employee/notifications">Notifications</Link><Link href="/admin/reports">Reporting</Link></section>
    <div className="dashboard-columns"><DemoSection title="Today's priorities"><div className="dashboard-list">{tasks.map(task => <div className="list-item" key={task.id}><div><b>{task.title}</b><small>{task.priority} priority · Due {task.due}</small></div><button className="text-button" onClick={() => setTasks(current => current.map(item => item.id === task.id ? { ...item, status: item.status === 'Completed' ? 'To do' : 'Completed' } : item))}>{task.status === 'Completed' ? 'Reopen' : 'Complete'}</button></div>)}</div></DemoSection>
      <DemoSection title="Upcoming appointments"><div className="dashboard-list">{demoAppointments.slice(0,3).map(item => <Link className="list-item" href="/clinician/schedule" key={item.id}><div><b>{item.patient}</b><small>{item.time} · {item.clinician}</small></div>{pill(item.status)}</Link>)}</div></DemoSection>
      <DemoSection title="Notifications"><div className="dashboard-list">{notifications.map(item => <div className="list-item" key={item.id}><div><b>{item.title}</b><small>{item.body} · {item.when}</small></div>{!item.read && <button className="text-button" onClick={() => setNotifications(current => current.map(entry => entry.id === item.id ? { ...entry, read: true } : entry))}>Mark read</button>}</div>)}</div></DemoSection></div></div>;
}

export function DemoPatientList() {
  const [query, setQuery] = useState('');
  const results = useMemo(() => demoPatients.filter(patient => `${patient.full_name} ${patient.patient_number} ${patient.clinician}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <section className="space-y-5"><div><p className="eyebrow">Synthetic client records</p><h1 className="text-2xl font-bold">Clients</h1><p className="text-slate-600">A fictional care portfolio for demonstration only.</p></div><div className="card p-4"><input aria-label="Search clients" className="w-full rounded border p-2" placeholder="Search by name, demo ID, or clinician" value={query} onChange={event => setQuery(event.target.value)} /></div><div className="card overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-slate-500"><tr>{['Client ID','Client','Care focus','Clinician','Next appointment','Progress','Status'].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{results.map(patient => <tr className="border-b" key={patient.id}><td className="p-3">{patient.patient_number}</td><td className="p-3 font-medium"><Link className="underline" href={`/employee/patients/${patient.slug}`}>{patient.full_name}</Link><small className="block text-slate-500">Age {patient.age}</small></td><td className="p-3">{patient.treatment}</td><td className="p-3">{patient.clinician}</td><td className="p-3">{patient.nextAppointment}</td><td className="p-3">{patient.progress}%</td><td className="p-3">{pill(patient.status)}</td></tr>)}</tbody></table></div></section>;
}

export function DemoPatientDetail({ patient }: { patient: DemoPatient }) { const [note, setNote] = useState(''); const [notes, setNotes] = useState<string[]>([]); return <section className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">{patient.patient_number} · synthetic record</p><h1 className="text-2xl font-bold">{patient.full_name}</h1><p className="text-slate-600">{patient.treatment} with {patient.clinician}</p></div>{pill(patient.status)}</div><section className="dashboard-metrics"><div className="metric-card"><p>Care progress</p><b>{patient.progress}%</b><small>Temporary demo status</small></div><div className="metric-card"><p>Session notes</p><b>{patient.notes + notes.length}</b><small>Synthetic entries</small></div><div className="metric-card"><p>Next appointment</p><b className="text-lg">{patient.nextAppointment}</b><small>Demo schedule</small></div></section><div className="dashboard-columns"><DemoSection title="Care timeline"><div className="dashboard-list"><div className="list-item"><div><b>Progress review</b><small>Care plan remains on track · synthetic entry</small></div>{pill('Completed')}</div><div className="list-item"><div><b>Upcoming session</b><small>{patient.nextAppointment} · {patient.clinician}</small></div>{pill('Confirmed')}</div></div></DemoSection><DemoSection title="Add a temporary note"><textarea className="w-full rounded border p-3" value={note} placeholder="Write a demo note…" onChange={event => setNote(event.target.value)} /><button className="button button-primary mt-3" onClick={() => { if (note.trim()) { setNotes(current => [note.trim(), ...current]); setNote(''); } }}>Save temporary note</button>{notes.map((entry,index) => <p className="mt-3 rounded bg-slate-50 p-3 text-sm" key={`${entry}-${index}`}>{entry}</p>)}</DemoSection></div></section>; }

export function DemoSchedule() { return <section className="space-y-5"><div><p className="eyebrow">Clinical workflow</p><h1 className="text-2xl font-bold">Today&apos;s schedule</h1><p className="text-slate-600">Appointments and care handoffs using fictional demo records.</p></div><div className="card overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-slate-500"><tr>{['Time','Client','Clinician','Care focus','Status'].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{demoAppointments.map(item => <tr className="border-b" key={item.id}><td className="p-3 font-medium">{item.time}</td><td className="p-3">{item.patient}</td><td className="p-3">{item.clinician}</td><td className="p-3">{item.treatment}</td><td className="p-3">{pill(item.status)}</td></tr>)}</tbody></table></div></section>; }

export function DemoNotifications() { const [items, setItems] = useState(demoNotifications); return <section className="space-y-5"><div><p className="eyebrow">In-app only</p><h1 className="text-2xl font-bold">Notifications</h1><p className="text-slate-600">Push delivery is disabled in the public demo.</p></div><div className="card divide-y">{items.map(item => <div className="flex items-start justify-between gap-4 p-4" key={item.id}><div><b>{item.title}</b><p className="text-sm text-slate-600">{item.body}</p><small>{item.when}</small></div>{!item.read && <button className="text-button" onClick={() => setItems(current => current.map(entry => entry.id === item.id ? { ...entry, read: true } : entry))}>Mark read</button>}</div>)}</div></section>; }

export function DemoReports() { return <section className="space-y-5"><div><p className="eyebrow">Portfolio analytics</p><h1 className="text-2xl font-bold">Operations overview</h1><p className="text-slate-600">Illustrative local data only. Export and report generation are disabled.</p></div><section className="dashboard-metrics">{[['Client engagement','82%'],['Care plans on track','14 / 18'],['Scheduled this week','26'],['Team capacity','76%']].map(([label,value]) => <div className="metric-card" key={label}><p>{label}</p><b>{value}</b><small>Synthetic demo metric</small></div>)}</section><div className="card p-5"><h2 className="font-semibold">Monthly appointment activity</h2><div className="mt-5 flex h-44 items-end gap-3">{[42,58,51,68,62,76].map((height,index) => <div className="flex flex-1 flex-col items-center gap-2" key={height}><div className="w-full rounded-t bg-sky-600" style={{height: `${height * 2}px`}} /><small>{['Apr','May','Jun','Jul','Aug','Sep'][index]}</small></div>)}</div></div></section>; }

function DemoSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="dashboard-section"><div className="section-heading"><h3>{title}</h3></div>{children}</section>; }
