'use client';

import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { adminRepository } from '@/lib/admin-repository';
import { inr } from '@/components/finance-ui';
import { currentProfile } from '@/lib/auth';
import { dashboardTitle, isSecurityAdministratorRole } from '@/lib/permission-access';
import { doctorSchedulingRepository } from '@/lib/doctor-scheduling-repository';
import { CustomerFeedbackDashboardWidget } from '@/components/customer-feedback-dashboard-widget';
import { employeeRepository } from '@/lib/employee-repository';
import { freshLocation, locationBlockedMessage, locationCheckingMessage } from '@/lib/attendance-geofence';
import { TeamAttendanceStrip, type TeamMember } from '@/components/team-attendance-strip';
import { ModuleIcon } from '@/components/module-icon';

const fmtDate = (value?: string) => value ? new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short' }).format(new Date(value)) : 'Not scheduled';

export default function ExecutiveDashboard() {
  const [summary, setSummary] = useState<any>(); const [finance, setFinance] = useState<any>(); const [audit, setAudit] = useState<any[]>([]); const [documents, setDocuments] = useState<any[]>([]); const [doctorSchedule, setDoctorSchedule] = useState<any>(); const [profile, setProfile] = useState<any>(); const [todayAttendance, setTodayAttendance] = useState<any>(); const [team, setTeam] = useState<TeamMember[]>(); const [canViewTeam, setCanViewTeam] = useState(false); const [canOpenEmployees, setCanOpenEmployees] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [role, setRole] = useState<string>(); const [refreshingAttendance, setRefreshingAttendance] = useState(false);
  const [attendanceError, setAttendanceError] = useState('');
  const [attendanceStatus, setAttendanceStatus] = useState('');
  const attendanceRequest = useRef(false);
  const load = async () => { const profilePromise = currentProfile().catch(() => null); const schedulingAccessPromise = doctorSchedulingRepository.permissions().catch(() => ({} as Record<string, boolean>)); const accessPromise = employeeRepository.grantedPermissions(['attendance.view', 'attendance.view_team', 'employees.view']).catch(() => new Set<string>()); const primaryPromise = Promise.allSettled([adminRepository.superAdminDashboard(), adminRepository.financeDashboard()]); void primaryPromise.then(primary => { const [summaryResult, financeResult] = primary; if (summaryResult.status === 'fulfilled') setSummary(summaryResult.value); if (financeResult.status === 'fulfilled') setFinance(financeResult.value); if (primary.some(result => result.status === 'rejected')) setError('Primary dashboard data could not be refreshed.'); }); const [signedInProfile, schedulingAccess, access] = await Promise.all([profilePromise, schedulingAccessPromise, accessPromise]); if (signedInProfile) { setProfile(signedInProfile); setRole(signedInProfile.role); } const teamAccess = access.has('attendance.view') || access.has('attendance.view_team'); setCanViewTeam(teamAccess); setCanOpenEmployees(access.has('employees.view')); const secondary = await Promise.allSettled([isSecurityAdministratorRole(signedInProfile?.role) ? adminRepository.audit() : Promise.resolve([]), adminRepository.documentRequests(), schedulingAccess['doctor_scheduling.view'] ? doctorSchedulingRepository.summary() : Promise.resolve(null), signedInProfile ? employeeRepository.attendanceToday(signedInProfile.id) : Promise.resolve({attendance:null}), teamAccess ? employeeRepository.teamAttendanceToday() : Promise.resolve(null)]); const [auditResult, documentResult, doctorScheduleResult, attendanceResult, teamResult] = secondary; if (auditResult.status === 'fulfilled') setAudit(auditResult.value); if (documentResult.status === 'fulfilled') setDocuments(documentResult.value); if (doctorScheduleResult.status === 'fulfilled') setDoctorSchedule(doctorScheduleResult.value); if (attendanceResult.status === 'fulfilled') setTodayAttendance(attendanceResult.value.attendance); if (teamResult.status === 'fulfilled' && teamResult.value) setTeam(teamResult.value.employees); if (secondary.some(result => result.status === 'rejected')) setError(current => current || 'Some secondary dashboard data could not be refreshed.'); };
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  const title = dashboardTitle(role);
  const securityAdministrator = isSecurityAdministratorRole(role);
  useEffect(() => { document.title = `${title} | BSmile CRM`; }, [title]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 3500); return () => window.clearTimeout(timer); }, [notice]);
  const currentMonth = new Date().toISOString().slice(0, 7);
  const previousMonthDate = new Date(); previousMonthDate.setMonth(previousMonthDate.getMonth() - 1); const previousMonth = previousMonthDate.toISOString().slice(0, 7);
  const monthly = useMemo(() => monthTotals(finance?.monthly || [], currentMonth, previousMonth), [finance, currentMonth, previousMonth]);
  const activeBreak = todayAttendance?.attendance_breaks?.find((item: any) => !item.ended_at);
  const attendanceTotal = Math.max(1, (summary?.presentToday || 0) + (summary?.lateToday || 0) + (summary?.onLeave || 0) + Math.max(0, (summary?.employees || 0) - (summary?.presentToday || 0) - (summary?.onLeave || 0)));
  const absent = Math.max(0, (summary?.employees || 0) - (summary?.presentToday || 0) - (summary?.onLeave || 0));
  const pendingApprovals = [{ label: 'Leave requests', value: summary?.pendingLeave || 0, href: '/admin/leaves', icon: '◷' }, { label: 'Payroll items', value: finance?.salariesPending ? 1 : 0, href: '/admin/finance/payroll', icon: '₹' }, { label: 'Document reviews', value: documents.filter(item => ['requested', 'submitted'].includes(item.status)).length, href: '/admin/documents', icon: '▣' }, { label: 'Overdue tasks', value: summary?.overdueTasks || 0, href: '/admin/tasks', icon: '✓' }];

  const attendanceAction = async (action: 'clockIn' | 'clockOut' | 'startBreak' | 'endBreak') => { if (!profile || attendanceRequest.current) return; attendanceRequest.current = true; setRefreshingAttendance(true); setNotice(''); setAttendanceError(''); try { if (action === 'clockIn' || action === 'clockOut') setAttendanceStatus(locationCheckingMessage); if (action === 'clockIn') await employeeRepository.clockIn(profile.id, await freshLocation('Clock In')); if (action === 'clockOut' && todayAttendance) await employeeRepository.clockOut(todayAttendance.id, await freshLocation('Clock Out')); if (action === 'startBreak' && todayAttendance) await employeeRepository.startBreak(todayAttendance.id); if (action === 'endBreak' && activeBreak) await employeeRepository.endBreak(activeBreak.id); const confirmed = await employeeRepository.attendanceToday(profile.id); const confirmedBreak = confirmed.attendance?.attendance_breaks?.some((item: any) => !item.ended_at); if (!confirmed.attendance?.clock_in || (action === 'clockOut' && !confirmed.attendance.clock_out) || (action === 'startBreak' && !confirmedBreak) || (action === 'endBreak' && confirmedBreak)) throw new Error('Attendance update could not be confirmed. Please try again.'); setTodayAttendance(confirmed.attendance); await load(); setNotice(action === 'clockIn' ? 'Clocked in.' : action === 'clockOut' ? 'Clocked out.' : action === 'startBreak' ? 'Break started.' : 'Break ended.'); } catch (caughtError: any) { console.error('GM attendance action failed', caughtError); setAttendanceError(caughtError.message || 'Attendance could not be updated.'); } finally { attendanceRequest.current = false; setAttendanceStatus(''); setRefreshingAttendance(false); } };
  if (!summary) return <DashboardSkeleton />;
  const presentPercent = Math.round(((summary.presentToday || 0) / Math.max(1, summary.employees || 1)) * 100);
  const conversion = summary.leads ? Math.round(((summary.sales || 0) / summary.leads) * 100) : 0;
  const kpis = [
    { icon: 'Employees', tone: 'people', title: 'Total employees', value: summary.employees, detail: `${summary.presentToday || 0} active today`, href: '/admin/employees' },
    { icon: 'Attendance', tone: 'attendance', title: 'Present today', value: summary.presentToday, detail: `${presentPercent}% attendance`, href: '/admin/attendance' },
    { icon: 'Leads', tone: 'crm', title: 'Active leads', value: summary.leads, detail: `${summary.newLeads || 0} new today`, href: '/admin/crm' },
    { icon: 'Finance Dashboard', tone: 'finance', title: 'Monthly revenue', value: inr(monthly.income), detail: trendLabel(monthly.income, monthly.previousIncome), href: '/admin/finance' },
    { icon: 'Leave', tone: 'leave', title: 'Pending leave', value: summary.pendingLeave, detail: 'Requires review', href: '/admin/leaves' },
    { icon: 'Tasks', tone: 'tasks', title: 'Open tasks', value: summary.openTasks, detail: `${summary.overdueTasks || 0} overdue`, href: '/admin/tasks' },
    { icon: 'Invoices', tone: 'finance', title: 'Outstanding invoices', value: inr(finance?.outstandingAmount || 0), detail: `${finance?.outstanding || 0} unpaid invoice${finance?.outstanding === 1 ? '' : 's'}`, href: '/admin/finance/invoices' },
    { icon: 'Payroll', tone: 'finance', title: 'Payroll status', value: finance?.salariesPending ? 'Pending' : 'Clear', detail: finance?.recentRuns?.find((run: any) => run.status !== 'paid') ? `Period ends ${fmtDate(finance.recentRuns.find((run: any) => run.status !== 'paid').period_end)}` : 'No pending payroll', href: '/admin/finance/payroll' },
  ];

  const displayDate = new Intl.DateTimeFormat('en', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date());
  const attentionItems = [
    { label: 'Overdue tasks', value: summary.overdueTasks || 0, href: '/admin/tasks' },
    { label: 'Follow-ups due', value: summary.followupsDue || 0, href: '/admin/crm/follow-ups' },
    { label: 'Leave requests', value: summary.pendingLeave || 0, href: '/admin/leaves' },
    { label: 'Document reviews', value: documents.filter(item => ['requested', 'submitted'].includes(item.status)).length, href: '/admin/documents' },
  ].filter(item => item.value > 0);
  return <section className="executive-dashboard">
    <header className="executive-header"><div><h1>{title}</h1><p>Company operations at a glance · <time>{displayDate}</time></p></div><div className="executive-header-actions"><Link className="btn btn-primary" href={securityAdministrator ? '/admin/access' : '/admin/profile'}>{securityAdministrator ? 'Profile & access' : 'My profile'}</Link></div></header>
    {error && <p className="executive-alert">{error} Available sections still show live data.</p>}

    <div className="executive-kpis executive-kpis-primary">{kpis.slice(0, 4).map(kpi => <Link href={kpi.href} className={`executive-kpi executive-kpi-${kpi.tone}`} key={kpi.title}><ModuleIcon label={kpi.icon} className="executive-kpi-icon" /><div><p>{kpi.title}</p><b>{kpi.value}</b><small>{kpi.detail}</small></div><span className="executive-arrow">→</span></Link>)}</div>
    <section className="standard-needs-attention"><div className="attention-heading"><div><h2>Needs attention</h2><p>Priority work requiring management review</p></div><Link href="/admin/tasks">View all</Link></div>{attentionItems.length ? <div className="attention-list">{attentionItems.slice(0, 3).map(item => <Link href={item.href} key={item.label}><span>{item.label}</span><b>{item.value}</b><i>Review →</i></Link>)}</div> : <p className="attention-clear">Nothing overdue or due soon.</p>}</section>

    <div className="executive-grid executive-grid-primary"><DashboardCard title="Attendance overview" subtitle="Today’s live workforce status" action={<Link href="/admin/attendance">View attendance</Link>}><div className="attendance-overview"><div className="attendance-ring" style={{ background: `conic-gradient(#007d74 0 ${presentPercent}%, #eab308 ${presentPercent}% ${Math.min(100, presentPercent + Math.round((summary.lateToday / attendanceTotal) * 100))}%, #60a5fa 0 ${Math.min(100, presentPercent + Math.round(((summary.lateToday + summary.onLeave) / attendanceTotal) * 100))}%, #f3f4f6 0)` }}><div><b>{presentPercent}%</b><small>present</small></div></div><div className="attendance-legend"><Legend label="Present" value={summary.presentToday} tone="teal" /><Legend label="Late" value={summary.lateToday} tone="amber" /><Legend label="Leave" value={summary.onLeave} tone="blue" /><Legend label="Absent" value={absent} tone="slate" /></div></div><p className="card-footnote">{summary.presentToday} clocked in across {summary.employees} active employees today.</p></DashboardCard><DashboardCard title="Quick actions" subtitle="Common management workflows"><div className="quick-action-grid">{[['Add employee','Employees','/admin/employees'],['New lead','Leads','/admin/crm'],['Create invoice','Invoices','/admin/finance/invoices/new'],['Announcement','Announcements','/admin/announcements'],['Grant access','Roles & Access','/admin/access'],['View reports','Reports','/admin/finance/reports']].filter(([, , href]) => securityAdministrator || href !== '/admin/access').map(([label, icon, href]) => <Link className="quick-action" href={href} key={label}><ModuleIcon label={icon} /><span className="quick-action-copy">{label}<small>Open workspace</small></span><i>→</i></Link>)}</div></DashboardCard></div>

    <details className="dashboard-more-insights"><summary><span><b>More insights</b><small>Attendance, finance, CRM, approvals, activity, and calendar</small></span><i>Show details</i></summary><div className="dashboard-more-content">
    <section className="my-attendance-card"><div><p className="eyebrow">MY ATTENDANCE</p><h2>{!todayAttendance ? 'Not clocked in' : todayAttendance.clock_out ? 'Day completed' : activeBreak ? 'On break' : 'Working today'}</h2><p>Clock in: <b>{attendanceTime(todayAttendance?.clock_in)}</b> · Break: <b>{activeBreak ? attendanceTime(activeBreak.started_at) : todayAttendance?.break_minutes ? `${todayAttendance.break_minutes} min` : '--'}</b> · Clock out: <b>{attendanceTime(todayAttendance?.clock_out)}</b></p></div><div className="my-attendance-actions">{!todayAttendance && <button className="btn btn-primary" disabled={refreshingAttendance} onClick={() => void attendanceAction('clockIn')}>Clock in</button>}{todayAttendance && !todayAttendance.clock_out && !activeBreak && <><button className="btn" disabled={refreshingAttendance} onClick={() => void attendanceAction('startBreak')}>Start break</button><button className="btn btn-primary" disabled={refreshingAttendance} onClick={() => void attendanceAction('clockOut')}>Clock out</button></>}{activeBreak && <button className="btn btn-primary" disabled={refreshingAttendance} onClick={() => void attendanceAction('endBreak')}>End break</button>}</div></section>
    {attendanceStatus && <p className="executive-notice" role="status">{attendanceStatus}</p>}
    {attendanceError && <p className="executive-alert">{attendanceError} {attendanceError === locationBlockedMessage && <button className="btn" disabled={refreshingAttendance} onClick={() => void attendanceAction(todayAttendance && !todayAttendance.clock_out ? 'clockOut' : 'clockIn')}>Try again</button>}</p>}
    {notice && <p className="executive-notice" role="status">{notice}</p>}
    {canViewTeam && <TeamAttendanceStrip employees={team} loading={!team} canOpenEmployees={canOpenEmployees} standardHub />}
    <div className="executive-kpis executive-kpis-secondary">{kpis.slice(4).map(kpi => <Link href={kpi.href} className={`executive-kpi executive-kpi-${kpi.tone}`} key={kpi.title}><ModuleIcon label={kpi.icon} className="executive-kpi-icon" /><div><p>{kpi.title}</p><b>{kpi.value}</b><small>{kpi.detail}</small></div><span className="executive-arrow">→</span></Link>)}</div>

    <div className="executive-grid executive-grid-primary"><DashboardCard title="Revenue overview" subtitle="Current month cash movement" action={<Link href="/admin/finance">Open finance</Link>}><div className="revenue-stats"><Stat label="Income" value={inr(monthly.income)} tone="teal" /><Stat label="Expenses" value={inr(monthly.expenses)} tone="rose" /><Stat label="Profit" value={inr(monthly.income - monthly.expenses)} tone="blue" /></div><MiniBars data={[monthly.previousIncome, monthly.income, monthly.previousExpenses, monthly.expenses]} labels={['Prev income', 'This income', 'Prev expenses', 'This expenses']} /></DashboardCard><DashboardCard title="CRM snapshot" subtitle="Lead activity and conversion" action={<Link href="/admin/crm">Open CRM</Link>}><div className="crm-snapshot"><Snapshot label="New leads" value={summary.newLeads || 0} detail="Today" /><Snapshot label="Follow-ups due" value={summary.followupsDue || 0} detail="Action today" /><Snapshot label="Deals won" value={summary.sales || 0} detail="All sales" /><Snapshot label="Conversion" value={`${conversion}%`} detail="Lead to sale" /></div></DashboardCard></div>

    {doctorSchedule && <DashboardCard title="Appointment & Scheduling" subtitle="Outsourced psychologist calendar" action={<Link href="/admin/doctor-scheduling">Open scheduling</Link>}><div className="crm-snapshot"><Snapshot label="Appointments today" value={doctorSchedule.today || 0} detail="Scheduled now" /><Snapshot label="Upcoming" value={doctorSchedule.upcoming || 0} detail="Next 14 days" /><Snapshot label="Available psychologists" value={doctorSchedule.availableDoctorsToday || 0} detail="Today" /><Snapshot label="Changed" value={doctorSchedule.changed || 0} detail="Cancelled or rescheduled" /></div></DashboardCard>}
    <CustomerFeedbackDashboardWidget />

    <div className="executive-grid executive-grid-primary"><DashboardCard title="Pending approvals" subtitle="Items that need management attention" action={<Link href="/admin/documents">Review all</Link>}><div className="approval-list">{pendingApprovals.map(item => <Link href={item.href} className="approval-row" key={item.label}><span>{item.icon}</span><div><b>{item.label}</b><small>{item.value ? `${item.value} awaiting attention` : 'Nothing waiting'}</small></div><strong className={item.value ? 'attention' : ''}>{item.value}</strong><span className="approval-action">Review →</span></Link>)}</div></DashboardCard><DashboardCard title="Recent activity" subtitle="Latest audit events" action={securityAdministrator ? <Link href="/admin/access">View audit log</Link> : undefined}><div className="activity-list">{audit.slice(0, 6).map(event => <div className="activity-row" key={event.id}><span className="activity-dot" /><div><b>{event.action} {event.entity_type}</b><small>{event.actor_id ? `Changed by ${event.actor_id.slice(0, 8)}` : 'System event'} · {new Date(event.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></div></div>)}{!audit.length && <Empty label="No recent activity is available yet." />}</div></DashboardCard></div>

    <DashboardCard title="Company calendar" subtitle="Today and the next six days. Leave, payroll, and meeting events appear here when scheduled."><div className="company-calendar">{Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setDate(day.getDate() + index); return <div className={`calendar-day ${index === 0 ? 'calendar-today' : ''}`} key={day.toISOString()}><small>{day.toLocaleDateString('en', { weekday: 'short' })}</small><b>{day.getDate()}</b><span>{index === 0 ? 'Today' : summary.onLeave && index === 1 ? `${summary.onLeave} on leave` : 'No event'}</span></div>; })}</div></DashboardCard>

    <div className="executive-insights"><Insight title="Attendance trend" value={`${presentPercent}%`} detail="Present today" percent={presentPercent} tone="teal" /><Insight title="Revenue trend" value={inr(monthly.income)} detail={trendLabel(monthly.income, monthly.previousIncome)} percent={monthly.income && monthly.previousIncome ? Math.min(100, Math.round((monthly.income / Math.max(monthly.income, monthly.previousIncome)) * 100)) : 0} tone="blue" /><Insight title="Lead conversion trend" value={`${conversion}%`} detail={`${summary.sales || 0} sales from ${summary.leads || 0} leads`} percent={conversion} tone="amber" /></div>
    </div></details>
  </section>;
}

function DashboardCard({ title, subtitle, action, children }: any) { return <section className="executive-card"><div className="executive-card-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action && <div>{action}</div>}</div>{children}</section>; }
function Legend({ label, value, tone }: any) { return <div><span className={`legend-dot ${tone}`} /><b>{value}</b><small>{label}</small></div>; }
function Stat({ label, value, tone }: any) { return <div className={`revenue-stat ${tone}`}><small>{label}</small><b>{value}</b></div>; }
function Snapshot({ label, value, detail }: any) { return <div><small>{label}</small><b>{value}</b><span>{detail}</span></div>; }
function Empty({ label }: { label: string }) { return <p className="executive-empty">{label}</p>; }
function Insight({ title, value, detail, percent, tone }: any) { return <section className="insight-card"><div><p>{title}</p><b>{value}</b><small>{detail}</small></div><div className="insight-track"><span className={tone} style={{ width: `${Math.max(4, percent || 0)}%` }} /></div></section>; }
function MiniBars({ data, labels }: { data: number[]; labels: string[] }) { const max = Math.max(1, ...data); return <div className="mini-bars">{data.map((value, index) => <div key={labels[index]}><span style={{ height: `${Math.max(8, Math.round((value / max) * 100))}%` }} /><small>{labels[index]}</small></div>)}</div>; }
function attendanceTime(value?: string | null) { return value ? new Intl.DateTimeFormat('en', { hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : '--'; }
function monthTotals(rows: any[], current: string, previous: string) { const sum = (month: string, kinds: string[]) => rows.filter(row => String(row.transaction_date || '').startsWith(month) && kinds.includes(row.transaction_type)).reduce((total, row) => total + Number(row.amount || 0), 0); return { income: sum(current, ['income', 'invoice_payment']), expenses: sum(current, ['expense', 'payroll_payment']), previousIncome: sum(previous, ['income', 'invoice_payment']), previousExpenses: sum(previous, ['expense', 'payroll_payment']) }; }
function trendLabel(current: number, previous: number) { if (!previous) return current ? 'First recorded month' : 'No recorded activity'; const change = Math.round(((current - previous) / previous) * 100); return `${change >= 0 ? '+' : ''}${change}% vs last month`; }
function DashboardSkeleton() { return <section><div className="executive-header"><div><p className="eyebrow">EXECUTIVE COMMAND CENTER</p><h1>Management Dashboard</h1><p>Loading live company data…</p></div></div><div className="executive-kpis">{Array.from({ length: 8 }).map((_, index) => <div className="employee-skeleton" key={index} />)}</div></section>; }
