'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { adminRepository } from '@/lib/admin-repository';
import { inr } from '@/components/finance-ui';
import { currentProfile } from '@/lib/auth';
import { dashboardTitle, isSecurityAdministratorRole } from '@/lib/permission-access';

const today = () => new Date().toISOString().slice(0, 10);
const fmtDate = (value?: string) => value ? new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short' }).format(new Date(value)) : 'Not scheduled';

export default function ExecutiveDashboard() {
  const [summary, setSummary] = useState<any>(); const [finance, setFinance] = useState<any>(); const [audit, setAudit] = useState<any[]>([]); const [documents, setDocuments] = useState<any[]>([]); const [error, setError] = useState(''); const [role, setRole] = useState<string>();
  const load = async () => { const profileResult = await Promise.allSettled([currentProfile()]); const profile = profileResult[0].status === 'fulfilled' ? profileResult[0].value : null; if (profile) setRole(profile.role); const results = await Promise.allSettled([adminRepository.superAdminDashboard(), adminRepository.financeDashboard(), isSecurityAdministratorRole(profile?.role) ? adminRepository.audit() : Promise.resolve([]), adminRepository.documentRequests()]); const [summaryResult, financeResult, auditResult, documentResult] = results; if (summaryResult.status === 'fulfilled') setSummary(summaryResult.value); if (financeResult.status === 'fulfilled') setFinance(financeResult.value); if (auditResult.status === 'fulfilled') setAudit(auditResult.value); if (documentResult.status === 'fulfilled') setDocuments(documentResult.value); const failures = results.filter(result => result.status === 'rejected').length; setError(failures ? `${failures} dashboard source${failures === 1 ? '' : 's'} could not be refreshed.` : ''); };
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  const title = dashboardTitle(role);
  const securityAdministrator = isSecurityAdministratorRole(role);
  useEffect(() => { document.title = `${title} | BSmile CRM`; }, [title]);
  const currentMonth = new Date().toISOString().slice(0, 7);
  const previousMonthDate = new Date(); previousMonthDate.setMonth(previousMonthDate.getMonth() - 1); const previousMonth = previousMonthDate.toISOString().slice(0, 7);
  const monthly = useMemo(() => monthTotals(finance?.monthly || [], currentMonth, previousMonth), [finance, currentMonth, previousMonth]);
  const attendanceTotal = Math.max(1, (summary?.presentToday || 0) + (summary?.lateToday || 0) + (summary?.onLeave || 0) + Math.max(0, (summary?.employees || 0) - (summary?.presentToday || 0) - (summary?.onLeave || 0)));
  const absent = Math.max(0, (summary?.employees || 0) - (summary?.presentToday || 0) - (summary?.onLeave || 0));
  const pendingApprovals = [{ label: 'Leave requests', value: summary?.pendingLeave || 0, href: '/admin/employees', icon: '◷' }, { label: 'Payroll items', value: finance?.salariesPending ? 1 : 0, href: '/admin/finance/payroll', icon: '₹' }, { label: 'Document reviews', value: documents.filter(item => ['requested', 'submitted'].includes(item.status)).length, href: '/admin/documents', icon: '▣' }, { label: 'Overdue tasks', value: summary?.overdueTasks || 0, href: '/admin/tasks', icon: '✓' }];

  if (!summary) return <DashboardSkeleton />;
  const presentPercent = Math.round(((summary.presentToday || 0) / Math.max(1, summary.employees || 1)) * 100);
  const conversion = summary.leads ? Math.round(((summary.sales || 0) / summary.leads) * 100) : 0;
  const kpis = [
    { icon: '👥', title: 'Total employees', value: summary.employees, detail: `${summary.presentToday || 0} active today`, href: '/admin/employees' },
    { icon: '◉', title: 'Present today', value: summary.presentToday, detail: `${presentPercent}% attendance`, href: '/admin/employees' },
    { icon: '◎', title: 'Active leads', value: summary.leads, detail: `${summary.newLeads || 0} new today`, href: '/admin/crm' },
    { icon: '₹', title: 'Monthly revenue', value: inr(monthly.income), detail: trendLabel(monthly.income, monthly.previousIncome), href: '/admin/finance' },
    { icon: '◷', title: 'Pending leave', value: summary.pendingLeave, detail: 'Requires review', href: '/admin/employees' },
    { icon: '✓', title: 'Open tasks', value: summary.openTasks, detail: `${summary.overdueTasks || 0} overdue`, href: '/admin/tasks' },
    { icon: '▤', title: 'Outstanding invoices', value: inr(finance?.outstandingAmount || 0), detail: `${finance?.outstanding || 0} unpaid invoice${finance?.outstanding === 1 ? '' : 's'}`, href: '/admin/finance/invoices' },
    { icon: '▣', title: 'Payroll status', value: finance?.salariesPending ? 'Pending' : 'Clear', detail: finance?.recentRuns?.find((run: any) => run.status !== 'paid') ? `Period ends ${fmtDate(finance.recentRuns.find((run: any) => run.status !== 'paid').period_end)}` : 'No pending payroll', href: '/admin/finance/payroll' },
  ];

  return <section className="executive-dashboard">
    <header className="executive-header"><div><p className="eyebrow">EXECUTIVE COMMAND CENTER</p><h1>{title}</h1><p>Monitor company operations, employees, CRM, finance, and approvals from one place.</p></div><div className="executive-header-actions"><Link className="btn btn-primary" href="/admin/access">Profile & access</Link></div></header>
    {error && <p className="executive-alert">{error} Available sections still show live data.</p>}

    <div className="executive-kpis">{kpis.map(kpi => <Link href={kpi.href} className="executive-kpi" key={kpi.title}><span className="executive-kpi-icon">{kpi.icon}</span><div><p>{kpi.title}</p><b>{kpi.value}</b><small>{kpi.detail}</small></div><span className="executive-arrow">→</span></Link>)}</div>

    <div className="executive-grid executive-grid-primary"><DashboardCard title="Attendance overview" subtitle="Today’s live workforce status" action={<Link href="/admin/employees">View employees</Link>}><div className="attendance-overview"><div className="attendance-ring" style={{ background: `conic-gradient(#007d74 0 ${presentPercent}%, #eab308 ${presentPercent}% ${Math.min(100, presentPercent + Math.round((summary.lateToday / attendanceTotal) * 100))}%, #60a5fa 0 ${Math.min(100, presentPercent + Math.round(((summary.lateToday + summary.onLeave) / attendanceTotal) * 100))}%, #f3f4f6 0)` }}><div><b>{presentPercent}%</b><small>present</small></div></div><div className="attendance-legend"><Legend label="Present" value={summary.presentToday} tone="teal" /><Legend label="Late" value={summary.lateToday} tone="amber" /><Legend label="Leave" value={summary.onLeave} tone="blue" /><Legend label="Absent" value={absent} tone="slate" /></div></div><p className="card-footnote">{summary.presentToday} clocked in across {summary.employees} active employees today.</p></DashboardCard><DashboardCard title="Quick actions" subtitle="Common management workflows"><div className="quick-action-grid">{[['+ Add employee','/admin/employees'],['+ New lead','/admin/crm'],['+ Create invoice','/admin/finance/invoices/new'],['+ Announcement','/admin/announcements'],['+ Grant access','/admin/access'],['+ View reports','/admin/finance/reports']].filter(([, href]) => securityAdministrator || href !== '/admin/access').map(([label, href]) => <Link className="quick-action" href={href} key={label}>{label}<span>→</span></Link>)}</div></DashboardCard></div>

    <div className="executive-grid executive-grid-primary"><DashboardCard title="Revenue overview" subtitle="Current month cash movement" action={<Link href="/admin/finance">Open finance</Link>}><div className="revenue-stats"><Stat label="Income" value={inr(monthly.income)} tone="teal" /><Stat label="Expenses" value={inr(monthly.expenses)} tone="rose" /><Stat label="Profit" value={inr(monthly.income - monthly.expenses)} tone="blue" /></div><MiniBars data={[monthly.previousIncome, monthly.income, monthly.previousExpenses, monthly.expenses]} labels={['Prev income', 'This income', 'Prev expenses', 'This expenses']} /></DashboardCard><DashboardCard title="CRM snapshot" subtitle="Lead activity and conversion" action={<Link href="/admin/crm">Open CRM</Link>}><div className="crm-snapshot"><Snapshot label="New leads" value={summary.newLeads || 0} detail="Today" /><Snapshot label="Follow-ups due" value={summary.followupsDue || 0} detail="Action today" /><Snapshot label="Deals won" value={summary.sales || 0} detail="All sales" /><Snapshot label="Conversion" value={`${conversion}%`} detail="Lead to sale" /></div></DashboardCard></div>

    <div className="executive-grid executive-grid-primary"><DashboardCard title="Pending approvals" subtitle="Items that need management attention" action={<Link href="/admin/documents">Review all</Link>}><div className="approval-list">{pendingApprovals.map(item => <Link href={item.href} className="approval-row" key={item.label}><span>{item.icon}</span><div><b>{item.label}</b><small>{item.value ? `${item.value} awaiting attention` : 'Nothing waiting'}</small></div><strong className={item.value ? 'attention' : ''}>{item.value}</strong><span className="approval-action">Review →</span></Link>)}</div></DashboardCard><DashboardCard title="Recent activity" subtitle="Latest audit events" action={<Link href="/admin/access">View audit log</Link>}><div className="activity-list">{audit.slice(0, 6).map(event => <div className="activity-row" key={event.id}><span className="activity-dot" /><div><b>{event.action} {event.entity_type}</b><small>{event.actor_id ? `Changed by ${event.actor_id.slice(0, 8)}` : 'System event'} · {new Date(event.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></div></div>)}{!audit.length && <Empty label="No recent activity is available yet." />}</div></DashboardCard></div>

    <DashboardCard title="Company calendar" subtitle="Today and the next six days. Leave, payroll, and meeting events appear here when scheduled."><div className="company-calendar">{Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setDate(day.getDate() + index); const key = day.toISOString().slice(0, 10); const isToday = key === today(); return <div className={`calendar-day ${isToday ? 'calendar-today' : ''}`} key={key}><small>{day.toLocaleDateString('en', { weekday: 'short' })}</small><b>{day.getDate()}</b><span>{isToday ? 'Today' : summary.onLeave && index === 1 ? `${summary.onLeave} on leave` : 'No event'}</span></div>; })}</div></DashboardCard>

    <div className="executive-insights"><Insight title="Attendance trend" value={`${presentPercent}%`} detail="Present today" percent={presentPercent} tone="teal" /><Insight title="Revenue trend" value={inr(monthly.income)} detail={trendLabel(monthly.income, monthly.previousIncome)} percent={monthly.income && monthly.previousIncome ? Math.min(100, Math.round((monthly.income / Math.max(monthly.income, monthly.previousIncome)) * 100)) : 0} tone="blue" /><Insight title="Lead conversion trend" value={`${conversion}%`} detail={`${summary.sales || 0} sales from ${summary.leads || 0} leads`} percent={conversion} tone="amber" /></div>
  </section>;
}

function DashboardCard({ title, subtitle, action, children }: any) { return <section className="executive-card"><div className="executive-card-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action && <div>{action}</div>}</div>{children}</section>; }
function Legend({ label, value, tone }: any) { return <div><span className={`legend-dot ${tone}`} /><b>{value}</b><small>{label}</small></div>; }
function Stat({ label, value, tone }: any) { return <div className={`revenue-stat ${tone}`}><small>{label}</small><b>{value}</b></div>; }
function Snapshot({ label, value, detail }: any) { return <div><small>{label}</small><b>{value}</b><span>{detail}</span></div>; }
function Empty({ label }: { label: string }) { return <p className="executive-empty">{label}</p>; }
function Insight({ title, value, detail, percent, tone }: any) { return <section className="insight-card"><div><p>{title}</p><b>{value}</b><small>{detail}</small></div><div className="insight-track"><span className={tone} style={{ width: `${Math.max(4, percent || 0)}%` }} /></div></section>; }
function MiniBars({ data, labels }: { data: number[]; labels: string[] }) { const max = Math.max(1, ...data); return <div className="mini-bars">{data.map((value, index) => <div key={labels[index]}><span style={{ height: `${Math.max(8, Math.round((value / max) * 100))}%` }} /><small>{labels[index]}</small></div>)}</div>; }
function monthTotals(rows: any[], current: string, previous: string) { const sum = (month: string, kinds: string[]) => rows.filter(row => String(row.transaction_date || '').startsWith(month) && kinds.includes(row.transaction_type)).reduce((total, row) => total + Number(row.amount || 0), 0); return { income: sum(current, ['income', 'invoice_payment']), expenses: sum(current, ['expense', 'payroll_payment']), previousIncome: sum(previous, ['income', 'invoice_payment']), previousExpenses: sum(previous, ['expense', 'payroll_payment']) }; }
function trendLabel(current: number, previous: number) { if (!previous) return current ? 'First recorded month' : 'No recorded activity'; const change = Math.round(((current - previous) / previous) * 100); return `${change >= 0 ? '+' : ''}${change}% vs last month`; }
function DashboardSkeleton() { return <section><div className="executive-header"><div><p className="eyebrow">EXECUTIVE COMMAND CENTER</p><h1>Management Dashboard</h1><p>Loading live company data…</p></div></div><div className="executive-kpis">{Array.from({ length: 8 }).map((_, index) => <div className="employee-skeleton" key={index} />)}</div></section>; }
