'use client';

import { useEffect, useState } from 'react';
import { pushRegistration, pushSupported, vapidKeyBytes } from '@/lib/push-client';

type Device = { id: string; device_name: string | null; browser_name: string | null; platform: string | null; created_at: string; is_active: boolean };
type State = 'loading' | 'unsupported' | 'default' | 'granted' | 'denied' | 'subscribed';

const deviceLabel = (device: Device) => [device.browser_name, device.platform].filter(Boolean).join(' on ') || device.device_name || 'This device';

export function BrowserPushSettings() {
  const [state, setState] = useState<State>('loading'); const [devices, setDevices] = useState<Device[]>([]); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const refresh = async () => {
    if (!pushSupported()) { setState('unsupported'); return; }
    const permission = Notification.permission; if (permission === 'denied') { setState('denied'); return; }
    const registration = await pushRegistration(); const subscription = await registration.pushManager.getSubscription(); setState(subscription ? 'subscribed' : permission === 'granted' ? 'granted' : 'default');
    const response = await fetch('/api/push/subscription'); if (response.ok) { const data = await response.json(); setDevices(data.devices || []); }
  };
  useEffect(() => { const timer = window.setTimeout(() => void refresh().catch(() => setState('unsupported')), 0); return () => window.clearTimeout(timer); }, []);
  const enable = async () => { setBusy(true); setNotice(''); try { if (!pushSupported()) throw new Error('unsupported'); const permission = await Notification.requestPermission(); if (permission !== 'granted') { setState('denied'); return; } const publicKey = process.env.NEXT_PUBLIC_WEB_PUSH_VAPID_PUBLIC_KEY; if (!publicKey) throw new Error('not-configured'); const registration = await pushRegistration(); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: vapidKeyBytes(publicKey) }); const response = await fetch('/api/push/subscription', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ subscription: subscription.toJSON(), deviceName: navigator.userAgent }) }); if (!response.ok) throw new Error('save'); setNotice('Desktop notifications are enabled on this device.'); await refresh(); } catch (cause: any) { setNotice(cause.message === 'not-configured' ? 'Desktop notifications are not configured yet.' : 'Notifications could not be enabled on this device. Check your browser settings and try again.'); } finally { setBusy(false); } };
  const disable = async () => { setBusy(true); setNotice(''); try { const registration = await pushRegistration(); const subscription = await registration.pushManager.getSubscription(); if (subscription) { await fetch('/api/push/subscription', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ endpoint: subscription.endpoint }) }); await subscription.unsubscribe(); } setNotice('Desktop notifications are disabled on this device.'); await refresh(); } catch { setNotice('Notifications could not be changed on this device.'); } finally { setBusy(false); } };
  const test = async () => { setBusy(true); setNotice(''); try { const registration = await pushRegistration(); const subscription = await registration.pushManager.getSubscription(); if (!subscription) throw new Error('missing'); const response = await fetch('/api/push/test', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ endpoint: subscription.endpoint }) }); const data = await response.json(); if (response.status === 429) { setNotice('Please wait a few minutes before sending another test notification.'); return; } if (!response.ok || !data.delivered) throw new Error('failed'); setNotice('A test notification was sent to this device.'); } catch { setNotice('The test notification could not be delivered. Your in-app notifications will continue to work.'); } finally { setBusy(false); } };
  const message = state === 'unsupported' ? 'This browser does not support background notifications. You will continue receiving in-app notifications.' : state === 'denied' ? 'Notifications are blocked in your browser settings. Allow notifications for this site to enable alerts.' : state === 'subscribed' ? 'Desktop notifications are enabled on this device.' : state === 'granted' ? 'Permission is granted. Finish enabling notifications on this device.' : 'Enable alerts for messages, tasks, leave decisions, and important announcements.';
  const isAppleMobile = typeof navigator !== 'undefined' && /iPad|iPhone|iPod/.test(navigator.userAgent);
  return <section className="card space-y-4 p-5"><div><h2 className="font-bold">Browser notifications</h2><p className="mt-1 text-sm text-slate-600">{message}</p></div>{state !== 'unsupported' && <div className="flex flex-wrap gap-2">{state === 'subscribed' ? <><button type="button" className="btn border" disabled={busy} onClick={() => void test()}>Send test notification</button><button type="button" className="btn border" disabled={busy} onClick={() => void disable()}>Disable this device</button></> : <button type="button" className="btn btn-primary" disabled={busy || state === 'denied'} onClick={() => void enable()}>{busy ? 'Updating…' : 'Enable notifications'}</button>}</div>}{isAppleMobile && <p className="rounded bg-slate-50 p-3 text-sm text-slate-600">To receive notifications on iPhone or iPad, add BSmile CRM to your Home Screen and open it from there.</p>}{devices.length > 0 && <div><h3 className="text-sm font-semibold">Your active devices</h3><ul className="mt-2 divide-y rounded border text-sm">{devices.filter(device => device.is_active).map(device => <li className="flex justify-between gap-3 p-3" key={device.id}><span className="truncate">{deviceLabel(device)}</span><span className="shrink-0 text-slate-500">Active</span></li>)}</ul></div>}{notice && <p className="text-sm text-slate-600" role="status">{notice}</p>}</section>;
}
