'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { currentProfile } from '@/lib/auth';
import { allowedNextStatuses, ideaAttachmentAccept, ideaPriorities, ideaStatuses, ideaStatusLabel, ideaStatusTone, type IdeaPriority, type IdeaStatus } from '@/lib/idea-rules';
import { ideaRepository, type InnovationFilters } from '@/lib/idea-repository';
import { EmployeeBanner, EmployeeEmptyState, EmployeeLoading, EmployeeMetric, EmployeeMetricGrid, EmployeePageHeader, EmployeeSection, EmployeeStatusBadge } from '@/components/employee-ui';

const formatDate=(value?:string|null)=>value?new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';
const route=(mode:'employee'|'admin',suffix='')=>`${mode==='admin'?'/admin':'/employee'}/innovation${suffix}`;
const emptyForm={title:'',category_id:'',problem_or_opportunity:'',proposed_solution:'',expected_benefit:''};

export function IdeaFeedPage({mode}:{mode:'employee'|'admin'}){
  const [permissions,setPermissions]=useState<Set<string>>(new Set()); const [ideas,setIdeas]=useState<any[]>([]); const [categories,setCategories]=useState<any[]>([]); const [summary,setSummary]=useState<Record<string,number>>({}); const [filters,setFilters]=useState<InnovationFilters>({}); const [draft,setDraft]=useState<InnovationFilters>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const [access,items,categoryRows,counts]=await Promise.all([ideaRepository.permissions(),ideaRepository.feed(filters),ideaRepository.categories(),ideaRepository.summary()]);setPermissions(access);setIdeas(items);setCategories(categoryRows);setSummary(counts);setError('');}catch(caught:any){setError(caught.message||'Innovation Hub is unavailable.');}finally{setLoading(false);}},[filters]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  const management=permissions.has('innovation.view_all')||permissions.has('innovation.review')||permissions.has('innovation.manage');
  if(loading)return <section><EmployeePageHeader title="Innovation & Development" subtitle="Submit improvements and track them through implementation."/><EmployeeLoading cards={5}/></section>;
  return <section className="space-y-4">
    <EmployeePageHeader title="Innovation & Development" subtitle={management?'Review, decide, and track internal improvements.':'Submit an idea and follow its review status.'} action={permissions.has('innovation.create')?<Link className="btn btn-primary" href={route(mode,'/new')}>Submit Idea</Link>:undefined}/>
    {error&&<EmployeeBanner>{error}</EmployeeBanner>}
    {!error&&<EmployeeMetricGrid>{(['submitted','under_review','approved','in_progress','implemented'] as const).map(status=><EmployeeMetric key={status} label={ideaStatusLabel(status)} value={summary[status]||0}/>)}</EmployeeMetricGrid>}
    <EmployeeSection title={management?'Innovation Review Queue':'My Ideas'} description="Results are permission-scoped and limited to the 50 newest matches.">
      <form className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-2 xl:grid-cols-6" onSubmit={event=>{event.preventDefault();setFilters(draft);}}>
        <label className="xl:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-600">Search</span><input className="input w-full" value={draft.search||''} onChange={event=>setDraft({...draft,search:event.target.value})} placeholder="Title, problem, or solution"/></label>
        <FilterSelect label="Status" value={draft.status||''} onChange={value=>setDraft({...draft,status:value})} options={ideaStatuses.map(value=>[value,ideaStatusLabel(value)])}/>
        <FilterSelect label="Category" value={draft.category||''} onChange={value=>setDraft({...draft,category:value})} options={categories.map(item=>[item.id,item.name])}/>
        <FilterSelect label="Priority" value={draft.priority||''} onChange={value=>setDraft({...draft,priority:value})} options={ideaPriorities.map(value=>[value,ideaStatusLabel(value)])}/>
        <div className="flex items-end gap-2"><button className="btn btn-primary flex-1" type="submit">Apply</button><button className="btn border" type="button" onClick={()=>{setDraft({});setFilters({});}}>Clear</button></div>
      </form>
      {ideas.length?<div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Idea</th>{management&&<th className="p-3">Submitter</th>}<th className="p-3">Status</th><th className="p-3">Priority</th><th className="p-3">Owner</th><th className="p-3">Submitted</th><th className="p-3">Target</th><th className="p-3">Progress</th></tr></thead><tbody className="divide-y divide-slate-100">{ideas.map(idea=><tr key={idea.id} className="hover:bg-slate-50"><td className="p-3"><Link className="font-bold text-teal-800 hover:underline" href={route(mode,`/${idea.id}`)}>{idea.title}</Link><small className="block text-slate-500">{idea.category?.name||'Other'}</small></td>{management&&<td className="p-3">{idea.submitter?.full_name||'Employee'}</td>}<td className="p-3"><EmployeeStatusBadge tone={ideaStatusTone(idea.status)}>{ideaStatusLabel(idea.status)}</EmployeeStatusBadge></td><td className="p-3 capitalize">{idea.priority}</td><td className="p-3">{idea.owner?.full_name||'Unassigned'}</td><td className="p-3">{formatDate(idea.created_at)}</td><td className="p-3">{formatDate(idea.target_date)}</td><td className="p-3"><span className="font-semibold">{idea.progress_percent}%</span><span className="ml-2 inline-block h-2 w-20 overflow-hidden rounded bg-slate-100"><i className="block h-full bg-teal-600" style={{width:`${idea.progress_percent}%`}}/></span></td></tr>)}</tbody></table></div>:<EmployeeEmptyState title="No innovation ideas found" detail={Object.keys(filters).length?'Clear or adjust the filters.':'Submit an improvement idea to begin.'}/>}
    </EmployeeSection>
  </section>;
}

function FilterSelect({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<[string,string]>}){return <label><span className="mb-1 block text-xs font-semibold text-slate-600">{label}</span><select className="input w-full" value={value} onChange={event=>onChange(event.target.value)}><option value="">All</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;}

export function IdeaFormPage({mode}:{mode:'employee'|'admin'}){
  const router=useRouter(); const [categories,setCategories]=useState<any[]>([]); const [form,setForm]=useState(emptyForm); const [file,setFile]=useState<File|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{void (async()=>{try{const [access,items]=await Promise.all([ideaRepository.permissions(),ideaRepository.categories()]);if(!access.has('innovation.create'))throw new Error('You do not have permission to submit ideas.');setCategories(items);setForm(current=>({...current,category_id:items[0]?.id||''}));}catch(caught:any){setError(caught.message||'Unable to prepare the form.');}finally{setLoading(false);}})();},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.set(key,value));if(file)body.set('file',file);const response=await fetch('/api/ideas/submit',{method:'POST',body});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to submit idea.');router.push(route(mode,`/${result.id}`));}catch(caught:any){setError(caught.message||'Unable to submit idea.');setSaving(false);}};
  if(loading)return <EmployeeLoading/>;
  return <section className="space-y-4"><EmployeePageHeader title="Submit an Innovation" subtitle="Do not include client names, clinical notes, diagnoses, or confidential finance data."/>{error&&<EmployeeBanner>{error}</EmployeeBanner>}<EmployeeSection title="Proposal" description="Keep the initial proposal clear and focused."><form className="grid gap-4 p-4" onSubmit={submit}><IdeaFields form={form} setForm={setForm} categories={categories}/><label><span className="mb-1 block text-sm font-semibold">Supporting attachment <span className="font-normal text-slate-500">(optional, private, up to 20 MB)</span></span><input className="input w-full" type="file" accept={ideaAttachmentAccept} onChange={event=>setFile(event.target.files?.[0]||null)}/></label><div className="flex flex-wrap justify-end gap-2"><Link className="btn border" href={route(mode)}>Cancel</Link><button className="btn btn-primary" disabled={saving}>{saving?'Submitting…':'Submit Idea'}</button></div></form></EmployeeSection></section>;
}

function IdeaFields({form,setForm,categories}:{form:typeof emptyForm;setForm:(value:typeof emptyForm)=>void;categories:any[]}){return <>
  <label><span className="mb-1 block text-sm font-semibold">Title *</span><input required minLength={5} maxLength={150} className="input w-full" value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label>
  <label><span className="mb-1 block text-sm font-semibold">Category *</span><select required className="input w-full" value={form.category_id} onChange={event=>setForm({...form,category_id:event.target.value})}>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
  <label><span className="mb-1 block text-sm font-semibold">Problem or opportunity *</span><textarea required minLength={20} maxLength={3000} className="input min-h-28 w-full" value={form.problem_or_opportunity} onChange={event=>setForm({...form,problem_or_opportunity:event.target.value})}/></label>
  <label><span className="mb-1 block text-sm font-semibold">Proposed solution *</span><textarea required minLength={20} maxLength={5000} className="input min-h-32 w-full" value={form.proposed_solution} onChange={event=>setForm({...form,proposed_solution:event.target.value})}/></label>
  <label><span className="mb-1 block text-sm font-semibold">Expected benefit <span className="font-normal text-slate-500">(optional)</span></span><textarea maxLength={3000} className="input min-h-24 w-full" placeholder="For example: save time, reduce errors, improve client experience" value={form.expected_benefit} onChange={event=>setForm({...form,expected_benefit:event.target.value})}/></label>
  </>;
}

export function IdeaDetailPage({id,mode}:{id:string;mode:'employee'|'admin'}){
  const [data,setData]=useState<any>(); const [profile,setProfile]=useState<any>(); const [permissions,setPermissions]=useState<Set<string>>(new Set()); const [people,setPeople]=useState<any[]>([]); const [tasks,setTasks]=useState<any[]>([]); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(true);
  const [nextStatus,setNextStatus]=useState<IdeaStatus>('under_review'); const [priority,setPriority]=useState<IdeaPriority>('medium'); const [owner,setOwner]=useState(''); const [targetDate,setTargetDate]=useState(''); const [progress,setProgress]=useState(0); const [decision,setDecision]=useState(''); const [implementation,setImplementation]=useState(''); const [taskId,setTaskId]=useState(''); const [note,setNote]=useState(''); const [visible,setVisible]=useState(true); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const [person,access,detail]=await Promise.all([currentProfile(),ideaRepository.permissions(),ideaRepository.detail(id)]);if(!person)throw new Error('Your session expired.');setProfile(person);setPermissions(access);setData(detail);const manage=access.has('innovation.review')||access.has('innovation.manage');if(manage){const [staff,taskRows]=await Promise.all([ideaRepository.people(),ideaRepository.tasks().catch(()=>[])]);setPeople(staff);setTasks(taskRows);}const idea=detail.idea;setPriority(idea.priority);setOwner(idea.owner_id||'');setTargetDate(idea.target_date||'');setProgress(idea.progress_percent);setDecision(idea.decision_notes||'');setImplementation(idea.implementation_note||'');setTaskId(idea.linked_task_id||'');setNextStatus(idea.status);setError('');}catch(caught:any){setError(caught.message||'This innovation is unavailable.');}finally{setLoading(false);}},[id]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  const saveWorkflow=async()=>{if(!data)return;setSaving(true);setError('');setNotice('');try{await ideaRepository.transition({id,expectedStatus:data.idea.status,nextStatus,priority,ownerId:owner,targetDate,progress,decisionNote:decision,implementationNote:implementation,taskId});setNotice('Innovation workflow updated.');await load();}catch(caught:any){setError(caught.message||'Unable to update workflow.');}finally{setSaving(false);}};
  const addNote=async()=>{if(!profile)return;setSaving(true);try{await ideaRepository.addReviewNote(id,note,profile.id,visible);setNote('');setNotice('Review note added.');await load();}catch(caught:any){setError(caught.message||'Unable to add review note.');}finally{setSaving(false);}};
  if(loading)return <EmployeeLoading cards={5}/>; if(error&&!data)return <section><EmployeePageHeader title="Innovation unavailable" subtitle="The record may be outside your permission scope."/><EmployeeBanner>{error}</EmployeeBanner></section>;
  const idea=data.idea; const canReview=permissions.has('innovation.review')||permissions.has('innovation.manage'); const next=allowedNextStatuses(idea.status as IdeaStatus);
  return <section className="space-y-4"><EmployeePageHeader title={idea.title} subtitle={`${idea.category?.name||'Other'} · submitted ${formatDate(idea.created_at)}`} action={<Link className="btn border" href={route(mode)}>Back to Innovation Hub</Link>}/>{error&&<EmployeeBanner>{error}</EmployeeBanner>}{notice&&<EmployeeBanner tone="success">{notice}</EmployeeBanner>}
    <EmployeeMetricGrid><EmployeeMetric label="Status" value={ideaStatusLabel(idea.status)}/><EmployeeMetric label="Priority" value={ideaStatusLabel(idea.priority)}/><EmployeeMetric label="Progress" value={`${idea.progress_percent}%`}/><EmployeeMetric label="Target" value={formatDate(idea.target_date)}/></EmployeeMetricGrid>
    <EmployeeSection title="Original Proposal" description={`Submitted by ${idea.submitter?.full_name||'Employee'}`}><div className="grid gap-5 p-4"><Block label="Problem or opportunity" value={idea.problem_or_opportunity}/><Block label="Proposed solution" value={idea.proposed_solution}/><Block label="Expected benefit" value={idea.expected_benefit||'Not specified'}/></div></EmployeeSection>
    <EmployeeSection title="Implementation" description="Workflow details do not overwrite the original proposal."><dl className="grid gap-4 p-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Fact label="Owner" value={idea.owner?.full_name||'Unassigned'}/><Fact label="Reviewer" value={idea.reviewer?.full_name||'Unassigned'}/><Fact label="Linked task" value={idea.task?.title||'None'}/><Fact label="Last updated" value={formatDate(idea.updated_at)}/></dl>{idea.decision_notes&&<div className="border-t p-4"><Block label="Decision note" value={idea.decision_notes}/></div>}{idea.implementation_note&&<div className="border-t p-4"><Block label="Implementation note" value={idea.implementation_note}/></div>}</EmployeeSection>
    {data.attachments.length>0&&<EmployeeSection title="Private Attachment"><div className="divide-y">{data.attachments.map((attachment:any)=><button type="button" className="flex w-full justify-between p-4 text-left hover:bg-slate-50" key={attachment.id} onClick={()=>void ideaRepository.openAttachment(id,attachment.id)}><span><b>{attachment.original_file_name}</b><small className="block text-slate-500">{Math.ceil(attachment.file_size/1024)} KB</small></span><span className="font-semibold text-teal-700">Open securely</span></button>)}</div></EmployeeSection>}
    {canReview&&<EmployeeSection title="Management Review" description="Changes are atomic and checked against the current status."><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4"><FilterSelect label="Status" value={nextStatus} onChange={value=>setNextStatus(value as IdeaStatus)} options={[idea.status,...next].map(value=>[value,ideaStatusLabel(value)])}/><FilterSelect label="Priority" value={priority} onChange={value=>setPriority(value as IdeaPriority)} options={ideaPriorities.map(value=>[value,ideaStatusLabel(value)])}/><FilterSelect label="Owner" value={owner} onChange={setOwner} options={people.map(person=>[person.id,person.full_name])}/><label><span className="mb-1 block text-xs font-semibold text-slate-600">Target date</span><input className="input w-full" type="date" value={targetDate} onChange={event=>setTargetDate(event.target.value)}/></label><label><span className="mb-1 block text-xs font-semibold text-slate-600">Progress (0–100)</span><input className="input w-full" type="number" min={0} max={100} value={progress} onChange={event=>setProgress(Number(event.target.value))}/></label><FilterSelect label="Canonical task" value={taskId} onChange={setTaskId} options={tasks.map(task=>[task.id,task.title])}/><label className="md:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-600">Decision / rejection note</span><textarea className="input min-h-20 w-full" value={decision} onChange={event=>setDecision(event.target.value)}/></label><label className="md:col-span-2 xl:col-span-4"><span className="mb-1 block text-xs font-semibold text-slate-600">Implementation note</span><textarea className="input min-h-20 w-full" value={implementation} onChange={event=>setImplementation(event.target.value)}/></label></div><div className="flex justify-end border-t p-4"><button className="btn btn-primary" disabled={saving} onClick={()=>void saveWorkflow()}>{saving?'Saving…':'Update Workflow'}</button></div></EmployeeSection>}
    {canReview&&<EmployeeSection title="Add Review Note"><div className="p-4"><label><span className="mb-1 block text-sm font-semibold">Note</span><textarea className="input min-h-24 w-full" value={note} onChange={event=>setNote(event.target.value)}/></label><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={visible} onChange={event=>setVisible(event.target.checked)}/> Visible to submitter</label><button className="btn btn-primary mt-3" disabled={saving||!note.trim()} onClick={()=>void addNote()}>Add Note</button></div></EmployeeSection>}
    <EmployeeSection title="Review Notes"><div className="divide-y">{data.comments.length?data.comments.map((comment:any)=><article className="p-4" key={comment.id}><div className="flex flex-wrap justify-between gap-2"><b>{comment.author?.full_name||'Reviewer'}</b><small className="text-slate-500">{new Date(comment.created_at).toLocaleString()}</small></div><p className="mt-2 whitespace-pre-wrap text-sm">{comment.content}</p></article>):<EmployeeEmptyState title="No review notes yet" detail="Review notes will appear here."/>}</div></EmployeeSection>
    <EmployeeSection title="History"><div className="divide-y">{data.history.map((row:any)=><article className="p-4 text-sm" key={row.id}><b>{ideaStatusLabel(row.event_type||row.new_status)}</b><span className="text-slate-500"> · {row.actor?.full_name||'System'} · {new Date(row.created_at).toLocaleString()}</span>{row.reason&&<p className="mt-1 text-slate-600">{row.reason}</p>}</article>)}</div></EmployeeSection>
  </section>;
}

function Block({label,value}:{label:string;value:string}){return <div><h3 className="font-bold text-slate-900">{label}</h3><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value}</p></div>;}
function Fact({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-800">{value}</dd></div>;}

export function IdeaCategoriesPage(){return <section className="space-y-4"><EmployeePageHeader title="Innovation Categories" subtitle="Stable filtering categories are managed through the existing category administration."/><EmployeeBanner>Batch 13 preserves the existing category administration and seeds the approved Innovation Hub categories.</EmployeeBanner><Link className="btn border" href="/admin/innovation">Back to Innovation Hub</Link></section>;}
