'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { currentProfile } from '@/lib/auth';
import { ideaAttachmentAccept, ideaStatuses, ideaStatusTone, type IdeaStatus } from '@/lib/idea-rules';
import { ideaRepository, type IdeaPayload } from '@/lib/idea-repository';
import { EmployeeBanner, EmployeeEmptyState, EmployeeLoading, EmployeeMetric, EmployeeMetricGrid, EmployeePageHeader, EmployeeSection, EmployeeStatusBadge } from '@/components/employee-ui';

const emptyForm: IdeaPayload = { title: '', problem_or_opportunity: '', proposed_solution: '', expected_benefit: '', category_id: '' };

const preview = (text: string) => text.length > 160 ? `${text.slice(0, 157)}...` : text;
const initials = (name?: string) => (name || 'B').split(' ').filter(Boolean).slice(0, 2).map(part => part[0]?.toUpperCase()).join('');
const isManager = (profile: any) => ['super_admin', 'chairman', 'director', 'general_manager'].includes(profile?.role);
const date = (value: string) => new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });
const normalize = (value: unknown) => String(value || '').toLowerCase();

export function IdeaFeedPage({ mode }: { mode: 'employee' | 'admin' }) {
  const [profile, setProfile] = useState<any>(); const [ideas, setIdeas] = useState<any[]>([]); const [stats, setStats] = useState<any>(); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [likeBusyId, setLikeBusyId] = useState<string | null>(null);
  const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const [scope, setScope] = useState('all'); const [sort, setSort] = useState('newest');
  const load = useCallback(async () => { setLoading(true); try { const person = await currentProfile(); if (!person) throw new Error('Your session has expired.'); const [items, counts] = await Promise.all([ideaRepository.feed(), mode === 'admin' ? ideaRepository.stats() : Promise.resolve(null)]); setProfile(person); setIdeas(items); setStats(counts); setError(''); } catch (caught: any) { setError(caught.message || 'Unable to load Innovation Hub.'); } finally { setLoading(false); } }, [mode]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const categories = useMemo(() => [...new Map(ideas.map(idea => [idea.category?.id || idea.category?.name || 'Other', idea.category?.name || 'Other'])).entries()], [ideas]);
  const visibleIdeas = useMemo(() => {
    const search = normalize(query);
    const filtered = ideas.filter(idea => {
      const supported = idea.supports?.some((support: any) => support.employee_id === profile?.id);
      const mine = idea.submitted_by === profile?.id;
      const matchesScope = scope === 'all' || (scope === 'mine' && mine) || (scope === 'supported' && supported);
      const matchesStatus = !statusFilter || idea.status === statusFilter;
      const matchesCategory = !categoryFilter || (idea.category?.id || idea.category?.name || 'Other') === categoryFilter;
      const searchable = [idea.title, idea.problem_or_opportunity, idea.proposed_solution, idea.expected_benefit, idea.category?.name, idea.submitter?.full_name, idea.submitter?.department?.name].map(normalize).join(' ');
      return matchesScope && matchesStatus && matchesCategory && (!search || searchable.includes(search));
    });
    return [...filtered].sort((left, right) => {
      if (sort === 'supported') return (right.supports?.length || 0) - (left.supports?.length || 0);
      if (sort === 'discussed') return (right.comments?.filter((comment: any) => !comment.is_deleted).length || 0) - (left.comments?.filter((comment: any) => !comment.is_deleted).length || 0);
      if (sort === 'oldest') return new Date(left.created_at).getTime() - new Date(right.created_at).getTime();
      return new Date(right.created_at).getTime() - new Date(left.created_at).getTime();
    });
  }, [categoryFilter, ideas, profile?.id, query, scope, sort, statusFilter]);
  const featured = useMemo(() => [...ideas].sort((left, right) => (right.supports?.length || 0) - (left.supports?.length || 0) || new Date(right.created_at).getTime() - new Date(left.created_at).getTime())[0], [ideas]);
  const categoryCounts = useMemo(() => Array.from(ideas.reduce((counts, idea) => { const name = idea.category?.name || 'Other'; counts.set(name, (counts.get(name) || 0) + 1); return counts; }, new Map<string, number>()).entries()) as Array<[string, number]>, [ideas]);
  const overview = useMemo(() => stats || { total: ideas.length, submitted: ideas.filter(item => item.status === 'Submitted').length, consideration: ideas.filter(item => item.status === 'Under Consideration').length, implemented: ideas.filter(item => item.status === 'Implemented').length, supports: ideas.reduce((sum, item) => sum + (item.supports?.length || 0), 0), thisMonth: ideas.filter(item => String(item.created_at).startsWith(new Date().toISOString().slice(0, 7))).length }, [ideas, stats]);
  const toggleLike = async (idea: any) => { if (!profile || likeBusyId) return; const liked = idea.supports?.some((row: any) => row.employee_id === profile.id); const oldIdeas = ideas; setLikeBusyId(idea.id); setError(''); setNotice(''); setIdeas(current => current.map(item => item.id === idea.id ? { ...item, supports: liked ? item.supports.filter((row: any) => row.employee_id !== profile.id) : [...(item.supports || []), { id: `local-${Date.now()}`, employee_id: profile.id }] } : item)); setStats((current: any) => current ? { ...current, supports: Math.max(0, current.supports + (liked ? -1 : 1)) } : current); try { await ideaRepository.toggleSupport(idea, profile.id); setNotice(liked ? 'Like removed.' : 'Idea liked.'); } catch (caught: any) { setIdeas(oldIdeas); setStats((current: any) => current ? { ...current, supports: Math.max(0, current.supports + (liked ? 1 : -1)) } : current); setError(caught.message || 'Unable to update like.'); } finally { setLikeBusyId(null); } };
  if (loading) return <section><EmployeePageHeader title="Innovation Hub" subtitle="Share, explore, and engage with practical ideas from across the team." /><EmployeeLoading cards={6} /></section>;
  return <section className="space-y-4">
    <EmployeePageHeader title="Innovation Hub" subtitle="Share, explore, and engage with practical ideas from across the team." action={<div className="flex gap-2"><Link className="btn btn-primary" href={mode === 'admin' ? '/admin/ideas/new' : '/employee/ideas/new'}>＋ Submit Idea</Link>{mode === 'admin' && <Link className="btn border" href="/admin/ideas/categories">▦ Categories</Link>}</div>} />
    {error && <EmployeeBanner>{error}</EmployeeBanner>}
    {notice && <EmployeeBanner tone="success">{notice}</EmployeeBanner>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,2.15fr)_minmax(280px,.85fr)]"><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-bold text-slate-900">Overview</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><HubMetric icon="☼" label="Total Ideas" value={overview.total} tone="text-teal-700 bg-teal-50" /><HubMetric icon="⌁" label="Submitted" value={overview.submitted} tone="text-sky-700 bg-sky-50" /><HubMetric icon="◷" label="Under Review" value={overview.consideration} tone="text-indigo-700 bg-indigo-50" /><HubMetric icon="✓" label="Implemented" value={overview.implemented} tone="text-emerald-700 bg-emerald-50" /><HubMetric icon="♥" label="Total Likes" value={overview.supports} tone="text-rose-700 bg-rose-50" /><HubMetric icon="□" label="This Month" value={overview.thisMonth} tone="text-amber-700 bg-amber-50" /></div><div className="mt-4 grid gap-4 border-t border-slate-100 pt-4 md:grid-cols-2"><div><h3 className="text-sm font-bold text-slate-800">Ideas by Category</h3><div className="mt-3 flex items-center gap-4"><CategoryDonut items={categoryCounts} total={ideas.length} /><div className="min-w-0 space-y-1.5">{categoryCounts.slice(0, 3).map(([name, count], index) => <p className="flex justify-between gap-2 text-xs text-slate-600" key={name}><span className="truncate"><i className={`mr-1.5 inline-block h-2 w-2 rounded-full ${index === 0 ? 'bg-teal-700' : index === 1 ? 'bg-teal-400' : 'bg-amber-400'}`} />{name}</span><b>{count}</b></p>)}</div></div></div><div><h3 className="text-sm font-bold text-slate-800">Ideas by Status</h3><div className="mt-3 space-y-3">{[['Submitted', overview.submitted, 'bg-teal-700'], ['Under Review', overview.consideration, 'bg-sky-400'], ['Implemented', overview.implemented, 'bg-emerald-300']].map(([label, count, color]) => <div className="grid grid-cols-[92px_1fr_22px] items-center gap-2 text-xs" key={String(label)}><span>{label}</span><span className="h-2 rounded-full bg-slate-100"><i className={`block h-2 rounded-full ${color}`} style={{ width: `${overview.total ? Number(count) / overview.total * 100 : 0}%` }} /></span><b>{count}</b></div>)}</div></div></div></section>{featured && <FeaturedIdea idea={featured} profile={profile} liking={likeBusyId === featured.id} onLike={() => void toggleLike(featured)} />}</div>
    <EmployeeSection title="Innovation Hub" description="Search, filter, and like practical ideas from across the team.">
      <div className="grid gap-3 border-b border-slate-100 p-4 lg:grid-cols-[minmax(240px,1fr)_160px_180px_150px]">
        <input aria-label="Search ideas" className="input" placeholder="Search title, benefit, category, or colleague" value={query} onChange={event => setQuery(event.target.value)} />
        <select aria-label="Status" className="input" value={statusFilter} onChange={event => setStatusFilter(event.target.value)}><option value="">All statuses</option>{ideaStatuses.map(value => <option value={value} key={value}>{value}</option>)}</select>
        <select aria-label="Category" className="input" value={categoryFilter} onChange={event => setCategoryFilter(event.target.value)}><option value="">All categories</option>{categories.map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select>
        <select aria-label="Sort ideas" className="input" value={sort} onChange={event => setSort(event.target.value)}><option value="newest">Newest</option><option value="supported">Most liked</option><option value="discussed">Most discussed</option><option value="oldest">Oldest</option></select>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-4 py-3 text-sm">
        <div className="flex flex-wrap gap-2">
          {[['all', 'All Ideas'], ['mine', 'My Ideas'], ['supported', 'Liked']].map(([value, label]) => <button aria-pressed={scope === value} className={`rounded-full border px-3 py-2 text-xs font-bold ${scope === value ? 'border-teal-300 bg-teal-50 text-teal-800' : 'border-slate-200 text-slate-600'}`} key={value} onClick={() => setScope(value)} type="button">{label}</button>)}
        </div>
        <span className="flex items-center gap-2 text-slate-500">{visibleIdeas.length} of {ideas.length} ideas{(query || statusFilter || categoryFilter || scope !== 'all' || sort !== 'newest') && <button className="font-semibold text-teal-700 hover:underline" onClick={() => { setQuery(''); setStatusFilter(''); setCategoryFilter(''); setScope('all'); setSort('newest'); }} type="button">Clear filters</button>}</span>
      </div>
      {visibleIdeas.length ? <div className="divide-y divide-slate-100">{visibleIdeas.map(idea => <IdeaCard key={idea.id} idea={idea} profile={profile} mode={mode} liking={likeBusyId === idea.id} onLike={() => void toggleLike(idea)} />)}</div> : <EmployeeEmptyState title={ideas.length ? 'No matching ideas' : 'No ideas yet'} detail={ideas.length ? 'Adjust the search or filters to widen the Innovation Hub.' : 'Be the first to submit an improvement idea.'} />}
    </EmployeeSection>
  </section>;
}

function HubMetric({ icon, label, value, tone }: { icon: string; label: string; value: number; tone: string }) { return <div className="flex items-center gap-2 rounded-xl border border-slate-100 p-2.5"><span className={`grid h-8 w-8 place-items-center rounded-lg text-sm font-bold ${tone}`}>{icon}</span><span><small className="block text-[11px] text-slate-500">{label}</small><b className="block text-lg leading-none text-slate-900">{value}</b></span></div>; }
function CategoryDonut({ items, total }: { items: Array<[string, number]>; total: number }) { const colors = ['#007d74', '#35c4b2', '#f2b545', '#8abcb6', '#d9a441']; const stops = items.reduce<string[]>((segments, [, count], index) => { const start = items.slice(0, index).reduce((sum, [, earlierCount]) => sum + (total ? earlierCount / total * 360 : 0), 0); const end = start + (total ? count / total * 360 : 0); return [...segments, `${colors[index % colors.length]} ${start}deg ${end}deg`]; }, []); return <div className="grid h-24 w-24 shrink-0 place-items-center rounded-full" style={{ background: stops.length ? `conic-gradient(${stops.join(', ')})` : '#e2e8f0' }}><span className="grid h-14 w-14 place-items-center rounded-full bg-white text-center text-xs"><b className="block text-base">{total}</b>ideas</span></div>; }
function FeaturedIdea({ idea, profile, liking, onLike }: { idea: any; profile: any; liking: boolean; onLike: () => void }) { const liked = idea.supports?.some((support: any) => support.employee_id === profile?.id); const comments = idea.comments?.filter((item: any) => !item.is_deleted).length || 0; return <aside className="flex min-h-[290px] flex-col rounded-2xl border border-teal-100 bg-gradient-to-br from-teal-50/70 to-white p-5 shadow-sm"><div className="flex items-center justify-between text-xs font-bold text-teal-800"><span>Featured Idea</span><span className="rounded-lg bg-teal-100 px-2 py-1">☆ Top liked</span></div><h2 className="mt-5 text-xl font-bold leading-7 text-slate-900">{idea.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{preview(idea.expected_benefit || idea.proposed_solution || '')}</p><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-200 font-bold text-slate-700">{initials(idea.submitter?.full_name)}</span><span>{idea.submitter?.full_name || 'Employee'}<small className="block">{idea.submitter?.department?.name || 'No department'} · {date(idea.created_at)} · {comments} comments</small></span></div><button aria-pressed={liked} className={`btn mt-auto w-full border ${liked ? 'border-teal-300 bg-teal-50 text-teal-800' : 'border-teal-200 bg-white text-teal-800'}`} disabled={liking} onClick={onLike}>{liked ? '♥ Liked' : '♡ Like'} · {idea.supports?.length || 0}</button></aside>; }
function IdeaCard({ idea, profile, mode, liking, onLike }: { idea: any; profile: any; mode: 'employee' | 'admin'; liking: boolean; onLike: () => void }) {
  const liked = idea.supports?.some((support: any) => support.employee_id === profile?.id);
  const href = `${mode === 'admin' ? '/admin' : '/employee'}/ideas/${idea.id}`;
  const comments = idea.comments?.filter((comment: any) => !comment.is_deleted).length || 0;
  return <article className="m-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:border-teal-200 hover:bg-teal-50/20">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
      <Link href={href} className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2"><EmployeeStatusBadge tone={ideaStatusTone(idea.status)}>{idea.status}</EmployeeStatusBadge><span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-semibold text-teal-800">{idea.category?.name || 'Other'}</span></div>
        <h2 className="mt-3 text-lg font-bold text-slate-900">{idea.title}</h2>
        <p className="mt-1 line-clamp-2 text-sm leading-6 text-slate-600">{preview(idea.proposed_solution || '')}</p>
        <div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-100 font-bold text-slate-700">{initials(idea.submitter?.full_name)}</span><span>{idea.submitter?.full_name || 'Employee'}</span><span>{idea.submitter?.department?.name || 'No department'}</span><span>{date(idea.created_at)}</span><span>{comments} comments</span>{idea.attachments?.length > 0 && <span aria-label="Has attachment">⌕ Attachment</span>}</div>
      </Link>
      <button aria-label={`${liked ? 'Unlike' : 'Like'} ${idea.title}; ${idea.supports?.length || 0} likes`} aria-pressed={liked} className={`btn min-h-10 min-w-28 shrink-0 ${liked ? 'border border-teal-300 bg-teal-50 text-teal-800' : 'border'}`} disabled={liking} onClick={onLike} type="button"><span aria-hidden="true">{liked ? '\u2665' : '\u2661'}</span> {liking ? 'Updating...' : liked ? 'Liked' : 'Like'} <span aria-hidden="true">&middot; {idea.supports?.length || 0}</span><span className="sr-only" role="status">{liking ? 'Updating like' : `${idea.supports?.length || 0} likes`}</span></button>
    </div>
  </article>;
}

export function IdeaFormPage({ mode }: { mode: 'employee' | 'admin' }) {
  const router = useRouter();
  const [profile, setProfile] = useState<any>(); const [categories, setCategories] = useState<any[]>([]); const [form, setForm] = useState<IdeaPayload>(emptyForm); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = setTimeout(async () => { try { const person = await currentProfile(); if (!person) throw new Error('Your session has expired.'); const active = await ideaRepository.categories(); setProfile(person); setCategories(active); setForm(current => ({ ...current, category_id: active[0]?.id || '' })); } catch (caught: any) { setError(caught.message || 'Unable to prepare the idea form.'); } finally { setLoading(false); } }, 0); return () => clearTimeout(timer); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!profile) return; setSaving(true); setError(''); try { const payload = new FormData(); Object.entries(form).forEach(([key, value]) => payload.set(key, value)); if (file) payload.set('file', file); const response = await fetch('/api/ideas/submit', { method: 'POST', body: payload }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to submit idea.'); setNotice('Idea submitted and published.'); router.push(`${mode === 'admin' ? '/admin' : '/employee'}/ideas/${body.id}`); } catch (caught: any) { setError(caught.message || 'Unable to submit idea.'); } finally { setSaving(false); } };
  if (loading) return <section><EmployeePageHeader title="Submit Idea" subtitle="Send a practical improvement to the Innovation Hub." /><EmployeeLoading /></section>;
  return <section className="space-y-4"><EmployeePageHeader title="Submit Idea" subtitle="Ideas are published immediately after validation." />{notice && <EmployeeBanner tone="success">{notice}</EmployeeBanner>}{error && <EmployeeBanner>{error}</EmployeeBanner>}<EmployeeSection title="Idea Details" description="Keep it clear and specific so colleagues can understand and like it."><IdeaFields form={form} setForm={setForm} categories={categories} /><div className="border-t border-slate-100 p-4"><label className="text-sm font-semibold text-slate-700">Attachment <span className="font-normal text-slate-500">(optional)</span><input className="input mt-2" type="file" accept={ideaAttachmentAccept} onChange={event => setFile(event.target.files?.[0] || null)} /></label><p className="mt-2 text-xs text-slate-500">PDF, Word, Excel, PNG, or JPG. Maximum 20 MB.</p></div><div className="flex justify-end gap-2 border-t border-slate-100 p-4"><Link href={mode === 'admin' ? '/admin/ideas' : '/employee/ideas'} className="btn border">Cancel</Link><button className="btn btn-primary" disabled={saving} onClick={submit}>{saving ? 'Submitting...' : 'Submit Idea'}</button></div></EmployeeSection></section>;
}

function IdeaFields({ form, setForm, categories }: { form: IdeaPayload; setForm: (value: IdeaPayload) => void; categories: any[] }) {
  return <form className="grid gap-4 p-4" onSubmit={event => event.preventDefault()}>
    <label className="text-sm font-semibold text-slate-700">Idea Title<input required minLength={5} maxLength={150} className="input mt-1" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label>
    <label className="text-sm font-semibold text-slate-700">Category<select required className="input mt-1" value={form.category_id} onChange={event => setForm({ ...form, category_id: event.target.value })}>{categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label>
    <label className="text-sm font-semibold text-slate-700">Problem or Opportunity<textarea required minLength={20} maxLength={3000} className="input mt-1 min-h-28" value={form.problem_or_opportunity} onChange={event => setForm({ ...form, problem_or_opportunity: event.target.value })} /></label>
    <label className="text-sm font-semibold text-slate-700">Proposed Idea or Solution<textarea required minLength={20} maxLength={5000} className="input mt-1 min-h-32" value={form.proposed_solution} onChange={event => setForm({ ...form, proposed_solution: event.target.value })} /></label>
    <label className="text-sm font-semibold text-slate-700">Expected Benefit<textarea required minLength={10} maxLength={3000} className="input mt-1 min-h-24" value={form.expected_benefit} onChange={event => setForm({ ...form, expected_benefit: event.target.value })} /></label>
  </form>;
}

export function IdeaDetailPage({ id, mode }: { id: string; mode: 'employee' | 'admin' }) {
  const [profile, setProfile] = useState<any>(); const [data, setData] = useState<any>(); const [categories, setCategories] = useState<any[]>([]); const [comment, setComment] = useState(''); const [replyTo, setReplyTo] = useState<string | null>(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState<IdeaPayload>(emptyForm); const [status, setStatus] = useState<IdeaStatus>('Submitted'); const [note, setNote] = useState(''); const [response, setResponse] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [likeBusy, setLikeBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [person, detail, active] = await Promise.all([currentProfile(), ideaRepository.detail(id), ideaRepository.categories()]); if (!person) throw new Error('Your session has expired.'); setProfile(person); setData(detail); setCategories(active); setForm({ title: detail.idea.title, problem_or_opportunity: detail.idea.problem_or_opportunity, proposed_solution: detail.idea.proposed_solution, expected_benefit: detail.idea.expected_benefit, category_id: detail.idea.category_id }); setStatus(detail.idea.status); setNote(detail.idea.status_note || ''); setResponse(detail.idea.official_response || ''); setError(''); } catch (caught: any) { setError(caught.message || 'Unable to load idea.'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const idea = data?.idea; const comments = data?.comments || []; const roots = comments.filter((item: any) => !item.parent_comment_id); const replies = (parentId: string) => comments.filter((item: any) => item.parent_comment_id === parentId); const supported = idea?.supports?.some((support: any) => support.employee_id === profile?.id); const canEdit = profile?.id === idea?.submitted_by && idea?.status === 'Submitted';
  if (loading) return <section><EmployeePageHeader title="Idea Details" subtitle="Loading Innovation Hub item." /><EmployeeLoading cards={3} /></section>;
  if (error && !idea) return <section><EmployeePageHeader title="Idea Details" subtitle="Innovation Hub item." /><EmployeeBanner>{error}</EmployeeBanner></section>;
  const addComment = async () => { try { await ideaRepository.addComment(id, profile.id, comment, replyTo); setComment(''); setReplyTo(null); await load(); } catch (caught: any) { setError(caught.message || 'Unable to add comment.'); } };
  const saveEdit = async () => { try { await ideaRepository.updateIdea(id, form); setEditing(false); await load(); } catch (caught: any) { setError(caught.message || 'Unable to update idea.'); } };
  const changeStatus = async () => { try { await ideaRepository.changeStatus(id, status, note, response); await load(); } catch (caught: any) { setError(caught.message || 'Unable to change status.'); } };
  const openAttachment = async (attachment: any) => { const result = await fetch(`/api/ideas/${id}/attachments/${attachment.id}/signed-url`); const body = await result.json(); if (!result.ok) { setError(body.error || 'Unable to open attachment.'); return; } window.open(body.url, '_blank', 'noopener,noreferrer'); };
  const toggleLike = async () => { if (likeBusy || !profile || !idea) return; const liked = idea.supports?.some((support: any) => support.employee_id === profile.id); const originalSupports = idea.supports || []; setLikeBusy(true); setError(''); setNotice(''); setData((current: any) => ({ ...current, idea: { ...current.idea, supports: liked ? originalSupports.filter((support: any) => support.employee_id !== profile.id) : [...originalSupports, { id: `local-${Date.now()}`, employee_id: profile.id }] } })); try { await ideaRepository.toggleSupport(idea, profile.id); setNotice(liked ? 'Like removed.' : 'Idea liked.'); } catch (caught: any) { setData((current: any) => ({ ...current, idea: { ...current.idea, supports: originalSupports } })); setError(caught.message || 'Unable to update like.'); } finally { setLikeBusy(false); } };
  return <section className="space-y-4">
    <EmployeePageHeader title={idea.title} subtitle={`${idea.category?.name || 'Other'} - ${date(idea.created_at)}`} />
    {error && <EmployeeBanner>{error}</EmployeeBanner>}{notice && <EmployeeBanner tone="success">{notice}</EmployeeBanner>}
    <EmployeeMetricGrid columns={3}><EmployeeMetric label="Status" value={<EmployeeStatusBadge tone={ideaStatusTone(idea.status)}>{idea.status}</EmployeeStatusBadge>} /><EmployeeMetric label="Likes" value={idea.supports?.length || 0} /><EmployeeMetric label="Comments" value={comments.filter((item: any) => !item.is_deleted).length} /></EmployeeMetricGrid>
    <EmployeeSection title="Idea" description={`${idea.submitter?.full_name || 'Employee'} - ${idea.submitter?.department?.name || 'No department'}`} action={canEdit && !editing ? <button className="btn border" onClick={() => setEditing(true)}>Edit</button> : undefined}>
      {editing ? <><IdeaFields form={form} setForm={setForm} categories={categories} /><div className="flex justify-end gap-2 border-t border-slate-100 p-4"><button className="btn border" onClick={() => setEditing(false)}>Cancel</button><button className="btn btn-primary" onClick={saveEdit}>Save Idea</button></div></> : <div className="grid gap-4 p-4 text-sm leading-6 text-slate-700"><Block label="Problem or Opportunity" value={idea.problem_or_opportunity} /><Block label="Proposed Idea or Solution" value={idea.proposed_solution} /><Block label="Expected Benefit" value={idea.expected_benefit} />{idea.official_response && <Block label="Official Management Response" value={idea.official_response} />}</div>}
    </EmployeeSection>
    <EmployeeSection title="Engagement" action={<button aria-label={`${supported ? 'Unlike' : 'Like'} ${idea.title}; ${idea.supports?.length || 0} likes`} aria-pressed={supported} className={`btn min-w-28 ${supported ? 'border border-teal-300 bg-teal-50 text-teal-800' : 'border'}`} disabled={likeBusy} onClick={() => void toggleLike()} type="button"><span aria-hidden="true">{supported ? '\u2665' : '\u2661'}</span> {likeBusy ? 'Updating...' : supported ? 'Liked' : 'Like'} <span aria-hidden="true">&middot; {idea.supports?.length || 0}</span><span className="sr-only" role="status">{likeBusy ? 'Updating like' : `${idea.supports?.length || 0} likes`}</span></button>}>
      <div className="border-t border-slate-100 p-4"><textarea className="input min-h-24" placeholder={replyTo ? 'Write a reply' : 'Add a comment'} value={comment} onChange={event => setComment(event.target.value)} /><div className="mt-2 flex justify-end gap-2">{replyTo && <button className="btn border" onClick={() => setReplyTo(null)}>Cancel reply</button>}<button className="btn btn-primary" onClick={addComment}>Post</button></div></div>
      <div className="divide-y divide-slate-100">{roots.map((item: any) => <CommentThread key={item.id} item={item} replies={replies(item.id)} profile={profile} onReply={() => setReplyTo(item.id)} onDeleted={load} />)}{!roots.length && <EmployeeEmptyState title="No comments yet" detail="Start the discussion with a clear note or question." />}</div>
    </EmployeeSection>
    {data.attachments.length > 0 && <EmployeeSection title="Attachment" description="Private file access uses a short-lived signed URL."><div className="divide-y divide-slate-100">{data.attachments.map((attachment: any) => <button className="flex w-full items-center justify-between gap-3 p-4 text-left text-sm hover:bg-slate-50" onClick={() => void openAttachment(attachment)} key={attachment.id}><span><b>{attachment.original_file_name}</b><small className="block text-slate-500">{attachment.file_extension.toUpperCase()} - {Math.ceil(attachment.file_size / 1024)} KB</small></span><span className="font-semibold text-teal-700">Open</span></button>)}</div></EmployeeSection>}
    {mode === 'admin' && isManager(profile) && <EmployeeSection title="Management" description="Change progress status or add an official response."><div className="grid gap-3 p-4 md:grid-cols-3"><select className="input" value={status} onChange={event => setStatus(event.target.value as IdeaStatus)}>{ideaStatuses.map(value => <option key={value}>{value}</option>)}</select><input className="input" placeholder={status === 'Not Proceeding' ? 'Reason required' : 'Status note'} value={note} onChange={event => setNote(event.target.value)} /><input className="input" placeholder="Official response" value={response} onChange={event => setResponse(event.target.value)} /></div><div className="flex justify-end border-t border-slate-100 p-4"><button className="btn btn-primary" onClick={changeStatus}>Update Status</button></div></EmployeeSection>}
    <EmployeeSection title="Status History"><div className="divide-y divide-slate-100">{data.history.map((row: any) => <p className="p-4 text-sm" key={row.id}><b>{row.new_status}</b><span className="text-slate-500"> from {row.previous_status || 'created'} by {row.actor?.full_name || 'System'} on {new Date(row.created_at).toLocaleString()}</span>{row.reason && <span className="block text-slate-600">{row.reason}</span>}</p>)}</div></EmployeeSection>
    <EmployeeSection title="Activity"><div className="divide-y divide-slate-100">{data.activity.map((row: any) => <p className="p-4 text-sm capitalize" key={row.id}>{row.action_type.replaceAll('_', ' ')} <span className="text-slate-500">- {row.actor?.full_name || 'System'} - {new Date(row.created_at).toLocaleString()}</span></p>)}</div></EmployeeSection>
  </section>;
}

function Block({ label, value }: { label: string; value: string }) {
  return <div><h3 className="font-bold text-slate-900">{label}</h3><p className="mt-1 whitespace-pre-wrap">{value}</p></div>;
}

function CommentThread({ item, replies, profile, onReply, onDeleted }: { item: any; replies: any[]; profile: any; onReply: () => void; onDeleted: () => void }) {
  if (item.is_deleted) return <p className="p-4 text-sm text-slate-500">Comment deleted.</p>;
  return <div className="p-4"><Comment item={item} profile={profile} onReply={onReply} onDeleted={onDeleted} />{replies.length > 0 && <div className="mt-3 space-y-3 border-l border-slate-200 pl-4">{replies.map(reply => reply.is_deleted ? <p className="text-sm text-slate-500" key={reply.id}>Reply deleted.</p> : <Comment item={reply} profile={profile} onReply={onReply} onDeleted={onDeleted} key={reply.id} />)}</div>}</div>;
}

function Comment({ item, profile, onReply, onDeleted }: { item: any; profile: any; onReply: () => void; onDeleted: () => void }) {
  return <article><div className="flex items-start gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-700">{initials(item.author?.full_name)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{item.author?.full_name || 'Employee'}</b>{item.is_official_response && <EmployeeStatusBadge tone="info">Official</EmployeeStatusBadge>}<small className="text-slate-500">{new Date(item.created_at).toLocaleString()}</small></div><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.content}</p><div className="mt-2 flex gap-3 text-xs"><button className="font-semibold text-teal-700" onClick={onReply}>Reply</button>{item.author_employee_id === profile?.id && <button className="font-semibold text-rose-700" onClick={async () => { await ideaRepository.deleteComment(item.id, profile.id); onDeleted(); }}>Delete</button>}</div></div></div></article>;
}

export function IdeaCategoriesPage() {
  const [profile, setProfile] = useState<any>(); const [items, setItems] = useState<any[]>([]); const [form, setForm] = useState({ id: '', name: '', description: '', sort_order: 100, is_active: true }); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [person, categories] = await Promise.all([currentProfile(), ideaRepository.categories(true)]); if (!person) throw new Error('Your session has expired.'); setProfile(person); setItems(categories); setError(''); } catch (caught: any) { setError(caught.message || 'Unable to load categories.'); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await ideaRepository.saveCategory({ ...form, actorId: profile.id }); setForm({ id: '', name: '', description: '', sort_order: 100, is_active: true }); await load(); } catch (caught: any) { setError(caught.message || 'Unable to save category.'); } };
  if (loading) return <section><EmployeePageHeader title="Innovation Categories" subtitle="Manage Innovation Hub category options." /><EmployeeLoading /></section>;
  return <section className="space-y-4"><EmployeePageHeader title="Innovation Categories" subtitle="Add, update, reorder, activate, or deactivate submission categories." action={<Link className="btn border" href="/admin/ideas">Innovation Hub</Link>} />{error && <EmployeeBanner>{error}</EmployeeBanner>}<EmployeeSection title={form.id ? 'Edit Category' : 'Add Category'}><form className="grid gap-3 p-4 md:grid-cols-[1fr_1fr_120px_140px_auto]" onSubmit={submit}><input required className="input" placeholder="Category name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /><input className="input" placeholder="Description" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /><input className="input" type="number" value={form.sort_order} onChange={event => setForm({ ...form, sort_order: Number(event.target.value) })} /><label className="flex items-center gap-2 rounded border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={event => setForm({ ...form, is_active: event.target.checked })} /> Active</label><button className="btn btn-primary">{form.id ? 'Save' : 'Add'}</button></form></EmployeeSection><EmployeeSection title="Categories" description="Used categories are deactivated instead of deleted."><div className="divide-y divide-slate-100">{items.map(category => <article className="flex flex-wrap items-center justify-between gap-3 p-4" key={category.id}><div><b>{category.name}</b><p className="text-sm text-slate-500">{category.description || 'No description'} - {category.ideas?.[0]?.count || 0} ideas - order {category.sort_order}</p></div><div className="flex items-center gap-2"><EmployeeStatusBadge tone={category.is_active ? 'success' : 'default'}>{category.is_active ? 'Active' : 'Inactive'}</EmployeeStatusBadge><button className="btn border" onClick={() => setForm({ id: category.id, name: category.name, description: category.description || '', sort_order: category.sort_order, is_active: category.is_active })}>Edit</button></div></article>)}</div></EmployeeSection></section>;
}
