'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { currentProfile } from '@/lib/auth';
import { calendarMeetingRepository } from '@/lib/calendar-meeting-repository';
import { businessTimezone, formatBusinessDateTime, storedToBusinessParts } from '@/lib/calendar-meeting-rules';
import { effectiveMeetingStatus } from '@/lib/meeting-mom';
import { isManagementRole } from '@/lib/permission-access';

type Decision={text:string};type ActionItem={action:string;owner_id:string;due_date:string;status:'pending'|'completed'};
export default function MeetingDetailWorkspace(){
  const {id}=useParams<{id:string}>();const [profile,setProfile]=useState<any>();const [meeting,setMeeting]=useState<any>();const [permissions,setPermissions]=useState<Record<string,boolean>>({});const [discussion,setDiscussion]=useState('');const [additional,setAdditional]=useState('');const [decisions,setDecisions]=useState<Decision[]>([{text:''}]);const [actions,setActions]=useState<ActionItem[]>([{action:'',owner_id:'',due_date:'',status:'pending'}]);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const load=async()=>{const [user,item,perms]=await Promise.all([currentProfile(),calendarMeetingRepository.meeting(id),calendarMeetingRepository.meetingPermissions()]);if(!user)throw Error('Your session has expired.');setProfile(user);setMeeting(item);setPermissions(perms);const note=Array.isArray(item.meeting_notes)?item.meeting_notes[0]:item.meeting_notes;setDiscussion(note?.discussion_summary||'');setAdditional(note?.additional_notes||'');setDecisions(item.meeting_decisions?.length?item.meeting_decisions.sort((a:any,b:any)=>a.position-b.position).map((entry:any)=>({text:entry.decision_text})):[{text:''}]);setActions(item.meeting_action_items?.length?item.meeting_action_items.sort((a:any,b:any)=>a.position-b.position).map((entry:any)=>({action:entry.action_text,owner_id:entry.responsible_user_id||'',due_date:entry.due_date||'',status:entry.status})):[{action:'',owner_id:'',due_date:'',status:'pending'}])};
  useEffect(()=>{let active=true;Promise.all([currentProfile(),calendarMeetingRepository.meeting(id),calendarMeetingRepository.meetingPermissions()]).then(([user,item,perms])=>{if(!active)return;if(!user)throw Error('Your session has expired.');setProfile(user);setMeeting(item);setPermissions(perms);const note=Array.isArray(item.meeting_notes)?item.meeting_notes[0]:item.meeting_notes;setDiscussion(note?.discussion_summary||'');setAdditional(note?.additional_notes||'');setDecisions(item.meeting_decisions?.length?item.meeting_decisions.sort((a:any,b:any)=>a.position-b.position).map((entry:any)=>({text:entry.decision_text})):[{text:''}]);setActions(item.meeting_action_items?.length?item.meeting_action_items.sort((a:any,b:any)=>a.position-b.position).map((entry:any)=>({action:entry.action_text,owner_id:entry.responsible_user_id||'',due_date:entry.due_date||'',status:entry.status})):[{action:'',owner_id:'',due_date:'',status:'pending'}])}).catch(cause=>{if(active)setError(cause.message)});return()=>{active=false}},[id]);
  if(error&&!meeting)return <section className="mx-auto max-w-3xl"><p className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-800">{error}</p></section>;
  if(!meeting)return <p className="p-8 text-sm text-slate-500">Loading meeting…</p>;
  const participants=meeting.meeting_participants||[];const status=effectiveMeetingStatus(meeting);const routeBase=isManagementRole(profile?.role)?'/admin/meetings':'/employee/meetings';const canNotes=status==='completed'&&(permissions['meetings.manage']||(meeting.host_user_id===profile?.id&&permissions['meetings.notes']));const canCancel=meeting.status!=='cancelled'&&(permissions['meetings.manage']||meeting.organizer_id===profile?.id||meeting.host_user_id===profile?.id);
  const saveNotes=async()=>{setBusy('notes');setError('');setNotice('');try{await calendarMeetingRepository.saveMinutes(id,{discussion,additional,decisions:decisions.filter(item=>item.text.trim()),actionItems:actions.filter(item=>item.action.trim())});await load();setNotice('Meeting notes saved. Generate or regenerate the MoM when ready.')}catch(cause:any){setError(cause.message)}finally{setBusy('')}};
  const generate=async()=>{setBusy('mom');setError('');try{const response=await fetch(`/api/meetings/${id}/mom`,{method:'POST'});if(!response.ok){const body=await response.json();throw Error(body.error||'MoM generation failed.')}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=decodeURIComponent(response.headers.get('X-Document-Filename')||`BSmile_MoM_${id}.pdf`);anchor.click();URL.revokeObjectURL(url);await load();setNotice('Minutes of Meeting generated and saved to private history.')}catch(cause:any){setError(cause.message)}finally{setBusy('')}};
  const download=async(documentId:string)=>{setBusy(documentId);setError('');try{const response=await fetch(`/api/meetings/${id}/mom/${documentId}`);const body=await response.json();if(!response.ok)throw Error(body.error||'Unable to open the MoM.');window.open(body.signedUrl,'_blank','noopener,noreferrer')}catch(cause:any){setError(cause.message)}finally{setBusy('')}};
  const cancel=async()=>{const reason=prompt('Cancellation reason');if(!reason)return;setBusy('cancel');try{await calendarMeetingRepository.cancel(id,reason);await load();setNotice('Meeting cancelled and participants notified.')}catch(cause:any){setError(cause.message)}finally{setBusy('')}};
  return <section className="mx-auto max-w-[1180px] space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><Link className="text-sm font-semibold text-teal-700" href={routeBase}>← Meetings</Link><p className="eyebrow mt-4">MEETING HISTORY</p><h1 className="text-2xl font-bold">{meeting.title}</h1><p className="mt-1 text-sm text-slate-600">Current status: <b className="capitalize">{status.replace('_',' ')}</b></p></div>{canCancel&&<button className="btn border border-rose-200 text-rose-700" disabled={busy==='cancel'} onClick={()=>void cancel()}>Cancel meeting</button>}</header>{error&&<p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}{notice&&<p className="rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-900">{notice}</p>}
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-5"><Card title="Meeting information"><dl className="grid gap-4 sm:grid-cols-2"><Info label="Date" value={formatBusinessDateTime(meeting.start_at)}/><Info label="Time" value={`${storedToBusinessParts(meeting.start_at).time} - ${storedToBusinessParts(meeting.end_at).time} · ${businessTimezone}`}/><Info label="Host" value={meeting.host?.full_name||'Host'}/><Info label="Created by" value={meeting.organizer?.full_name||'Creator'}/><Info label="Location" value={meeting.venue||'Not specified'}/><Info label="Location type" value={meeting.meeting_type?.replaceAll('_',' ')||'Office'}/></dl>{meeting.meeting_url&&<a className="mt-4 inline-block font-semibold text-teal-700" href={meeting.meeting_url} target="_blank" rel="noreferrer">Open meeting link ↗</a>}{meeting.cancellation_reason&&<p className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800"><b>Cancellation:</b> {meeting.cancellation_reason}</p>}</Card><Card title="Agenda"><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{meeting.agenda}</p>{meeting.description&&<p className="mt-3 border-t pt-3 text-sm text-slate-600">{meeting.description}</p>}</Card><Card title="Participants"><div className="grid gap-2 sm:grid-cols-2">{participants.map((entry:any)=><div className="rounded-lg border p-3" key={entry.employee_id}><b className="text-sm">{entry.profiles?.full_name}</b><small className="block text-slate-500">{entry.profiles?.designation||'Employee'}</small></div>)}</div></Card></div>
      <div className="space-y-5"><Card title="Progress"><ol className="space-y-3 text-sm">{['Scheduled','Meeting ended','Notes saved','MoM generated'].map((label,index)=>{const done=[true,status==='completed',Boolean(meeting.meeting_notes?.length),Boolean(meeting.meeting_mom_versions?.length)][index];return <li className="flex items-center gap-2" key={label}><span className={`grid h-6 w-6 place-items-center rounded-full text-xs ${done?'bg-teal-700 text-white':'bg-slate-100 text-slate-500'}`}>{done?'✓':index+1}</span>{label}</li>})}</ol></Card><Card title="Activity / audit"><div className="max-h-72 space-y-3 overflow-y-auto">{[...(meeting.meeting_events||[])].sort((a:any,b:any)=>b.created_at.localeCompare(a.created_at)).map((event:any)=><div className="border-l-2 border-teal-200 pl-3 text-sm" key={event.id}><b className="capitalize">{event.event_type.replaceAll('_',' ')}</b><small className="block text-slate-500">{new Date(event.created_at).toLocaleString('en-IN',{timeZone:businessTimezone})}{event.actor?.full_name?` · ${event.actor.full_name}`:''}</small></div>)}{!meeting.meeting_events?.length&&<p className="text-sm text-slate-500">No activity recorded yet.</p>}</div></Card></div></div>
    <Card title="Meeting notes" id="notes"><p className="mb-4 text-sm text-slate-600">Only the approved host or meeting management can edit notes after the scheduled end time. Participants can read final notes.</p><div className="grid gap-4"><label><span className="mb-1 block text-sm font-semibold">Discussion summary</span><textarea className="input min-h-32" disabled={!canNotes} value={discussion} onChange={event=>setDiscussion(event.target.value)}/></label><label><span className="mb-1 block text-sm font-semibold">Additional notes</span><textarea className="input min-h-24" disabled={!canNotes} value={additional} onChange={event=>setAdditional(event.target.value)}/></label><EditorList title="Decisions" disabled={!canNotes} rows={decisions} add={()=>setDecisions([...decisions,{text:''}])}>{decisions.map((item,index)=><div className="flex gap-2" key={index}><input className="input" disabled={!canNotes} value={item.text} onChange={event=>setDecisions(decisions.map((row,rowIndex)=>rowIndex===index?{text:event.target.value}:row))}/>{canNotes&&<button className="btn border" type="button" onClick={()=>setDecisions(decisions.filter((_,rowIndex)=>rowIndex!==index))}>Remove</button>}</div>)}</EditorList><EditorList title="Action items" disabled={!canNotes} rows={actions} add={()=>setActions([...actions,{action:'',owner_id:'',due_date:'',status:'pending'}])}>{actions.map((item,index)=><div className="grid gap-2 rounded-xl border p-3 md:grid-cols-[minmax(220px,1fr)_180px_150px_120px_auto]" key={index}><input className="input" placeholder="Action" disabled={!canNotes} value={item.action} onChange={event=>setActions(actions.map((row,rowIndex)=>rowIndex===index?{...row,action:event.target.value}:row))}/><select className="input" disabled={!canNotes} value={item.owner_id} onChange={event=>setActions(actions.map((row,rowIndex)=>rowIndex===index?{...row,owner_id:event.target.value}:row))}><option value="">Unassigned</option>{participants.map((entry:any)=><option value={entry.employee_id} key={entry.employee_id}>{entry.profiles?.full_name}</option>)}</select><input className="input" type="date" disabled={!canNotes} value={item.due_date} onChange={event=>setActions(actions.map((row,rowIndex)=>rowIndex===index?{...row,due_date:event.target.value}:row))}/><select className="input" disabled={!canNotes} value={item.status} onChange={event=>setActions(actions.map((row,rowIndex)=>rowIndex===index?{...row,status:event.target.value as 'pending'|'completed'}:row))}><option value="pending">Pending</option><option value="completed">Completed</option></select>{canNotes&&<button className="btn border" type="button" onClick={()=>setActions(actions.filter((_,rowIndex)=>rowIndex!==index))}>Remove</button>}</div>)}</EditorList>{canNotes&&<div className="flex justify-end"><button className="btn btn-primary" disabled={busy==='notes'} onClick={()=>void saveNotes()}>{busy==='notes'?'Saving…':'Save notes'}</button></div>}</div></Card>
    <Card title="Minutes of Meeting"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-600">Official letterhead PDF generated only from the persisted notes above.</p><small className="text-slate-500">Previous versions remain private and auditable.</small></div>{canNotes&&<button className="btn btn-primary" disabled={busy==='mom'} onClick={()=>void generate()}>{busy==='mom'?'Generating…':meeting.meeting_mom_versions?.length?'Regenerate MoM':'Generate Minutes of Meeting'}</button>}</div><div className="mt-4 divide-y rounded-xl border">{[...(meeting.meeting_mom_versions||[])].sort((a:any,b:any)=>b.version_number-a.version_number).map((version:any)=><div className="flex flex-wrap items-center justify-between gap-2 p-3 text-sm" key={version.id}><span><b>MoM v{version.version_number}</b><small className="ml-2 text-slate-500">{new Date(version.generated_at).toLocaleString('en-IN',{timeZone:businessTimezone})}</small></span><button className="font-semibold text-teal-700" disabled={busy===version.document_id} onClick={()=>void download(version.document_id)}>Open private PDF</button></div>)}{!meeting.meeting_mom_versions?.length&&<p className="p-4 text-sm text-slate-500">No MoM generated yet.</p>}</div></Card>
  </section>;
}

function Card({title,id,children}:{title:string;id?:string;children:React.ReactNode}){return <section className="card p-5" id={id}><h2 className="mb-4 text-lg font-bold">{title}</h2>{children}</section>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold capitalize">{value}</dd></div>}
function EditorList({title,disabled,rows,add,children}:{title:string;disabled:boolean;rows:any[];add:()=>void;children:React.ReactNode}){return <section><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-semibold">{title}</h3>{!disabled&&<button className="text-sm font-semibold text-teal-700" type="button" onClick={add}>+ Add</button>}</div><div className="space-y-2">{children}{!rows.length&&<p className="text-sm text-slate-500">No {title.toLowerCase()} recorded.</p>}</div></section>}
