'use client';

import { useEffect, useState } from 'react';
import { employeeRepository } from '@/lib/employee-repository';

const categories = ['chat', 'tasks', 'leave', 'attendance', 'crm', 'finance', 'documents', 'announcements', 'security'];
const title = (value: string) => value === 'crm' ? 'CRM' : value[0].toUpperCase() + value.slice(1);
const defaults = { notifications_enabled: true, sounds_enabled: false, desktop_enabled: false, muted: false, volume: 'medium', quiet_hours_enabled: false, quiet_hours_start: '22:00', quiet_hours_end: '08:00', critical_bypasses_quiet_hours: true, category_settings: Object.fromEntries(categories.map(category => [category, { in_app: true, sound: ['chat', 'tasks', 'leave', 'crm', 'finance', 'announcements', 'security'].includes(category), desktop: false }])) };

export function NotificationPreferences({ userId }: { userId: string }) {
  const [preferences, setPreferences] = useState<any>(defaults); const [saving, setSaving] = useState(false); const [status, setStatus] = useState('');
  useEffect(() => { void employeeRepository.notificationPreferences(userId).then(data => { if (data) setPreferences((current: any) => ({ ...current, ...data, category_settings: { ...current.category_settings, ...data.category_settings } })); }).catch(() => setStatus('Preferences are temporarily unavailable.')); }, [userId]);
  const update = (key: string, value: unknown) => setPreferences((current: any) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); setStatus(''); try { await employeeRepository.saveNotificationPreferences(userId, preferences); setStatus('Saved.'); } catch { setStatus('Could not save preferences.'); } finally { setSaving(false); } };
  const testSound = () => { const audio = new Audio('/mixkit-software-interface-start-2574.wav'); audio.volume = 1; audio.muted = false; void audio.play().then(() => { setStatus('Sound played successfully'); console.log('[NotificationAudio][Test] playback resolved'); }).catch(error => { const message = error instanceof Error ? `${error.name}: ${error.message}` : String(error); setStatus(message); console.error('[NotificationAudio][Test] playback rejected', error); }); };
  return <section className="card space-y-4 p-5"><div><h2 className="text-lg font-bold">Notification preferences</h2><p className="text-sm text-slate-600">Choose which important updates can make a sound. Your browser enables audio after you interact with this page.</p></div><audio controls preload="auto" src="/mixkit-software-interface-start-2574.wav" className="w-full" /><div className="grid gap-3 md:grid-cols-2">{[['notifications_enabled', 'Enable in-app notifications'], ['sounds_enabled', 'Enable notification sounds'], ['desktop_enabled', 'Enable desktop notifications'], ['muted', 'Mute all sounds'], ['quiet_hours_enabled', 'Use quiet hours'], ['critical_bypasses_quiet_hours', 'Allow critical alerts during quiet hours']].map(([key, label]) => <label className="flex items-center gap-2 text-sm" key={key}><input type="checkbox" checked={Boolean(preferences[key])} onChange={event => update(key, event.target.checked)} />{label}</label>)}</div><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Sound level<select className="ml-2 rounded border p-2" value={preferences.volume} onChange={event => update('volume', event.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>{preferences.quiet_hours_enabled && <><label className="text-sm">From <input className="ml-1 rounded border p-2" type="time" value={preferences.quiet_hours_start || ''} onChange={event => update('quiet_hours_start', event.target.value)} /></label><label className="text-sm">To <input className="ml-1 rounded border p-2" type="time" value={preferences.quiet_hours_end || ''} onChange={event => update('quiet_hours_end', event.target.value)} /></label></>}</div><div><p className="mb-2 text-sm font-semibold">Sounds by category</p><div className="grid gap-2 sm:grid-cols-2">{categories.map(category => <label className="flex items-center justify-between rounded border p-2 text-sm" key={category}><span>{title(category)}</span><input aria-label={`${title(category)} sound`} type="checkbox" checked={preferences.category_settings?.[category]?.sound !== false} onChange={event => setPreferences((current: any) => ({ ...current, category_settings: { ...current.category_settings, [category]: { ...current.category_settings?.[category], sound: event.target.checked } } }))} /></label>)}</div></div><div className="flex items-center gap-3"><button className="rounded bg-brand px-3 py-2 text-sm text-white disabled:opacity-50" disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save preferences'}</button><button className="rounded border px-3 py-2 text-sm" onClick={testSound}>Test notification sound</button>{status && <span className="text-sm text-slate-600" role="status">{status}</span>}</div></section>;
}
