'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { downloadReportCsv, downloadReportXlsx, type ReportRow } from '@/lib/report-export';
import { grantedPermissions } from '@/lib/granted-permissions';
import { documentExpiryLabel } from '@/lib/document-expiry-rules';
import { employeeStatuses, employeeStatusLabel } from '@/lib/employee-status';
import { downloadOfficialReport } from '@/lib/official-report-download';

const db:any=supabase;
type Key='leads'|'patients'|'employees'|'attendance'|'leave'|'appointments'|'documents'|'finance';
const meta:Record<Key,{label:string;permissions:string[];headers:string[]}>={
 leads:{label:'Leads',permissions:['crm.manage_all','crm.view_team','leads.view'],headers:['Created','Lead name','Phone','Source','Assigned staff','Status','Follow-up','Converted client ID']},
 patients:{label:'Clients',permissions:['patients.view','patients.view_all'],headers:['Client ID','Name','Phone','Email','Status','Source','Assigned psychologist','Created']},
 employees:{label:'Employees',permissions:['employees.view'],headers:['Employee code','Name','Department','Designation','Employment status','Joining date','Manager']},
 attendance:{label:'Attendance',permissions:['attendance.view','attendance.manage'],headers:['Date','Employee','Clock in','Break minutes','Clock out','Status']},
 leave:{label:'Leave',permissions:['leave.view','leave.manage','leave.approve'],headers:['Employee','Leave type','Start','End','Days','Status','Requested']},
 appointments:{label:'Appointments',permissions:['doctor_scheduling.view','appointments.view'],headers:['Appointment','Client','Client ID','Clinician','Clinician type','Status','Created']},
 documents:{label:'Documents',permissions:['documents.manage','documents.employee.manage','patient_documents.view'],headers:['Owner type','Document type','Owner / entity','Expiry date','Status']},
 finance:{label:'Finance',permissions:['reports.view','reports.finance.view','finance.view'],headers:['Date','Type','Account','Category','Description','Amount']},
};
const value=(x:any)=>x||'—'; const date=(x:any)=>x?String(x).slice(0,10):'';
export function OperationalReports(){const [permissions,setPermissions]=useState<Record<string,boolean>>({});const [kind,setKind]=useState<Key>('leads');const [rows,setRows]=useState<ReportRow[]>([]);const [from,setFrom]=useState('');const [to,setTo]=useState('');const [employeeStatus,setEmployeeStatus]=useState('');const [error,setError]=useState('');const [pdfBusy,setPdfBusy]=useState(false);
 useEffect(()=>{if(!db)return;const codes=[...new Set(Object.values(meta).flatMap(x=>x.permissions))];void grantedPermissions(db,codes).then(allowed=>setPermissions(Object.fromEntries(codes.map(code=>[code,allowed.has(code)]))));},[]);
 const allowed=(key:Key)=>meta[key].permissions.some(code=>permissions[code]); const available=(Object.keys(meta) as Key[]).filter(allowed);
 useEffect(()=>{if(available.length&&!allowed(kind))setKind(available[0]);},[permissions]);
 useEffect(()=>{if(!db||!allowed(kind))return;let cancelled=false;setError('');const load=async()=>{let data:any[]=[];
  if(kind==='leads'){let q=db.from('crm_leads').select('lead_date,full_name,phone,source:crm_lead_sources(name),assignee:profiles!crm_leads_assigned_to_fkey(full_name),status:crm_lead_statuses(name),converted_patient:patients!crm_leads_converted_patient_id_fkey(patient_number),crm_lead_followups(next_follow_up_at)').is('archived_at',null).order('lead_date',{ascending:false});if(from)q=q.gte('lead_date',from);if(to)q=q.lte('lead_date',to);const r=await q;if(r.error)throw r.error;data=r.data.map((x:any)=>({'Created':date(x.lead_date),'Lead name':x.full_name,'Phone':x.phone,'Source':value(x.source?.name),'Assigned staff':value(x.assignee?.full_name),'Status':value(x.status?.name),'Follow-up':date(x.crm_lead_followups?.[0]?.next_follow_up_at),'Converted client ID':value(x.converted_patient?.patient_number)}));}
  if(kind==='patients'){let q=db.from('patients').select('patient_number,full_name,phone,email,status,source,created_at,assigned:profiles!patients_assigned_psychologist_id_fkey(full_name)').is('deleted_at',null).order('created_at',{ascending:false});if(from)q=q.gte('created_at',from);if(to)q=q.lte('created_at',`${to}T23:59:59Z`);const r=await q;if(r.error)throw r.error;data=r.data.map((x:any)=>({'Client ID':x.patient_number,'Name':x.full_name,'Phone':value(x.phone),'Email':value(x.email),'Status':x.status,'Source':value(x.source),'Assigned psychologist':value(x.assigned?.full_name),'Created':date(x.created_at)}));}
  if(kind==='employees'){let q=db.from('profiles').select('employee_code,full_name,designation,status,joining_date,department:departments(name),manager:profiles!profiles_manager_id_fkey(full_name)').eq('is_employee',true).eq('workforce_visible',true).order('full_name');if(employeeStatus)q=q.eq('status',employeeStatus);const r=await q;if(r.error)throw r.error;data=r.data.map((x:any)=>({'Employee code':value(x.employee_code),'Name':x.full_name,'Department':value(x.department?.name),'Designation':value(x.designation),'Employment status':employeeStatusLabel(x.status),'Joining date':date(x.joining_date),'Manager':value(x.manager?.full_name)}));}
  if(kind==='attendance'){let q=db.from('attendance').select('work_date,clock_in,clock_out,break_minutes,status,employee:profiles(full_name)').order('work_date',{ascending:false});if(from)q=q.gte('work_date',from);if(to)q=q.lte('work_date',to);const r=await q;if(r.error)throw r.error;data=r.data.map((x:any)=>({'Date':x.work_date,'Employee':value(x.employee?.full_name),'Clock in':value(x.clock_in),'Break minutes':x.break_minutes||0,'Clock out':value(x.clock_out),'Status':x.status}));}
  if(kind==='leave'){const r=await db.from('leave_requests').select('leave_type,starts_on,ends_on,requested_days,status,created_at,employee:profiles!leave_requests_profile_id_fkey(full_name)').order('created_at',{ascending:false});if(r.error)throw r.error;data=r.data.map((x:any)=>({'Employee':value(x.employee?.full_name),'Leave type':x.leave_type,'Start':x.starts_on,'End':x.ends_on,'Days':x.requested_days||'','Status':x.status,'Requested':date(x.created_at)}));}
  if(kind==='appointments'){let q=db.from('doctor_appointments').select('start_at,status,created_at,doctor:outsourced_doctors(doctor_name,clinician_type),patient:patients(full_name,patient_number)').is('deleted_at',null).order('start_at',{ascending:false});if(from)q=q.gte('start_at',from);if(to)q=q.lte('start_at',`${to}T23:59:59Z`);const r=await q;if(r.error)throw r.error;data=r.data.map((x:any)=>({'Appointment':x.start_at,'Patient':value(x.patient?.full_name),'Patient ID':value(x.patient?.patient_number),'Clinician':value(x.doctor?.doctor_name),'Clinician type':value(x.doctor?.clinician_type).replaceAll('_',' '),'Status':x.status,'Created':date(x.created_at)}));}
  if(kind==='documents'){const [company,patient]=await Promise.all([db.from('documents').select('title,category,expiry_date,archived_at').is('archived_at',null),db.from('patient_documents').select('document_name,category,expiry_date,status,patient:patients(full_name)').is('deleted_at',null).neq('status','replaced')]);if(company.error)throw company.error;if(patient.error)throw patient.error;data=[...(company.data||[]).map((x:any)=>({'Owner type':'Operational','Document type':value(x.category),'Owner / entity':x.title,'Expiry date':date(x.expiry_date),'Status':documentExpiryLabel(x.expiry_date)||'Valid'})),...(patient.data||[]).map((x:any)=>({'Owner type':'Patient','Document type':x.category,'Owner / entity':value(x.patient?.full_name),'Expiry date':date(x.expiry_date),'Status':x.status==='archived'?'Archived':documentExpiryLabel(x.expiry_date)||'Valid'}))];}
  if(kind==='finance'){let q=db.from('finance_transactions').select('transaction_date,transaction_type,amount,counterparty_name,description,account:finance_accounts(name),income_category:finance_income_categories(name),expense_category:finance_expense_categories(name)').is('archived_at',null).order('transaction_date',{ascending:false});if(from)q=q.gte('transaction_date',from);if(to)q=q.lte('transaction_date',to);const r=await q;if(r.error)throw r.error;data=r.data.map((x:any)=>({'Date':x.transaction_date,'Type':x.transaction_type,'Account':value(x.account?.name),'Category':value(x.income_category?.name||x.expense_category?.name),'Description':value(x.counterparty_name||x.description),'Amount':x.amount}));}
 if(!cancelled)setRows(data);};void load().catch(e=>!cancelled&&setError(e.message||'Report unavailable.'));return()=>{cancelled=true};},[kind,from,to,employeeStatus,permissions]);
 const headers=meta[kind].headers;const file=`bsmile-${kind}-report`;const pdf=async()=>{setPdfBusy(true);setError('');try{await downloadOfficialReport({reportType:kind,columns:headers.map(header=>({key:header,label:header,align:header==='Amount'?'right':'left',weight:/Description|Name|Owner|Client|Lead/.test(header)?1.45:1})),rows,period:`Period: ${from||'All dates'} - ${to||'All dates'}`,filters:kind==='employees'&&employeeStatus?[`Employment status: ${employeeStatusLabel(employeeStatus)}`]:[],context:{from:from||'all',to:to||'all',employee_status:employeeStatus||'all'},filenameSuffix:`${from||'all'}_${to||'all'}`});}catch(e:any){setError(e.message||'Unable to generate PDF.')}finally{setPdfBusy(false)}};return <section className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Operational reports</h1><p className="text-slate-500">Exports reflect the active report and filters. Sensitive clinical content is excluded.</p></div><div className="flex gap-2 no-print"><button className="btn border" onClick={()=>downloadReportCsv(`${file}.csv`,headers,rows)}>CSV</button><button className="btn border" onClick={()=>void downloadReportXlsx(`${file}.xlsx`,headers,rows)}>Excel</button><button className="btn border" disabled={pdfBusy} onClick={()=>void pdf()}>{pdfBusy?'Generating PDF...':'Download PDF'}</button></div></div>{error&&<p className="text-rose-700">{error}</p>}<div className="card flex flex-wrap gap-2 p-3"><select className="input" value={kind} onChange={e=>setKind(e.target.value as Key)}>{available.map(key=><option key={key} value={key}>{meta[key].label}</option>)}</select>{kind==='employees'&&<select className="input" value={employeeStatus} onChange={e=>setEmployeeStatus(e.target.value)}><option value="">All employment statuses</option>{employeeStatuses.map(status=><option value={status} key={status}>{employeeStatusLabel(status)}</option>)}</select>}<input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="card overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead className="bg-slate-50"><tr>{headers.map(h=><th className="p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr className="border-t" key={i}>{headers.map(h=><td className="p-3" key={h}>{value(row[h])}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-5 text-slate-500">No records match this report.</p>}</div></section>}
