'use client';
import { FormEvent,useState } from 'react';
import Link from 'next/link';
import type { ChatTurn } from '@/lib/policy-assistant-engine';

type Source={section_id:string;document_id:string;title:string;version:string;applicable_to:string;effective_date:string|null;section_number:string|null;section_title:string;page_start:number;page_end:number};
type Message={role:'user'|'assistant';content:string;sources?:Source[];status?:string};
const prompts=['Can employees freelance outside BSmile?','How should I report a missed attendance record?','Can an intern conduct therapy independently?','What is the hiring interview process?'];

export function PolicyAssistant({mode}:{mode:'admin'|'employee'}){
  const [messages,setMessages]=useState<Message[]>([]);const [question,setQuestion]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  async function ask(value:string){const next=value.trim();if(!next||loading)return;setError('');setLoading(true);const prior=messages.map(({role,content})=>({role,content})) as ChatTurn[];setMessages(current=>[...current,{role:'user',content:next}]);setQuestion('');
    try{const response=await fetch('/api/policy-assistant/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:next,history:prior})});const data=await response.json();if(!response.ok&&response.status!==503)throw new Error(data.error||'Unable to ask Policy Assistant.');setMessages(current=>[...current,{role:'assistant',content:data.answer||data.error,sources:data.sources||[],status:data.status}]);}
    catch(reason){setError(reason instanceof Error?reason.message:'Unable to ask Policy Assistant.');}finally{setLoading(false);}}
  function submit(event:FormEvent){event.preventDefault();void ask(question);}
  async function openSource(source:Source){const response=await fetch(`/api/policy-assistant/documents/${source.document_id}/source`);const data=await response.json();if(response.ok)window.open(data.url,'_blank','noopener,noreferrer');else setError(data.error||'Source unavailable.');}
  return <section className="mx-auto max-w-5xl space-y-5">
    <header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">INTERNAL KNOWLEDGE</p><h2 className="text-2xl font-bold text-slate-900">Policy Assistant</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">Ask about current, approved BSmile policies. Answers are grounded in private policy documents and include the exact sources used.</p></div>{mode==='admin'&&<Link className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white" href="/admin/policy-assistant/manage">Manage policies</Link>}</div></header>
    <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="min-h-[420px] space-y-4 p-5" aria-live="polite">
      {!messages.length&&<div className="mx-auto max-w-lg py-16 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-xl bg-teal-50 text-xl text-teal-700">?</div><h3 className="font-semibold text-slate-900">What would you like to clarify?</h3><p className="mt-2 text-sm text-slate-500">I will only answer from approved policy content. If the answer is not there, I’ll say so.</p></div>}
      {messages.map((message,index)=><article key={index} className={message.role==='user'?'ml-auto max-w-[82%] rounded-2xl bg-slate-900 p-4 text-white':'max-w-[92%] rounded-2xl border border-slate-200 bg-slate-50 p-4 text-slate-800'}><p className="whitespace-pre-wrap text-sm leading-6">{message.content}</p>{message.sources?.length?<div className="mt-4 space-y-2 border-t border-slate-200 pt-3"><b className="text-xs uppercase tracking-wide text-slate-500">Approved sources</b>{message.sources.map(source=><button key={source.section_id} onClick={()=>void openSource(source)} className="block w-full rounded-lg border border-slate-200 bg-white p-3 text-left hover:border-teal-400"><span className="block text-sm font-semibold text-slate-800">{source.title} · v{source.version}</span><span className="mt-1 block text-xs text-slate-500">{source.section_number?`${source.section_number} · `:''}{source.section_title} · {source.page_start===source.page_end?`Page ${source.page_start}`:`Pages ${source.page_start}–${source.page_end}`} · {source.applicable_to}</span></button>)}</div>:null}</article>)}
      {loading&&<div className="max-w-[92%] rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">Checking approved policy sections…</div>}
    </div><form onSubmit={submit} className="border-t border-slate-200 p-4"><label className="sr-only" htmlFor="policy-question">Ask a policy question</label><div className="flex gap-2"><textarea id="policy-question" rows={2} maxLength={1000} value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void ask(question);}}} placeholder="Ask a policy question…" className="min-h-12 flex-1 resize-none rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-teal-500"/><button disabled={loading||question.trim().length<2} className="rounded-xl bg-teal-700 px-5 text-sm font-semibold text-white disabled:opacity-50">Ask</button></div>{error&&<p role="alert" className="mt-2 text-sm text-rose-700">{error}</p>}<p className="mt-2 text-xs text-slate-500">Enter to send · Shift+Enter for a new line · Conversation stays in this browser tab only.</p></form></div>
      <aside className="space-y-3"><div className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-semibold text-slate-800">Try asking</h3><div className="mt-3 space-y-2">{prompts.map(prompt=><button key={prompt} onClick={()=>void ask(prompt)} className="block w-full rounded-lg border border-slate-200 p-3 text-left text-sm text-slate-700 hover:border-teal-400">{prompt}</button>)}</div></div><div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><b>Policy guidance, not a decision</b><p className="mt-1">For exceptions, personal HR matters, legal advice, or disciplinary decisions, contact an authorized manager.</p></div></aside></div>
  </section>;
}
