'use client';
import { FormEvent,useEffect,useState } from 'react';
import Link from 'next/link';
import { initialPolicyManifest } from '@/lib/policy-corpus';

type DocumentRow={id:string;title:string;version:string;document_type:string;applicable_to:string;effective_date:string|null;last_updated_on:string|null;status:string;page_count:number;is_current:boolean;policy_sections?:{count:number}[]};
export function PolicyAssistantManagement(){
  const [documents,setDocuments]=useState<DocumentRow[]>([]);const [loading,setLoading]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [preview,setPreview]=useState<any>(null);
  async function load(){const response=await fetch('/api/policy-assistant/documents',{cache:'no-store'});const data=await response.json();if(response.ok)setDocuments(data.documents||[]);else setError(data.error||'Unable to load policies.');}
  useEffect(()=>{let active=true;void fetch('/api/policy-assistant/documents',{cache:'no-store'}).then(response=>response.json().then(data=>({ok:response.ok,data}))).then(({ok,data})=>{if(!active)return;if(ok)setDocuments(data.documents||[]);else setError(data.error||'Unable to load policies.');});return()=>{active=false;};},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');setNotice('');const form=new FormData(event.currentTarget);try{const response=await fetch('/api/policy-assistant/documents',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setPreview(data.preview);setNotice('Draft extracted and saved. Review the extraction preview and publish when ready.');event.currentTarget.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:'Upload failed.');}finally{setLoading(false);}}
  async function change(id:string,action:'publish'|'archive'){setError('');const response=await fetch(`/api/policy-assistant/documents/${id}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const data=await response.json();if(!response.ok)setError(data.error||'Policy update failed.');else{setNotice(action==='publish'?'Policy published and eligible staff notified.':'Policy archived.');await load();}}
  return <section className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6"><div><p className="eyebrow">POLICY GOVERNANCE</p><h2 className="text-2xl font-bold">Manage Policy Assistant</h2><p className="mt-2 text-sm text-slate-600">Upload a private PDF, inspect the extraction, then publish it. Only one current version of a policy can be active.</p></div><Link href="/admin/policy-assistant" className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Open assistant</Link></header>
    {(notice||error)&&<p role="status" className={`rounded-xl p-3 text-sm ${error?'bg-rose-50 text-rose-800':'bg-emerald-50 text-emerald-800'}`}>{error||notice}</p>}
    <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><form onSubmit={submit} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-semibold">New policy draft</h3><p className="text-xs text-slate-500">Initial corpus: {initialPolicyManifest.map(item=>item.title).join(', ')}.</p><label className="block text-sm">PDF file<input required name="file" type="file" accept="application/pdf,.pdf" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"/></label><label className="block text-sm">Title<input required name="title" maxLength={180} className="mt-1 block w-full rounded-lg border border-slate-300 p-2"/></label><div className="grid grid-cols-2 gap-2"><label className="block text-sm">Version<input required name="version" placeholder="1.0" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"/></label><label className="block text-sm">Type<select name="document_type" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"><option value="employee_handbook">Employee handbook</option><option value="internship_policy">Internship policy</option><option value="hiring_policy">Hiring policy</option><option value="sop">SOP</option><option value="faq">FAQ</option></select></label></div><label className="block text-sm">Applicable to<input required name="applicable_to" placeholder="All employees" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"/></label><div className="grid grid-cols-2 gap-2"><label className="block text-sm">Effective date<input name="effective_date" type="date" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"/></label><label className="block text-sm">Last updated<input name="last_updated_on" type="date" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"/></label></div><label className="block text-sm">Visibility<select name="audience_type" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"><option value="employees">All employees</option><option value="all_authenticated">All authenticated users</option><option value="role">Specific role</option><option value="department">Department ID</option><option value="profile">Individual profile ID</option></select></label><label className="block text-sm">Visibility value (when specific)<input name="audience_value" className="mt-1 block w-full rounded-lg border border-slate-300 p-2"/></label><button disabled={loading} className="w-full rounded-lg bg-teal-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{loading?'Extracting PDF…':'Extract and save draft'}</button></form>
      <div className="space-y-4"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-4"><h3 className="font-semibold">Policy versions</h3></div><div className="divide-y divide-slate-100">{documents.length?documents.map(document=><article key={document.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><div className="flex items-center gap-2"><b>{document.title} v{document.version}</b><span className={`rounded-full px-2 py-1 text-xs font-semibold ${document.status==='published'?'bg-emerald-50 text-emerald-700':document.status==='archived'?'bg-slate-100 text-slate-600':'bg-amber-50 text-amber-700'}`}>{document.status}{document.is_current?' · current':''}</span></div><p className="mt-1 text-xs text-slate-500">{document.applicable_to} · {document.page_count} pages · {document.policy_sections?.[0]?.count||0} sections {document.effective_date?`· effective ${document.effective_date}`:''}</p></div><div className="flex gap-2">{document.status==='draft'&&<button onClick={()=>void change(document.id,'publish')} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Publish</button>}{document.status!=='archived'&&<button onClick={()=>void change(document.id,'archive')} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold">Archive</button>}</div></article>):<p className="p-8 text-center text-sm text-slate-500">No policy documents uploaded yet.</p>}</div></div>{preview&&<div className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-semibold">Latest extraction preview</h3><p className="mt-1 text-sm text-slate-500">{preview.pageCount} pages · {preview.characterCount.toLocaleString()} characters · {preview.sections.length} searchable sections</p><div className="mt-3 max-h-64 space-y-2 overflow-auto">{preview.sections.map((section:any,index:number)=><div className="rounded-lg bg-slate-50 p-3 text-sm" key={index}><b>{section.section_number?`${section.section_number} · `:''}{section.section_title}</b><p className="text-xs text-slate-500">Pages {section.page_start}–{section.page_end}</p></div>)}</div></div>}</div></div>
  </section>;
}
