'use client';
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { inr, FinanceStatus } from '@/components/finance-ui';
import { grantedPermissions } from '@/lib/granted-permissions';

const db:any=supabase;
const today=()=>new Date().toISOString().slice(0,10);
export function PsychologistSessionPayables(){const [rows,setRows]=useState<any[]>([]);const [accounts,setAccounts]=useState<any[]>([]);const [allowed,setAllowed]=useState(false);const [status,setStatus]=useState('');const [doctor,setDoctor]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const load=async()=>{if(!db)return;try{const permissions=await grantedPermissions(db,['psychologist_payments.view','psychologist_payments.settle','finance.manage']);setAllowed(permissions.has('psychologist_payments.view'));if(!permissions.has('psychologist_payments.view'))return;let q=db.from('psychologist_session_payables').select('*,psychologist:outsourced_doctors(doctor_name),appointment:doctor_appointments(start_at)').order('due_date');if(status)q=q.eq('status',status);if(doctor)q=q.eq('psychologist_id',doctor);const [payables,accountRows]=await Promise.all([q,db.from('finance_accounts').select('id,name').eq('is_active',true).order('name')]);if(payables.error)throw payables.error;setRows(payables.data||[]);setAccounts(accountRows.data||[])}catch(e:any){setError(e.message||'Unable to load psychologist payables.')}};
 useEffect(()=>{void load()},[status,doctor]);const doctors=useMemo(()=>Array.from(new Map(rows.map(x=>[x.psychologist_id,x.psychologist?.doctor_name||'Psychologist'])).entries()),[rows]);const due=rows.filter(x=>x.status==='payment_due');const overdue=due.filter(x=>x.due_date&&x.due_date<today());const paid=rows.filter(x=>x.status==='paid');const pending=due.reduce((n,x)=>n+Number(x.payable_amount),0);const settle=async(id:string)=>{const account=accounts[0]?.id;if(!account)return setError('No active finance account is available.');setBusy(id);setError('');try{const {error}=await db.rpc('settle_psychologist_session_payable',{target_payable:id,target_account:account,paid_on:today(),method:'bank_transfer',reference:null});if(error)throw error;await load()}catch(e:any){setError(e.message||'Unable to settle payable.')}finally{setBusy('')}};
 if(!allowed)return <section><h1 className="text-2xl font-bold">Psychologist payments</h1><p className="mt-3 text-rose-700">You do not have permission to view psychologist payment liabilities.</p></section>;
 return <section className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Psychologist session payments</h1><p className="text-slate-500">Eligible online-session liabilities only. Clinical notes are not shown here.</p></div></div>{error&&<p className="text-rose-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pending" value={inr(pending)}/><Metric label="Due soon" value={due.length-overdue.length}/><Metric label="Overdue" value={overdue.length}/><Metric label="Paid" value={paid.length}/></div><div className="card flex flex-wrap gap-2 p-3"><select className="input" aria-label="Payment status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['payment_due','scheduled','paid','on_hold','cancelled'].map(x=><option key={x}>{x}</option>)}</select><select className="input" aria-label="Psychologist" value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">All psychologists</option>{doctors.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><div className="card overflow-x-auto"><table className="min-w-[780px] w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Psychologist</th><th className="p-3 text-left">Session</th><th className="p-3 text-left">Submitted</th><th className="p-3 text-right">Payable</th><th className="p-3 text-left">Due</th><th className="p-3 text-left">Status</th><th className="p-3"/></tr></thead><tbody>{rows.map(x=>{const isOverdue=x.status==='payment_due'&&x.due_date<today();return <tr className="border-b" key={x.id}><td className="p-3">{x.psychologist?.doctor_name}</td><td className="p-3">{x.session_date}</td><td className="p-3">{String(x.session_record_submitted_at).slice(0,10)}</td><td className="p-3 text-right">{inr(x.payable_amount)}</td><td className="p-3">{x.due_date||'Manual'}</td><td className="p-3"><FinanceStatus value={isOverdue?'overdue':x.status}/></td><td className="p-3">{x.status==='payment_due'&&<button className="btn border" disabled={busy===x.id} onClick={()=>void settle(x.id)}>{busy===x.id?'Settling…':'Mark paid'}</button>}</td></tr>})}</tbody></table>{!rows.length&&<p className="p-6 text-slate-500">No psychologist session payables match these filters.</p>}</div></section>}
function Metric({label,value}:{label:string;value:string|number}){return <article className="card p-4"><p className="text-sm text-slate-500">{label}</p><b className="text-xl">{value}</b></article>}
