'use client';

import { useEffect, useMemo, useState } from 'react';
import { currentProfile } from '@/lib/auth';
import { adminRepository } from '@/lib/admin-repository';
import { EmployeeBanner, EmployeeLoading, EmployeeMetric, EmployeeMetricGrid, EmployeePageHeader, EmployeeSection, EmployeeStatusBadge } from '@/components/employee-ui';

const legacyRoleName = (code?: string) => ({ super_admin: 'Super Admin', chairman: 'Chairman', director: 'Director', general_manager: 'General Manager', staff: 'Staff' }[code || ''] || code || 'Staff');
const roleTone = (code?: string) => ({ super_admin: 'bg-violet-100 text-violet-800', chairman: 'bg-emerald-100 text-emerald-800', director: 'bg-blue-100 text-blue-800', general_manager: 'bg-amber-100 text-amber-800', staff: 'bg-slate-100 text-slate-700' }[code || ''] || 'bg-slate-100 text-slate-700');
const groups = ['admin', 'employees', 'attendance', 'leave', 'tasks', 'documents', 'announcements', 'notifications', 'chat', 'crm', 'finance', 'payroll', 'invoices', 'reports', 'roles', 'permissions', 'audit', 'settings'];

export default function AccessManagementPage() {
  const [profile, setProfile] = useState<any>(); const [catalogue, setCatalogue] = useState<any>(); const [loading, setLoading] = useState(true); const [roleCode, setRoleCode] = useState(''); const [employeeQuery, setEmployeeQuery] = useState(''); const [matches, setMatches] = useState<any[]>([]); const [target, setTarget] = useState<any>(); const [permissionId, setPermissionId] = useState(''); const [startsAt, setStartsAt] = useState(new Date().toISOString().slice(0, 16)); const [expiresAt, setExpiresAt] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const p = await currentProfile() as any; if (!p) throw Error('Please sign in.'); const data = await adminRepository.accessCatalogue(); setProfile(p); setCatalogue(data); setRoleCode(current => current || data.roles[0]?.code || 'super_admin'); setPermissionId(current => current || data.permissions[0]?.id || ''); setError(''); } catch (caught: any) { setError(caught.message || 'Unable to load access management.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  const selectedRole = catalogue?.roles?.find((role: any) => role.code === roleCode) || catalogue?.roles?.[0];
  const selectedRoleKey = catalogue?.rolePermissionMode === 'legacy' ? legacyRoleName(selectedRole?.code) : selectedRole?.id;
  const rolePermissionIds = useMemo(() => new Set((catalogue?.rolePermissions || []).filter((item: any) => item.role_key === selectedRoleKey).map((item: any) => item.permission_id)), [catalogue, selectedRoleKey]);
  const roleCounts = useMemo(() => Object.fromEntries((catalogue?.employees || []).reduce((rows: any[], employee: any) => { rows.push([employee.role, (rows.find(row => row[0] === employee.role)?.[1] || 0) + 1]); return rows.filter((row, index, all) => all.findIndex(item => item[0] === row[0]) === index); }, [])), [catalogue]);
  const activeGrants = (catalogue?.grants || []).filter((grant: any) => !grant.revoked_at && (!grant.expires_at || new Date(grant.expires_at) > new Date()));

  const search = async () => { try { setMatches(await adminRepository.searchActiveEmployees(employeeQuery)); } catch (caught: any) { setError(caught.message || 'Unable to search employees.'); } };
  const grant = async () => { try { if (!profile || !target || !permissionId) throw Error('Choose an active employee and a permission.'); setSaving(true); await adminRepository.grantPermission({ profile_id: target.id, permission_id: permissionId, granted_by: profile.id, starts_at: new Date(startsAt).toISOString(), expires_at: expiresAt ? new Date(expiresAt).toISOString() : null, reason }); setNotice(`Access granted to ${target.full_name}.`); setTarget(undefined); setReason(''); setMatches([]); await load(); } catch (caught: any) { setError(caught.message || 'Unable to grant access.'); } finally { setSaving(false); } };
  const revoke = async (grantId: string) => { try { setSaving(true); await adminRepository.revokePermission(grantId, profile.id); setNotice('Access revoked.'); await load(); } catch (caught: any) { setError(caught.message || 'Unable to revoke access.'); } finally { setSaving(false); } };

  if (loading) return <section><EmployeePageHeader title="Roles & Access" subtitle="Manage employee roles, permissions, and temporary access grants." /><EmployeeLoading cards={4} /></section>;
  if (!catalogue) return <section><EmployeePageHeader title="Roles & Access" subtitle="Manage employee roles, permissions, and temporary access grants." /><EmployeeBanner>{error || 'Access management could not be loaded.'}</EmployeeBanner><button className="btn btn-primary mt-4" onClick={() => void load()}>Try again</button></section>;

  return <section className="space-y-5">
    <EmployeePageHeader title="Roles & Access" subtitle="Manage employee roles, permissions, and temporary access grants." action={<div className="flex flex-wrap gap-2"><button className="btn border" onClick={() => document.getElementById('grant-access')?.scrollIntoView({ behavior: 'smooth' })}>+ Direct grant</button><button className="btn btn-primary" onClick={() => document.getElementById('audit-log')?.scrollIntoView({ behavior: 'smooth' })}>Audit log</button></div>} />
    {error && <EmployeeBanner>{error}</EmployeeBanner>}{notice && <EmployeeBanner tone="success">{notice}</EmployeeBanner>}

    <EmployeeMetricGrid columns={4}><EmployeeMetric label="Roles" value={catalogue.roles.length} /><EmployeeMetric label="Permissions" value={catalogue.permissions.length} /><EmployeeMetric label="Active employees" value={catalogue.employees.length} /><EmployeeMetric label="Active direct grants" value={activeGrants.length} tone="info" /></EmployeeMetricGrid>

    <EmployeeSection title="Role overview" description="Active employees by their assigned role. Super Admin access is an override and is not granted through role checkboxes."><div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5">{catalogue.roles.map((role: any) => <button key={role.code} onClick={() => document.getElementById('permission-matrix')?.scrollIntoView({ behavior: 'smooth' }) || setRoleCode(role.code)} className="rounded-lg border border-slate-200 bg-white p-3 text-left transition hover:border-teal-400 hover:bg-teal-50"><div className="flex items-center justify-between gap-2"><span className={`rounded-full px-2 py-1 text-xs font-bold ${roleTone(role.code)}`}>{role.name}</span><b className="text-lg">{roleCounts[role.code] || 0}</b></div><p className="mt-2 text-xs text-slate-500">Active user{(roleCounts[role.code] || 0) === 1 ? '' : 's'}</p></button>)}</div></EmployeeSection>

    <EmployeeSection title="Permission matrix" description="Review or update the permissions for a role. Changes apply to all active employees with that role."><div id="permission-matrix" className="p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{catalogue.roles.map((role: any) => <button key={role.code} className={`rounded-full px-3 py-1.5 text-sm font-bold ${selectedRole?.code === role.code ? 'bg-teal-700 text-white' : 'bg-slate-100 text-slate-700'}`} onClick={() => setRoleCode(role.code)}>{role.name}</button>)}</div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${roleTone(selectedRole?.code)}`}>{selectedRole?.name}</span></div><div className="grid gap-4 lg:grid-cols-3">{groups.map(group => { const permissions = catalogue.permissions.filter((permission: any) => permission.code.startsWith(`${group}.`)); if (!permissions.length) return null; return <div className="rounded-lg border border-slate-200" key={group}><h3 className="border-b border-slate-100 px-3 py-2 text-sm font-bold capitalize">{group.replace('_', ' ')}</h3><div className="space-y-1 p-2">{permissions.map((permission: any) => <label className="flex cursor-pointer items-start gap-2 rounded p-2 text-sm hover:bg-slate-50" key={permission.id}><input type="checkbox" className="mt-1" checked={selectedRole?.code === 'super_admin' || rolePermissionIds.has(permission.id)} disabled={selectedRole?.code === 'super_admin' || saving} onChange={async event => { try { setSaving(true); await adminRepository.setRolePermission(selectedRoleKey, permission.id, event.target.checked, catalogue.rolePermissionMode); setNotice(`${permission.code} ${event.target.checked ? 'enabled' : 'removed'} for ${selectedRole.name}.`); await load(); } catch (caught: any) { setError(caught.message || 'Unable to update permission.'); } finally { setSaving(false); } }} /><span><b>{permission.code.split('.').slice(1).join(' ') || permission.code}</b><small className="mt-0.5 block text-xs text-slate-500">{permission.description}</small></span></label>)}</div></div>; })}</div></div></EmployeeSection>

    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <EmployeeSection title="Direct access grants" description="Temporary or exceptional access for an active employee."><div className="overflow-x-auto"><table className="table min-w-[760px]"><thead><tr><th>Employee</th><th>Permission</th><th>Start</th><th>End</th><th>Status</th><th /></tr></thead><tbody>{catalogue.grants.map((grant: any) => { const expired = !grant.revoked_at && grant.expires_at && new Date(grant.expires_at) <= new Date(); const state = grant.revoked_at ? 'Revoked' : expired ? 'Expired' : 'Active'; return <tr key={grant.id}><td><b>{grant.profile?.full_name || 'Unknown employee'}</b><small className="block">{grant.profile?.email}</small></td><td><b>{grant.permission?.code}</b><small className="block">{grant.reason || 'No reason supplied'}</small></td><td>{new Date(grant.starts_at).toLocaleDateString()}</td><td>{grant.expires_at ? new Date(grant.expires_at).toLocaleDateString() : 'No expiry'}</td><td><EmployeeStatusBadge tone={state === 'Active' ? 'success' : 'default'}>{state}</EmployeeStatusBadge></td><td>{state === 'Active' && <button disabled={saving} className="btn border text-xs" onClick={() => void revoke(grant.id)}>Revoke</button>}</td></tr>; })}</tbody></table>{!catalogue.grants.length && <div className="p-8 text-center"><b>No direct grants yet.</b><p className="mt-1 text-sm text-slate-500">Grant temporary access to an employee when a role is not enough.</p><button className="btn btn-primary mt-3" onClick={() => document.getElementById('grant-access')?.scrollIntoView({ behavior: 'smooth' })}>Grant access</button></div>}</div></EmployeeSection>
      <EmployeeSection title="Grant direct access" description="Search by employee name or work email."><div id="grant-access" className="space-y-3 p-4"><label className="block text-sm font-semibold">Employee search<div className="mt-1 flex gap-2"><input className="input" placeholder="Search employee…" value={employeeQuery} onChange={event => setEmployeeQuery(event.target.value)} /><button type="button" className="btn border" onClick={() => void search()}>Search</button></div></label>{matches.map(person => <button type="button" className={`w-full rounded border p-2 text-left text-sm ${target?.id === person.id ? 'border-teal-500 bg-teal-50' : 'border-slate-200'}`} onClick={() => setTarget(person)} key={person.id}><b>{person.full_name}</b><span className="ml-2 text-slate-500">{person.email}</span></button>)}{target && <p className="rounded bg-teal-50 p-2 text-sm text-teal-800">Selected: <b>{target.full_name}</b></p>}<label className="block text-sm font-semibold">Permission<select className="input mt-1" value={permissionId} onChange={event => setPermissionId(event.target.value)}>{catalogue.permissions.map((permission: any) => <option value={permission.id} key={permission.id}>{permission.code}</option>)}</select></label><label className="block text-sm font-semibold">Reason<input className="input mt-1" placeholder="Why is this access needed?" value={reason} onChange={event => setReason(event.target.value)} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Start date<input type="datetime-local" className="input mt-1" value={startsAt} onChange={event => setStartsAt(event.target.value)} /></label><label className="text-sm font-semibold">Expiry date <span className="font-normal text-slate-500">(optional)</span><input type="datetime-local" className="input mt-1" value={expiresAt} onChange={event => setExpiresAt(event.target.value)} /></label></div><button disabled={saving} className="btn btn-primary w-full" onClick={() => void grant()}>{saving ? 'Saving…' : 'Grant access'}</button></div></EmployeeSection>
    </div>

    <EmployeeSection title="Recent permission changes" description="Latest audit events retained by the platform."><div id="audit-log" className="divide-y divide-slate-100">{catalogue.audit.map((event: any) => <div className="flex gap-3 p-4" key={event.id}><span className="mt-1 h-2.5 w-2.5 rounded-full bg-teal-500" /><div><b className="text-sm">{event.action} {event.entity_type}</b><p className="mt-1 text-sm text-slate-600">{event.actor_id ? `Changed by ${event.actor_id}` : 'System change'}{event.entity_id ? ` · ${event.entity_id}` : ''}</p><small className="text-slate-500">{new Date(event.created_at).toLocaleString()}</small></div></div>)}{!catalogue.audit.length && <div className="p-8 text-center text-sm text-slate-500">No recent audit events are available to this account.</div>}</div></EmployeeSection>
  </section>;
}
