'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { adminRepository } from '@/lib/admin-repository';
import { FinanceEmpty, FinanceStatus, inr } from '@/components/finance-ui';
import { payrollLoadError } from '@/lib/payroll-query';

const month = () => new Date().toISOString().slice(0, 7);
const monthLabel = (value: string) => new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}T00:00:00Z`));

export default function PayrollPage() {
  const [runs, setRuns] = useState<any[]>([]);
  const [settings, setSettings] = useState<any[]>([]);
  const [selected, setSelected] = useState(month());
  const [periodFilter, setPeriodFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [paymentFilter, setPaymentFilter] = useState('');
  const [canManage, setCanManage] = useState(false);
  const [notice, setNotice] = useState<{ kind: 'error' | 'success'; text: string } | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const load = async () => { try { setLoading(true); setNotice(null); const [loadedRuns, loadedSettings, manage] = await Promise.all([adminRepository.payrollRuns(), adminRepository.salarySettings(), adminRepository.hasPermission('payroll.manage')]); setRuns(loadedRuns); setSettings(loadedSettings); setCanManage(manage); } catch { setNotice({ kind: 'error', text: payrollLoadError }); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []);
  const existingRun = runs.find(run => run.period_start?.startsWith(selected));
  const create = async () => { if (existingRun) { setNotice({ kind: 'error', text: `A payroll run already exists for ${selected}. Open the existing run instead.` }); return; } const [year, nextMonth] = selected.split('-').map(Number); const periodEnd = new Date(Date.UTC(year, nextMonth, 0)).toISOString().slice(0, 10); setBusy(true); try { const run = await adminRepository.createPayrollRun({ period_start: `${selected}-01`, period_end: periodEnd }, []); window.location.href = `/admin/finance/payroll/${run.id}`; } catch (caught: any) { const message = String(caught?.message || ''); setNotice({ kind: 'error', text: /duplicate|already exists|unique/i.test(message) ? `A payroll run already exists for ${selected}. Open the existing run instead.` : message || 'Payroll run could not be created.' }); } finally { setBusy(false); } };
  const shownRuns = useMemo(() => runs.filter(run => (!periodFilter || run.period_start.startsWith(periodFilter)) && (!statusFilter || run.status === statusFilter) && (!paymentFilter || (paymentFilter === 'paid' ? (run.payroll_entries || []).every((entry: any) => entry.payment_status === 'paid') : (run.payroll_entries || []).some((entry: any) => entry.payment_status !== 'paid')))), [runs, periodFilter, statusFilter, paymentFilter]);
  const allEntries = useMemo(() => shownRuns.flatMap(run => run.payroll_entries || []), [shownRuns]);
  const totals = useMemo(() => ({ employees: new Set(allEntries.map(entry => entry.profile_id)).size, gross: allEntries.reduce((sum, entry) => sum + Number(entry.gross_earnings), 0), deductions: allEntries.reduce((sum, entry) => sum + Number(entry.deductions) + Number(entry.other_deductions), 0), net: allEntries.reduce((sum, entry) => sum + Number(entry.net_payable), 0), paid: allEntries.filter(entry => entry.payment_status === 'paid').reduce((sum, entry) => sum + Number(entry.net_payable), 0), pending: allEntries.filter(entry => entry.payment_status !== 'paid').reduce((sum, entry) => sum + Number(entry.net_payable), 0) }), [allEntries]);
  return <section className="mx-auto max-w-[1320px] space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Employee payroll</p><h1 className="text-2xl font-bold">Payroll management</h1><p className="mt-1 text-sm text-slate-600">Prepare monthly employee salary snapshots, approve them, and track atomic Finance payments.</p></div>{canManage && <Link className="btn border" href="/admin/finance/payroll/settings">Salary settings</Link>}</div>
    {notice && <p className={`rounded-xl border px-4 py-3 text-sm ${notice.kind === 'error' ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-teal-200 bg-teal-50 text-teal-900'}`}>{notice.text}</p>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[['Employees', String(totals.employees)], ['Gross payroll', inr(totals.gross)], ['Deductions', inr(totals.deductions)], ['Net payroll', inr(totals.net)], ['Paid', inr(totals.paid)], ['Pending', inr(totals.pending)]].map(([label, value]) => <div className="card p-4" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>)}</div>
    {canManage && <div className="card flex flex-wrap items-end justify-between gap-4 p-4"><div><h2 className="font-bold">Start a payroll run</h2><p className="mt-1 text-sm text-slate-500">The database snapshots active employees with effective salary settings.</p></div><div className="flex flex-wrap items-end gap-2"><label className="block text-sm font-semibold">Payroll month<input required className="input mt-1" type="month" value={selected} onChange={event => setSelected(event.target.value)} /></label><button disabled={busy || loading || !settings.length} className="btn btn-primary" onClick={() => void create()}>{busy ? 'Generating…' : 'Create payroll run'}</button></div></div>}
    <div className="card grid gap-3 p-4 sm:grid-cols-3"><label className="text-sm font-semibold">Period<input className="input mt-1" type="month" value={periodFilter} onChange={event => setPeriodFilter(event.target.value)} /></label><label className="text-sm font-semibold">Run status<select className="input mt-1" value={statusFilter} onChange={event => setStatusFilter(event.target.value)}><option value="">All statuses</option>{['draft', 'approved', 'paid'].map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-semibold">Payment<select className="input mt-1" value={paymentFilter} onChange={event => setPaymentFilter(event.target.value)}><option value="">Paid and pending</option><option value="paid">Fully paid</option><option value="pending">Has pending</option></select></label></div>
    <div className="space-y-3 md:hidden">{shownRuns.map(run => <RunCard key={run.id} run={run} />)}</div>
    <div className="card hidden overflow-x-auto md:block"><table className="min-w-[820px] w-full text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Payroll period', 'Status', 'Employees', 'Gross', 'Deductions', 'Net payroll', 'Payment', 'Actions'].map(label => <th className="px-4 py-3 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-6">Loading payroll…</td></tr> : shownRuns.map(run => <RunRow key={run.id} run={run} />)}</tbody></table>{!loading && !shownRuns.length && <FinanceEmpty>No payroll runs match these filters.</FinanceEmpty>}</div>
  </section>;
}

function runSummary(run: any) { const entries = run.payroll_entries || []; return { entries, gross: entries.reduce((sum: number, entry: any) => sum + Number(entry.gross_earnings), 0), deductions: entries.reduce((sum: number, entry: any) => sum + Number(entry.deductions) + Number(entry.other_deductions), 0), net: entries.reduce((sum: number, entry: any) => sum + Number(entry.net_payable), 0), paid: entries.filter((entry: any) => entry.payment_status === 'paid').length }; }
function RunRow({ run }: any) { const summary = runSummary(run); return <tr className="border-t"><td className="px-4 py-3 font-medium">{monthLabel(run.period_start)}<br /><span className="text-xs text-slate-500">{run.period_start} – {run.period_end}</span></td><td className="px-4 py-3"><FinanceStatus value={run.status} /></td><td className="px-4 py-3">{summary.entries.length}</td><td className="px-4 py-3">{inr(summary.gross)}</td><td className="px-4 py-3">{inr(summary.deductions)}</td><td className="px-4 py-3 font-bold">{inr(summary.net)}</td><td className="px-4 py-3">{summary.paid}/{summary.entries.length} paid</td><td className="px-4 py-3"><Link className="font-medium text-teal-700 underline" href={`/admin/finance/payroll/${run.id}`}>Open run</Link></td></tr>; }
function RunCard({ run }: any) { const summary = runSummary(run); return <article className="card p-4"><div className="flex justify-between gap-3"><div><b>{monthLabel(run.period_start)}</b><p className="text-xs text-slate-500">{summary.entries.length} employees</p></div><FinanceStatus value={run.status} /></div><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-slate-500">Gross</dt><dd>{inr(summary.gross)}</dd></div><div><dt className="text-slate-500">Deductions</dt><dd>{inr(summary.deductions)}</dd></div><div><dt className="text-slate-500">Net</dt><dd className="font-bold">{inr(summary.net)}</dd></div></dl><Link className="btn border mt-4 w-full" href={`/admin/finance/payroll/${run.id}`}>Open run · {summary.paid}/{summary.entries.length} paid</Link></article>; }
