import { createClient } from '@supabase/supabase-js';
import { createServerClient } from '@supabase/ssr';
import { randomUUID } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import assert from 'node:assert/strict';
import * as provisioning from '../src/lib/clinician-provisioning';
import * as scheduling from '../src/lib/doctor-scheduling-rules';
const generateSlots = (scheduling as any).generateAvailableSlots || (scheduling as any).default?.generateAvailableSlots;
const provision = (provisioning as any).provisionExternalClinician || (provisioning as any).default?.provisionExternalClinician;
process.loadEnvFile('../.env.release-gate.local');
const url = process.env.BSMILE_QA_SUPABASE_URL!;
if (new URL(url).hostname !== 'enylrvmjgbntkrgpqsfe.supabase.co' || process.env.BSMILE_QA_PROJECT_REF !== 'enylrvmjgbntkrgpqsfe') throw Error('Approved QA project required.');
const options = { auth: { persistSession: false, autoRefreshToken: false } };
const svc = createClient(url, process.env.BSMILE_QA_SUPABASE_SERVICE_ROLE_KEY!, options);
const dir = 'release-evidence/online-psychologists/phase2';
const f = JSON.parse(readFileSync(`${dir}/qa-fixtures.local.json`, 'utf8'));
const persist = () => writeFileSync(`${dir}/qa-fixtures.local.json`, JSON.stringify(f, null, 2));
const ok = (r: any) => { if(r.error) throw Error(r.error.message); return r.data; };
const deny = (r: any) => assert.ok(r.error || !r.data || (Array.isArray(r.data) && !r.data.length), 'Unexpected access');
async function login(identity: any) { const db = createClient(url, process.env.BSMILE_QA_SUPABASE_ANON_KEY!, options); ok(await db.auth.signInWithPassword({email:identity.email,password:identity.password||f.password})); return db; }
const a = await login(f.external.a), b = await login(f.external.b), manager = await login(f.users.faiz), normal = await login(f.users.normal), sales = await login(f.users.sales), internal = await login(f.users.psychologist), director = await login(f.users.director);
const results: any[] = [];
async function probe(name: string, run: () => Promise<void>) { try { await run(); results.push({name,status:'PASS'}); } catch(e:any) {results.push({name,status:'FAIL',error:e.message});} writeFileSync(`${dir}/boundary-probes.json`,JSON.stringify(results,null,2)); }
async function cookies(identity:any) { const jar = new Map<string,string>(); const db=createServerClient(url,process.env.BSMILE_QA_SUPABASE_ANON_KEY!,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:items=>items.forEach(({name,value})=>jar.set(name,value))}}); ok(await db.auth.signInWithPassword({email:identity.email,password:identity.password||f.password})); return [...jar].map(([key,value])=>`${key}=${value}`).join('; '); }
const cookieA=await cookies(f.external.a),cookieB=await cookies(f.external.b),cookieSales=await cookies(f.users.sales);
async function request(path:string,cookie:string,body?:any) {return fetch(`http://127.0.0.1:3033${path}`,{method:'POST',headers:{cookie,...(body && !(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined,redirect:'manual'});}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF1sAAAAASUVORK5CYII=','base64');
writeFileSync(`${dir}/qa-pixel.png`,png);
await probe('provisioning validates missing email and unauthorized manager',async()=>{
 await assert.rejects(()=>provision(manager,svc,{doctorId:f.doctors.placeholder,email:'',requestId:randomUUID(),fields:{full_name:'QA'}},process.env.EMPLOYEE_INITIAL_PASSWORD),/valid login email/);
 await assert.rejects(()=>provision(normal,svc,{doctorId:f.doctors.placeholder,email:`qa-denied-${f.run}@example.test`,requestId:randomUUID(),fields:{full_name:'QA'}},process.env.EMPLOYEE_INITIAL_PASSWORD));
 const doctor=ok(await svc.from('outsourced_doctors').select('profile_id').eq('id',f.doctors.placeholder).single());assert.equal(doctor.profile_id,null);
});
await probe('confirmed Auth and single canonical identity',async()=>{for(const key of ['a','b']) {const user=ok(await svc.auth.admin.getUserById(f.external[key].id)).user;assert.ok(user.email_confirmed_at);const doctor=ok(await svc.from('outsourced_doctors').select('id,profile_id').eq('id',f.doctors[key]).single());assert.equal(doctor.profile_id,user.id);assert.equal(doctor.id,f.doctors[key]);}});
await probe('fresh external onboarding blocks workspace and routing',async()=>{
 if(!f.external.c){const doctor=ok(await svc.from('outsourced_doctors').insert({doctor_name:`QA P2 ${f.run} onboarding`,qualification:'QA',specialization:'QA',phone:'Not provided',clinician_type:'outsourced',status:'active',created_by:f.users.faiz.id}).select('id').single());f.doctors.c=doctor.id;f.external.c={email:`clinician-phase2-${f.run}-onboarding@example.test`,requestId:randomUUID(),fields:{full_name:`QA P2 ${f.run} onboarding`},password:process.env.EMPLOYEE_INITIAL_PASSWORD};persist();}
 const linked=await provision(manager,svc,{doctorId:f.doctors.c,email:f.external.c.email,requestId:f.external.c.requestId,fields:f.external.c.fields},process.env.EMPLOYEE_INITIAL_PASSWORD);f.external.c.id=linked.profileId;persist();const c=await login(f.external.c);assert.equal(ok(await c.rpc('has_permission',{permission_code:'clinician.workspace'})),false);deny(await c.rpc('clinician_schedule'));
 const cookie=await cookies(f.external.c);const res=await fetch('http://127.0.0.1:3033/clinician/schedule',{headers:{cookie},redirect:'manual'});assert.ok(res.headers.get('location')?.includes('/onboarding/password'));assert.equal(ok(await svc.from('profiles').select('onboarding_required').eq('id',linked.profileId).single()).onboarding_required,true);
});
await probe('explicit client assignment and expiry',async()=>{const row=ok(await svc.from('patient_access_assignments').insert({patient_id:f.patients.b.id,profile_id:f.external.a.id,assigned_by:f.users.faiz.id,assignment_type:'care_team'}).select('id').single());try {assert.equal(ok(await a.rpc('external_patient_access',{target_patient:f.patients.b.id})),true);assert.equal(ok(await a.rpc('clinician_clients',{target_slug:f.patients.b.slug})).length,1);ok(await svc.from('patient_access_assignments').update({ends_at:new Date(Date.now()-1000).toISOString()}).eq('id',row.id));assert.equal(ok(await a.rpc('external_patient_access',{target_patient:f.patients.b.id})),false);}finally{ok(await svc.from('patient_access_assignments').delete().eq('id',row.id));}});
await probe('deleted client removed across projections',async()=>{ok(await svc.from('patients').update({deleted_at:new Date().toISOString()}).eq('id',f.patients.a.id));try{assert.equal(ok(await a.rpc('external_patient_access',{target_patient:f.patients.a.id})),false);assert.deepEqual(ok(await a.rpc('clinician_clients',{target_slug:f.patients.a.slug})),[]);deny(await a.rpc('clinician_sessions',{target_patient:f.patients.a.id}));}finally{ok(await svc.from('patients').update({deleted_at:null}).eq('id',f.patients.a.id));}});
await probe('employee code audit records actor and before after',async()=>{const before=ok(await svc.from('profiles').select('employee_code').eq('id',f.users.normal.id).single()).employee_code;const code=`AUDIT-${f.run}-${randomUUID().slice(0,4)}`;ok(await manager.rpc('edit_employee_identity',{target_profile:f.users.normal.id,patch:{employee_code:code}}));const logs=ok(await svc.from('employee_activity_logs').select('*').eq('profile_id',f.users.normal.id).order('created_at',{ascending:false}).limit(10));assert.ok(logs.some((r:any)=>r.actor_id===f.users.faiz.id&&JSON.stringify(r).includes(code)&&JSON.stringify(r).includes(before)));});
await probe('manager blocked periods and external denial',async()=>{const block=ok(await manager.from('doctor_blocked_periods').insert({doctor_id:f.doctors.a,blocked_date:'2027-01-03',reason:'QA manager block',created_by:f.users.faiz.id}).select('id').single());try{deny(await a.from('doctor_blocked_periods').delete().eq('id',block.id).select());assert.ok(ok(await a.rpc('clinician_schedule')).blocked_periods.some((r:any)=>r.blocked_date==='2027-01-03'));}finally{ok(await manager.from('doctor_blocked_periods').delete().eq('id',block.id));}});
await probe('internal staff and intern clinician self availability preserved',async()=>{
 if(!f.doctors.internal){const existing=ok(await svc.from('outsourced_doctors').select('id').eq('profile_id',f.users.psychologist.id).maybeSingle());f.doctors.internal=existing?.id || ok(await svc.from('outsourced_doctors').insert({doctor_name:`QA P2 ${f.run} internal`,qualification:'QA',specialization:'QA',phone:'Not provided',clinician_type:'staff_psychologist',profile_id:f.users.psychologist.id,self_service_enabled:true,status:'active',created_by:f.users.faiz.id}).select('id').single()).id;persist();}
 for(const status of ['active','intern']){ok(await director.from('profiles').update({status}).eq('id',f.users.psychologist.id));try{assert.equal(ok(await internal.rpc('current_clinician_id')),f.doctors.internal);ok(await internal.rpc('replace_clinician_availability',{target_doctor:f.doctors.internal,ranges:[{day_of_week:2,start_time:'10:00',end_time:'12:00'}]}));}finally{ok(await director.from('profiles').update({status:'active'}).eq('id',f.users.psychologist.id));}}
});
await probe('patient document upload metadata storage and finalization',async()=>{
 const form=new FormData();form.set('file',new Blob([png],{type:'image/png'}),'qa-clinical.png');form.set('documentName','QA permitted clinical upload');form.set('category','Session Records');form.set('visibility','clinical_team');const response=await request(`/api/patients/${f.patients.a.id}/documents/upload`,cookieA,form);const body=await response.json();assert.equal(response.status,201,JSON.stringify(body));f.document=body.id;persist();const doc=ok(await a.from('patient_documents').select('*').eq('id',body.id).single());assert.ok(doc.storage_key.startsWith(`patients/${f.patients.a.id}/documents/`));assert.ok(doc.checksum);f.documentPath=doc.storage_key;persist();
});
await probe('clinical signed download works and unassigned routes denied',async()=>{
 assert.ok(f.document);const own=await request(`/api/patients/${f.patients.a.id}/documents/${f.document}/signed-url`,cookieA);const body=await own.json();assert.equal(own.status,200,JSON.stringify(body));assert.equal(body.expiresIn,120);assert.equal((await fetch(body.url)).status,200);
 const other=await request(`/api/patients/${f.patients.a.id}/documents/${f.document}/signed-url`,cookieB);assert.equal(other.status,404);deny(await b.storage.from('patient-documents').createSignedUrl(f.documentPath,120));deny(await b.from('patient_documents').select('*').eq('id',f.document));
});
await probe('restricted documents and Sales clinical content denied',async()=>{
 assert.ok(f.document);for(const patch of [{visibility:'management_only'},{category:'Identity Documents'},{archived_at:new Date().toISOString()}]){ok(await svc.from('patient_documents').update(patch).eq('id',f.document));try{deny(await a.from('patient_documents').select('id').eq('id',f.document));assert.equal((await request(`/api/patients/${f.patients.a.id}/documents/${f.document}/signed-url`,cookieA)).status,404);}finally{ok(await svc.from('patient_documents').update({visibility:'clinical_team',category:'Session Records',archived_at:null}).eq('id',f.document));}}
 deny(await sales.from('patient_documents').select('*').eq('id',f.document));assert.equal((await request(`/api/patients/${f.patients.a.id}/documents/${f.document}/signed-url`,cookieSales)).status,404);
});
await probe('upload finalization and direct object abuse denied',async()=>{
 assert.ok(f.document);deny(await a.from('patient_documents').update({patient_id:f.patients.b.id}).eq('id',f.document).select());deny(await a.from('patient_documents').update({storage_key:`patients/${f.patients.b.id}/documents/${f.document}/v1/file.png`}).eq('id',f.document).select());deny(await a.storage.from('patient-documents').upload(`patients/${f.patients.b.id}/documents/${randomUUID()}/v1/file.png`,png,{contentType:'image/png'}));
 const form=new FormData();form.set('file',new Blob([png],{type:'image/png'}),'qa-denied.png');form.set('documentName','Denied');form.set('category','Session Records');assert.equal((await request(`/api/patients/${f.patients.b.id}/documents/upload`,cookieA,form)).status,404);
});
await probe('own and scoped manager private photo and hijack denial',async()=>{
 const path=`${f.external.a.id}/${randomUUID()}.png`;ok(await a.storage.from('profile-photos').upload(path,png,{contentType:'image/png'}));ok(await a.rpc('save_clinician_profile',{target_doctor:f.doctors.a,patch:{avatar_url:path}}));assert.ok(ok(await a.storage.from('profile-photos').createSignedUrl(path,300)).signedUrl);f.photoPath=path;persist();deny(await b.from('profiles').update({avatar_url:path}).eq('id',f.external.b.id).select());deny(await b.rpc('save_clinician_profile',{target_doctor:f.doctors.b,patch:{avatar_url:path}}));
 const managerPath=`${f.external.a.id}/${randomUUID()}.png`;ok(await manager.storage.from('profile-photos').upload(managerPath,png,{contentType:'image/png'}));ok(await manager.rpc('save_clinician_profile',{target_doctor:f.doctors.a,patch:{avatar_url:managerPath}}));
});
await probe('direct chat search and placeholder exclusion',async()=>{const people=ok(await manager.rpc('chat_recipient_search',{search_text:`QA P2 ${f.run}`}));assert.ok(people.some((p:any)=>p.id===f.external.a.id));assert.ok(people.some((p:any)=>p.id===f.external.b.id));assert.ok(!people.some((p:any)=>p.id===f.external.c?.id));assert.ok(!people.some((p:any)=>p.id===f.orphan.id));});
await probe('external internal direct messages attachment mentions receipts',async()=>{
 f.chatInternal=ok(await a.rpc('create_or_get_direct_chat',{other_profile:f.users.normal.id}));persist();const path=`${f.external.a.id}/${f.chatInternal}/${randomUUID()}-qa.png`;ok(await a.storage.from('chat-attachments').upload(path,png,{contentType:'image/png'}));const message=ok(await a.from('chat_messages').insert({conversation_id:f.chatInternal,sender_id:f.external.a.id,body:'QA direct clinician message',client_message_id:randomUUID(),message_type:'attachment',attachment_path:path,attachment_name:'qa.png',attachment_type:'image/png',attachment_size:png.length}).select('id').single());f.chatMessage=message.id;f.chatAttachment=path;persist();assert.equal(ok(await normal.from('chat_messages').select('id').eq('id',message.id)).length,1);assert.ok(ok(await normal.storage.from('chat-attachments').createSignedUrl(path,120)).signedUrl);
 ok(await a.rpc('sync_chat_message_mentions',{target_message:message.id,target_conversation:f.chatInternal,target_profiles:[f.users.normal.id]}));ok(await normal.rpc('mark_chat_conversation_delivered',{target_conversation:f.chatInternal,target_message:message.id}));ok(await normal.rpc('mark_chat_conversation_read',{target_conversation:f.chatInternal,target_message:message.id}));ok(await normal.from('chat_message_reactions').insert({message_id:message.id,profile_id:f.users.normal.id,emoji:'👍'}));
 deny(await b.from('chat_messages').select('id').eq('id',message.id));deny(await b.storage.from('chat-attachments').createSignedUrl(path,120));deny(await b.from('chat_message_reactions').insert({message_id:message.id,profile_id:f.external.b.id,emoji:'👍'}));deny(await b.rpc('mark_chat_conversation_read',{target_conversation:f.chatInternal,target_message:message.id}));deny(await a.rpc('sync_chat_message_mentions',{target_message:message.id,target_conversation:f.chatInternal,target_profiles:[f.external.b.id]}));
});
await probe('external external direct chat and no company groups',async()=>{f.chatExternal=ok(await a.rpc('create_or_get_direct_chat',{other_profile:f.external.b.id}));persist();ok(await b.from('chat_messages').insert({conversation_id:f.chatExternal,sender_id:f.external.b.id,body:'QA external direct reply',client_message_id:randomUUID()}));assert.equal(ok(await a.rpc('ensure_my_all_employees_chat')),null);deny(await a.rpc('create_group_chat',{chat_title:'Denied QA group',chat_description:'',chat_type:'general',member_ids:[f.users.normal.id]}));const members=ok(await svc.from('chat_members').select('conversation_id,chat_conversations(conversation_type,is_system_group)').eq('profile_id',f.external.a.id));assert.ok(members.every((r:any)=>r.chat_conversations.conversation_type==='personal'&&!r.chat_conversations.is_system_group));});
await probe('inactive clinician omitted and shared member access revoked',async()=>{ok(await svc.from('profiles').update({status:'inactive'}).eq('id',f.external.a.id));try{deny(await a.rpc('is_chat_member',{conversation:f.chatInternal}));deny(await a.from('chat_messages').select('id').eq('id',f.chatMessage));deny(await a.storage.from('chat-attachments').createSignedUrl(f.chatAttachment,120));assert.ok(!ok(await manager.rpc('chat_recipient_search',{search_text:`QA P2 ${f.run}`})).some((r:any)=>r.id===f.external.a.id));}finally{ok(await svc.from('profiles').update({status:'active'}).eq('id',f.external.a.id));}});
await probe('revoked chat permission denies messages reactions receipts storage',async()=>{const perm=ok(await svc.from('permissions').select('id').eq('code','chat.use').single());const grants=ok(await svc.from('user_permission_grants').select('id,revoked_at').eq('profile_id',f.external.a.id).eq('permission_id',perm.id).is('revoked_at',null));for(const g of grants)ok(await svc.from('user_permission_grants').update({revoked_at:new Date().toISOString()}).eq('id',g.id));try{assert.equal(ok(await a.rpc('is_chat_member',{conversation:f.chatInternal})),false);deny(await a.from('chat_messages').insert({conversation_id:f.chatInternal,sender_id:f.external.a.id,body:'Denied revoked',client_message_id:randomUUID()}));deny(await a.from('chat_message_reactions').insert({message_id:f.chatMessage,profile_id:f.external.a.id,emoji:'✅'}));deny(await a.rpc('mark_chat_conversation_read',{target_conversation:f.chatInternal,target_message:f.chatMessage}));deny(await a.storage.from('chat-attachments').createSignedUrl(f.chatAttachment,120));}finally{for(const g of grants)ok(await svc.from('user_permission_grants').update({revoked_at:null}).eq('id',g.id));}});
await probe('reject notification targets authorized internal scheduling',async()=>{const rows=ok(await svc.from('notifications').select('*').eq('entity_id',f.appointments.b));assert.ok(rows.some((r:any)=>JSON.stringify(r).includes('clinician_appointment_rejected')&&JSON.stringify(r).includes(f.users.faiz.id)));});
await probe('rejection preserves finance and occupied slot generation',async()=>{
 const tables=['psychologist_session_payables','psychologist_payout_settings','finance_invoices','finance_invoice_payments'];
 const snapshot=async()=>Object.fromEntries(await Promise.all(tables.map(async table=>[table,ok(await director.from(table).select('*').order('id'))])));
 const financeBefore=await snapshot(),before=ok(await svc.from('doctor_appointments').select('*').eq('id',f.appointments.b).single());
 ok(await b.rpc('respond_to_clinician_appointment',{target_appointment:f.appointments.b,decision:'rejected',request_id:randomUUID(),rejection_reason:'QA finance and occupancy verification'}));
 const after=ok(await svc.from('doctor_appointments').select('*').eq('id',f.appointments.b).single());assert.deepEqual(after,before);assert.deepEqual(await snapshot(),financeBefore);
 const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(before.start_at));
 const args={date,durationMinutes:30,cadenceMinutes:30,availability:[{day_of_week:new Date(`${date}T00:00:00Z`).getUTCDay(),start_time:'14:00',end_time:'17:00'}],blockedPeriods:[],now:new Date('2020-01-01')};
 assert.ok(generateSlots({...args,appointments:[]}).some((slot:any)=>slot.startAt===before.start_at.replace('+00:00','Z').replace('Z','.000Z'))||generateSlots({...args,appointments:[]}).some((slot:any)=>new Date(slot.startAt).getTime()===new Date(before.start_at).getTime()));
 assert.ok(!generateSlots({...args,appointments:[after]}).some((slot:any)=>new Date(slot.startAt).getTime()===new Date(after.start_at).getTime()));
 writeFileSync(`${dir}/reject-finance-and-slot.json`,JSON.stringify({appointmentUnchanged:true,financeTablesUnchanged:tables,rejectedSlotAvailable:false},null,2));
});
const failures=results.filter(r=>r.status==='FAIL');console.log(`Boundary probes: ${results.length-failures.length} passed, ${failures.length} failed.`);for(const failure of failures)console.log(`${failure.name}: ${failure.error}`);if(failures.length)process.exitCode=1;
