import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
import * as provisioning from '../src/lib/clinician-provisioning';
const provisionExternalClinician = (provisioning as any).provisionExternalClinician || (provisioning as any).default?.provisionExternalClinician;

// This harness is intentionally incapable of using production configuration.
process.loadEnvFile('../.env.release-gate.local');
const url = process.env.BSMILE_QA_SUPABASE_URL!;
if (new URL(url).hostname !== 'enylrvmjgbntkrgpqsfe.supabase.co' || process.env.BSMILE_QA_PROJECT_REF !== 'enylrvmjgbntkrgpqsfe') throw new Error('This harness requires the approved isolated QA project.');
const service = createClient(url, process.env.BSMILE_QA_SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } });
const directory = 'release-evidence/online-psychologists/phase2'; mkdirSync(directory, { recursive: true });
const path = `${directory}/qa-fixtures.local.json`;
const f: any = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : { run: randomUUID().slice(0, 8), password: randomUUID() + randomUUID(), users: {}, doctors: {}, external: {}, patients: {}, appointments: {}, sessions: {} };
function persist() { writeFileSync(path, JSON.stringify(f, null, 2)); }
function checked(result: any) { if (result.error) throw new Error(result.error.message); return result.data; }
async function login(identity: any) { const db = createClient(url, process.env.BSMILE_QA_SUPABASE_ANON_KEY!, { auth: { persistSession: false, autoRefreshToken: false } }); checked(await db.auth.signInWithPassword({ email: identity.email, password: identity.password || f.password })); return db; }
async function grant(profile: string, codes: string[]) {
  const permissions = checked(await service.from('permissions').select('id,code').in('code', codes));
  assert.equal(permissions.length, codes.length, 'Permission catalogue is incomplete');
  const existing = checked(await service.from('user_permission_grants').select('permission_id').eq('profile_id', profile).is('revoked_at', null));
  for (const permission of permissions) if (!existing.some((row: any) => row.permission_id === permission.id)) checked(await service.from('user_permission_grants').insert({ profile_id: profile, permission_id: permission.id, granted_by: f.users.faiz.id, reason: `Disposable online-clinician QA ${f.run}`, expires_at: new Date(Date.now() + 7 * 86400000).toISOString() }));
}
async function seed() {
  for (const [key, role, designation] of [['faiz', 'general_manager', 'QA General Manager'], ['director', 'director', 'QA Director'], ['diya', 'staff', 'QA Assistant Manager'], ['normal', 'staff', 'QA Staff'], ['psychologist', 'psychologist', 'QA Internal psychologist'], ['sales', 'staff', 'QA Sales Coordinator']]) {
    const email = `clinician-phase2-${f.run}-${key}@example.test`;
    if (!f.users[key]) { const created = checked(await service.auth.admin.createUser({ email, password: f.password, email_confirm: true, app_metadata: { qa_task: 'online-clinicians-phase2', qa_run: f.run } })); f.users[key] = { id: created.user.id, email }; persist(); }
    checked(await service.from('profiles').upsert({ id: f.users[key].id, email, full_name: `QA P2 ${f.run} ${key}`, role, designation, is_employee: true, workforce_visible: true, status: 'active', login_enabled: true, onboarding_required: false, employee_code: key === 'normal' ? `P2-${f.run}-STAFF` : null }));
  }
  await grant(f.users.faiz.id, ['outsourced_clinicians.manage', 'employees.identity.edit', 'clinical_followups.view_operational', 'chat.use']);
  await grant(f.users.director.id, ['employees.identity.edit', 'chat.use']);
  await grant(f.users.diya.id, ['outsourced_clinicians.manage', 'employees.identity.view', 'employees.identity.edit', 'chat.use']);
  await grant(f.users.psychologist.id, ['outsourced_clinicians.manage', 'chat.use']);
  await grant(f.users.normal.id, ['chat.use']);
  await grant(f.users.sales.id, ['clinical_followups.view_operational', 'patients.view_identity', 'chat.use']);
  const manager = await login(f.users.faiz);
  for (const key of ['a', 'b', 'placeholder', 'orphan']) {
    if (!f.doctors[key]) { const row = checked(await service.from('outsourced_doctors').insert({ doctor_name: `QA P2 ${f.run} External ${key}`, qualification: 'QA qualification', specialization: 'QA specialty', phone: 'Not provided', clinician_type: 'outsourced', self_service_enabled: false, status: 'active', created_by: f.users.faiz.id }).select('id').single()); f.doctors[key] = row.id; persist(); }
  }
  if (!f.orphan) { const email = `clinician-phase2-${f.run}-unrelated@example.test`; const identity = checked(await service.auth.admin.createUser({ email, password: f.password, email_confirm: true, app_metadata: { qa_task: 'unrelated-auth-fixture', qa_run: f.run } })); f.orphan = { id: identity.user.id, email }; persist(); }
  for (const key of ['a', 'b']) {
    const email = `clinician-phase2-${f.run}-external-${key}@example.test`;
    if (!f.external[key]) { f.external[key] = { email, requestId: randomUUID(), fields: { full_name: `QA P2 ${f.run} External ${key}` } }; persist(); }
    const identity = await provisionExternalClinician(manager, service, { doctorId: f.doctors[key], email, requestId: f.external[key].requestId, fields: f.external[key].fields }, process.env.EMPLOYEE_INITIAL_PASSWORD);
    f.external[key].id = identity.profileId; persist();
  }
  console.log('Prepared six internal and two linked external QA identities. Passwords remain in ignored local evidence.');
}

const results: any[] = existsSync(`${directory}/api-probes.json`) ? JSON.parse(readFileSync(`${directory}/api-probes.json`,'utf8')) : [];
async function probe(name: string, action: () => Promise<void>) { try { await action(); const existing = results.findIndex(row => row.name === name); if(existing >= 0) results.splice(existing,1); results.push({ name, status: 'PASS' }); } catch (error: any) { const existing = results.findIndex(row => row.name === name); if(existing >= 0) results.splice(existing,1); results.push({ name, status: 'FAIL', error: error.message }); } writeFileSync(`${directory}/api-probes.json`, JSON.stringify(results, null, 2)); }
async function denied(result: any) { assert.ok(result.error || !result.data || (Array.isArray(result.data) && !result.data.length), 'Unexpected access or mutation'); }
async function qualify() {
  const manager = await login(f.users.faiz); const director = await login(f.users.director); const diya = await login(f.users.diya); const normal = await login(f.users.normal); const sales = await login(f.users.sales);
  for (const key of ['a', 'b']) {
    const identity = f.external[key];
    const profile = checked(await service.from('profiles').select('*').eq('id', identity.id).single());
    if (profile.onboarding_required) {
      identity.password = process.env.EMPLOYEE_INITIAL_PASSWORD; const initial = await login(identity);
      await probe(`onboarding ${key} workspace blocked`, async () => { await denied(await initial.rpc('clinician_schedule')); });
      identity.password = randomUUID() + randomUUID(); checked(await initial.auth.updateUser({ password: identity.password })); checked(await service.rpc('complete_employee_onboarding', { target_profile: identity.id })); persist();
    }
  }
  const a = await login(f.external.a); const b = await login(f.external.b);
  for (const key of ['a', 'b']) {
    if (!f.patients[key]) { const row = checked(await service.from('patients').insert({ full_name: `QA P2 ${f.run} Client ${key}`, patient_number: `P2-${f.run}-${key}`, phone: '0000000000', gender: 'female', preferred_language: 'English', status: 'active', is_demo: true, assigned_psychologist_id: f.external[key].id, created_by: f.users.faiz.id }).select('id,slug').single()); f.patients[key] = row; persist(); }
    if (!f.appointments[key]) { const start = new Date(Date.now() + (key === 'a' ? 3 : 4) * 86400000); start.setUTCHours(10, 0, 0, 0); const row = checked(await service.from('doctor_appointments').insert({ patient_id: f.patients[key].id, doctor_id: f.doctors[key], start_at: start.toISOString(), end_at: new Date(+start + 1800000).toISOString(), consultation_type: 'online', status: 'scheduled', remarks: 'QA scheduling remark, not a clinical note', created_by: f.users.faiz.id }).select('id').single()); f.appointments[key] = row.id; persist(); }
    if (!f.sessions[key]) { const row = checked(await service.from('patient_sessions').insert({ patient_id: f.patients[key].id, assigned_psychologist_id: f.external[key].id, appointment_at: new Date().toISOString(), session_type: 'Initial consultation', attendance_status: 'scheduled', created_by: f.users.faiz.id }).select('id').single()); f.sessions[key] = row.id; persist(); }
  }
  checked(await service.from('doctor_appointments').update({status:'scheduled'}).eq('id',f.appointments.a));
  for (const [name, actor] of [['Faiz', manager], ['Director', director], ['Diya', diya]] as const) await probe(`${name} employee code edit`, async () => { const code = `P2-${f.run}-${name}`; checked(await actor.rpc('edit_employee_identity', { target_profile: f.users.normal.id, patch: { employee_code: ` ${code} ` } })); const row = checked(await service.from('profiles').select('employee_code,id,email').eq('id', f.users.normal.id).single()); assert.equal(row.employee_code, code); assert.equal(row.id, f.users.normal.id); assert.equal(row.email, f.users.normal.email); });
  await probe('normal employee direct code update denied', async () => { await denied(await normal.from('profiles').update({ employee_code: 'BYPASS' }).eq('id', f.users.normal.id).select()); });
  await probe('Diya role and login API escalation denied', async () => { await denied(await diya.from('profiles').update({ role: 'super_admin' }).eq('id', f.users.diya.id).select()); await denied(await diya.rpc('edit_employee_identity', { target_profile: f.users.normal.id, patch: { role: 'super_admin' } })); });
  await probe('duplicate trimmed code denied', async () => { const existing = checked(await service.from('profiles').select('employee_code').eq('id', f.users.normal.id).single()); const result = await manager.rpc('edit_employee_identity', { target_profile: f.users.sales.id, patch: { employee_code: ` ${existing.employee_code} ` } }); assert.equal(result.error?.code, '23505'); });
  await probe('external classification and no code', async () => { const row = checked(await service.from('profiles').select('is_employee,employee_code,role,onboarding_required').eq('id', f.external.a.id).single()); assert.equal(row.is_employee, false); assert.equal(row.employee_code, null); assert.equal(row.role, 'staff'); assert.equal(row.onboarding_required, false); });
  await probe('provision replay preserves private password and IDs', async () => { const result = await provisionExternalClinician(manager, service, { doctorId: f.doctors.a, email: f.external.a.email, requestId: f.external.a.requestId, fields: f.external.a.fields }, undefined); assert.equal(result.profileId, f.external.a.id); await login(f.external.a); const doctor = checked(await service.from('outsourced_doctors').select('profile_id').eq('id', f.doctors.a).single()); assert.equal(doctor.profile_id, f.external.a.id); });
  await probe('unrelated Auth account remains unclaimed', async () => { await assert.rejects(async () => provisionExternalClinician(manager, service, { doctorId: f.doctors.orphan, email: f.orphan.email, requestId: checked(await service.from('clinician_provision_requests').select('request_id').eq('doctor_id',f.doctors.orphan).single()).request_id, fields: { full_name: 'QA unrelated ownership test' } }, process.env.EMPLOYEE_INITIAL_PASSWORD), /another Auth account/); const doctor = checked(await service.from('outsourced_doctors').select('profile_id').eq('id', f.doctors.orphan).single()); assert.equal(doctor.profile_id, null); });
  await probe('own client and other client scope', async () => { const clients = checked(await a.rpc('clinician_clients')); assert.ok(clients.some((row: any) => row.id === f.patients.a.id)); assert.ok(!clients.some((row: any) => row.id === f.patients.b.id)); assert.deepEqual(checked(await a.rpc('clinician_clients', { target_slug: f.patients.b.slug })), []); await denied(await a.from('patients').select('*').eq('id', f.patients.b.id)); });
  await probe('own schedule only and no finance projection', async () => { const schedule = checked(await a.rpc('clinician_schedule')); assert.ok(schedule.appointments.some((row: any) => row.id === f.appointments.a)); assert.ok(!schedule.appointments.some((row: any) => row.id === f.appointments.b)); assert.ok(!JSON.stringify(schedule).includes('psychologist_fee_snapshot')); });
  await probe('accept other appointment denied', async () => { await denied(await a.rpc('respond_to_clinician_appointment', { target_appointment: f.appointments.b, decision: 'accepted', request_id: randomUUID() })); });
  await probe('accept own appointment', async () => { const response = checked(await a.rpc('respond_to_clinician_appointment', { target_appointment: f.appointments.a, decision: 'accepted', request_id: randomUUID() })); assert.equal(response.appointment_status, 'confirmed'); });
  await probe('reject retains entire scheduling row and slot', async () => { const before = checked(await service.from('doctor_appointments').select('*').eq('id', f.appointments.b).single()); const response = checked(await b.rpc('respond_to_clinician_appointment', { target_appointment: f.appointments.b, decision: 'rejected', request_id: randomUUID(), rejection_reason: 'QA cannot attend; awaiting reassignment' })); assert.equal(response.response, 'rejected'); const after = checked(await service.from('doctor_appointments').select('*').eq('id', f.appointments.b).single()); assert.deepEqual(after, before); writeFileSync(`${directory}/reject-evidence.json`, JSON.stringify({ before, response, after }, null, 2)); });
  await probe('external reschedule and arbitrary insert denied', async () => { await denied(await a.from('doctor_appointments').update({ start_at: new Date().toISOString() }).eq('id', f.appointments.a).select()); await denied(await a.from('doctor_appointments').insert({ patient_id: f.patients.a.id, doctor_id: f.doctors.b, start_at: new Date().toISOString(), end_at: new Date(Date.now() + 1800000).toISOString(), consultation_type: 'online', status: 'scheduled', created_by: f.external.a.id }).select()); });
  await probe('external availability mutation denied', async () => { await denied(await a.rpc('replace_clinician_availability', { target_doctor: f.doctors.a, ranges: [] })); await denied(await a.from('doctor_blocked_periods').insert({ doctor_id: f.doctors.a, blocked_date: '2027-01-01', created_by: f.external.a.id }).select()); });
  await probe('approved manager availability allowed', async () => { checked(await manager.rpc('replace_clinician_availability', { target_doctor: f.doctors.a, ranges: [{ day_of_week: 1, start_time: '09:00', end_time: '17:00' }] })); const schedule = checked(await a.rpc('clinician_schedule')); assert.equal(schedule.availability.length, 1); });
  await probe('Director broad permission cannot mutate outsourced availability', async () => { await denied(await director.rpc('replace_clinician_availability', { target_doctor: f.doctors.a, ranges: [] })); await denied(await normal.rpc('replace_clinician_availability', { target_doctor: f.doctors.a, ranges: [] })); });
  await probe('own note creation and other author edit denial', async () => { f.note = checked(await a.rpc('save_clinician_note', { target_patient: f.patients.a.id, target_appointment: f.appointments.a, target_session: f.sessions.a, note_content: 'QA PRIVATE CLINICAL NOTE' })); persist(); await denied(await b.rpc('save_clinician_note', { target_patient: f.patients.a.id, target_appointment: f.appointments.a, target_note: f.note, target_session: f.sessions.a, note_content: 'Unauthorized' })); const appointment = checked(await service.from('doctor_appointments').select('remarks').eq('id', f.appointments.a).single()); assert.equal(appointment.remarks, 'QA scheduling remark, not a clinical note'); });
  await probe('own operational followup and unassigned denial', async () => { f.followup = checked(await a.rpc('save_clinician_followup', { target_patient: f.patients.a.id, target_appointment: f.appointments.a, target_session: f.sessions.a, follow_up_date: '2027-01-02', operational_remarks: 'QA call to arrange next visit' })); persist(); await denied(await a.rpc('save_clinician_followup', { target_patient: f.patients.b.id, target_appointment: f.appointments.b, follow_up_date: '2027-01-02', operational_remarks: 'Unauthorized' })); });
  await probe('admin and Sales minimal followup', async () => { for (const actor of [manager, sales]) { const rows = checked(await actor.rpc('operational_clinical_followups', { target_patient: f.patients.a.id })); assert.ok(rows.some((row: any) => row.id === f.followup)); assert.ok(!JSON.stringify(rows).includes('QA PRIVATE CLINICAL NOTE')); } await denied(await sales.from('patient_notes').select('*').eq('id', f.note)); });
  await probe('own professional/contact fields and manager edit', async () => { checked(await a.rpc('save_clinician_profile', { target_doctor: f.doctors.a, patch: { full_name: `QA P2 ${f.run} External a edited`, phone: '0000000001', qualification: 'QA updated qualification', specialization: 'QA updated specialty' } })); checked(await manager.rpc('save_clinician_profile', { target_doctor: f.doctors.a, patch: { professional_information: 'QA manager-reviewed professional information' } })); });
  await probe('external immutable identity and other clinician edit denied', async () => { for (const patch of [{ is_employee: true }, { role: 'psychologist' }, { employee_code: 'EXTERNAL' }]) await denied(await a.from('profiles').update(patch).eq('id', f.external.a.id).select()); await denied(await a.rpc('save_clinician_profile', { target_doctor: f.doctors.b, patch: { phone: 'bad' } })); await denied(await a.from('outsourced_doctors').update({ clinician_type: 'staff_psychologist' }).eq('id', f.doctors.a).select()); });
  await probe('external role bundle inheritance clamped', async () => { checked(await service.from('profiles').update({ role: 'psychologist' }).eq('id', f.external.a.id)); try { for (const permission_code of ['patients.view_all', 'finance.view', 'employees.view', 'attendance.view_self', 'leaves.request', 'crm.manage_all', 'appointments.update_status']) assert.equal(checked(await a.rpc('has_permission', { permission_code })), false, permission_code); for (const table of ['profiles', 'payroll_entries', 'attendance', 'leave_requests', 'leads', 'patients', 'doctor_appointments']) { const result = await a.from(table).select('id').limit(50); if (table === 'profiles') assert.deepEqual(checked(result).map((row: any) => row.id), [f.external.a.id]); else await denied(result); } } finally { checked(await service.from('profiles').update({ role: 'staff' }).eq('id', f.external.a.id)); } });
  const failed = results.filter(row => row.status === 'FAIL'); console.log(`QA probes: ${results.length - failed.length} passed, ${failed.length} failed.`); for (const row of failed) console.log(`${row.name}: ${row.error}`); if (failed.length) process.exitCode = 1;
}
if (process.argv[2] === 'seed') await seed(); else if (process.argv[2] === 'qualify') await qualify(); else throw new Error('Use seed or qualify.');
