create table if not exists public.designations (id uuid primary key default gen_random_uuid(), name text not null, department_id uuid references public.departments(id) on delete set null, created_at timestamptz not null default now(), unique(name,department_id));
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
-- Upgrade the earlier audit_logs table when it already exists without full change snapshots.
alter table public.audit_logs add column if not exists before_data jsonb;
alter table public.audit_logs add column if not exists after_data jsonb;

create or replace function public.can_manage_admin() returns boolean language sql stable security definer set search_path=public as $$ select public.current_role() in ('chairman','director') $$;
create or replace function public.audit_row() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.audit_logs(actor_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),lower(TG_OP),TG_TABLE_NAME,coalesce(new.id,old.id),case when TG_OP='INSERT' then null else to_jsonb(old) end,case when TG_OP='DELETE' then null else to_jsonb(new) end); return coalesce(new,old); end $$;
drop trigger if exists profiles_audit on public.profiles; create trigger profiles_audit after insert or update or delete on public.profiles for each row execute function public.audit_row();
drop trigger if exists departments_audit on public.departments; create trigger departments_audit after insert or update or delete on public.departments for each row execute function public.audit_row();
drop trigger if exists designations_audit on public.designations; create trigger designations_audit after insert or update or delete on public.designations for each row execute function public.audit_row();
drop trigger if exists roles_audit on public.roles; create trigger roles_audit after insert or update or delete on public.roles for each row execute function public.audit_row();

alter table public.departments enable row level security; alter table public.designations enable row level security; alter table public.roles enable row level security; alter table public.permissions enable row level security; alter table public.role_permissions enable row level security; alter table public.audit_logs enable row level security;
drop policy if exists "read departments" on public.departments; drop policy if exists "manage departments" on public.departments; drop policy if exists "read designations" on public.designations; drop policy if exists "manage designations" on public.designations; drop policy if exists "read roles" on public.roles; drop policy if exists "manage roles" on public.roles; drop policy if exists "read permissions" on public.permissions; drop policy if exists "manage permissions" on public.permissions; drop policy if exists "read role permissions" on public.role_permissions; drop policy if exists "manage role permissions" on public.role_permissions; drop policy if exists "read audit logs" on public.audit_logs;
create policy "read departments" on public.departments for select to authenticated using(true); create policy "manage departments" on public.departments for all to authenticated using(public.can_manage_admin()) with check(public.can_manage_admin());
create policy "read designations" on public.designations for select to authenticated using(true); create policy "manage designations" on public.designations for all to authenticated using(public.can_manage_admin()) with check(public.can_manage_admin());
create policy "read roles" on public.roles for select to authenticated using(true); create policy "manage roles" on public.roles for all to authenticated using(public.can_manage_admin()) with check(public.can_manage_admin());
create policy "read permissions" on public.permissions for select to authenticated using(true); create policy "manage permissions" on public.permissions for all to authenticated using(public.can_manage_admin()) with check(public.can_manage_admin());
create policy "read role permissions" on public.role_permissions for select to authenticated using(true); create policy "manage role permissions" on public.role_permissions for all to authenticated using(public.can_manage_admin()) with check(public.can_manage_admin());
create policy "read audit logs" on public.audit_logs for select to authenticated using(public.can_manage_admin());
