-- Simple company-document sharing and employee document-request workflow.
alter table public.documents add column if not exists file_name text, add column if not exists description text, add column if not exists mime_type text, add column if not exists file_size bigint check(file_size is null or file_size>=0), add column if not exists review_comment text, add column if not exists updated_at timestamptz not null default now();
create table if not exists public.document_shares (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete cascade, profile_id uuid references public.profiles(id) on delete cascade, shared_with_all boolean not null default false, created_at timestamptz not null default now(), check((shared_with_all and profile_id is null) or (not shared_with_all and profile_id is not null)), unique(document_id,profile_id));
create table if not exists public.document_requests (id uuid primary key default gen_random_uuid(), title text not null, description text, due_date date, profile_id uuid not null references public.profiles(id) on delete cascade, requested_by uuid references public.profiles(id) on delete set null, status text not null default 'requested' check(status in ('requested','submitted','approved','rejected')), admin_comment text, reviewer_id uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.document_requests add column if not exists due_date date, add column if not exists reviewer_id uuid references public.profiles(id) on delete set null, add column if not exists reviewed_at timestamptz;
create table if not exists public.document_submissions (id uuid primary key default gen_random_uuid(), request_id uuid not null unique references public.document_requests(id) on delete cascade, storage_path text not null, file_name text not null, mime_type text, file_size bigint check(file_size is null or file_size>=0), submitted_by uuid not null references public.profiles(id), submitted_at timestamptz not null default now());
alter table public.document_submissions add column if not exists mime_type text, add column if not exists file_size bigint check(file_size is null or file_size>=0);
create index if not exists document_shares_profile_idx on public.document_shares(profile_id,document_id); create index if not exists document_requests_profile_status_idx on public.document_requests(profile_id,status); create index if not exists document_submissions_request_idx on public.document_submissions(request_id);
drop trigger if exists documents_touch_updated_at on public.documents; create trigger documents_touch_updated_at before update on public.documents for each row execute function public.touch_updated_at();
drop trigger if exists document_requests_touch_updated_at on public.document_requests; create trigger document_requests_touch_updated_at before update on public.document_requests for each row execute function public.touch_updated_at();
create or replace function public.document_manager_can_manage(target uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_management() or (public.current_role()='general_manager' and public.in_management_tree(target)) $$;
alter table public.document_shares enable row level security; alter table public.document_requests enable row level security; alter table public.document_submissions enable row level security;
drop policy if exists "documents visible to signed in" on public.documents; create policy "documents shared with audience" on public.documents for select to authenticated using(public.is_management() or exists(select 1 from public.document_shares s where s.document_id=id and (s.shared_with_all or s.profile_id=auth.uid())));
create policy "documents managers write" on public.documents for all to authenticated using(public.is_management() or (public.current_role()='general_manager' and uploaded_by=auth.uid())) with check(public.is_management() or (public.current_role()='general_manager' and uploaded_by=auth.uid()));
create policy "document shares visible to audience" on public.document_shares for select to authenticated using(shared_with_all or profile_id=auth.uid() or public.is_management()); create policy "document shares managers write" on public.document_shares for all to authenticated using(public.is_management()) with check(public.is_management());
create policy "document requests own or hierarchy" on public.document_requests for select to authenticated using(profile_id=auth.uid() or public.document_manager_can_manage(profile_id)); create policy "document requests managers write" on public.document_requests for insert to authenticated with check(public.document_manager_can_manage(profile_id)); create policy "document requests employee submit" on public.document_requests for update to authenticated using(profile_id=auth.uid() and status in ('requested','rejected')) with check(profile_id=auth.uid() and status='submitted'); create policy "document requests managers review" on public.document_requests for update to authenticated using(public.document_manager_can_manage(profile_id)) with check(public.document_manager_can_manage(profile_id));
create policy "document submissions own or hierarchy" on public.document_submissions for select to authenticated using(submitted_by=auth.uid() or exists(select 1 from public.document_requests r where r.id=request_id and public.document_manager_can_manage(r.profile_id))); create policy "document submissions own request" on public.document_submissions for insert to authenticated with check(submitted_by=auth.uid() and exists(select 1 from public.document_requests r where r.id=request_id and r.profile_id=auth.uid() and r.status='submitted'));
-- Keep files private: signed URLs are issued only after the document records above pass RLS.
drop policy if exists "employee document uploads" on storage.objects; create policy "document uploads by owner or management" on storage.objects for insert to authenticated with check(bucket_id='employee-documents' and (public.is_management() or (owner_id=auth.uid()::text and (storage.foldername(name))[1]=auth.uid()::text)));
drop policy if exists "employee document downloads" on storage.objects; create policy "document downloads for authorized records" on storage.objects for select to authenticated using(bucket_id='employee-documents' and (public.is_management() or exists(select 1 from public.documents d where d.storage_path=name) or exists(select 1 from public.document_submissions s where s.storage_path=name and (s.submitted_by=auth.uid() or exists(select 1 from public.document_requests r where r.id=s.request_id and public.document_manager_can_manage(r.profile_id))))));
