-- Targeted employee announcements with simple read receipts.
alter table public.announcements add column if not exists category text not null default 'general' check(category in ('general','hr','holiday','meeting','policy','event','urgent')), add column if not exists status text not null default 'draft' check(status in ('draft','published','archived')), add column if not exists is_pinned boolean not null default false, add column if not exists audience_type text not null default 'all' check(audience_type in ('all','department','employees')), add column if not exists department_id uuid references public.departments(id) on delete set null, add column if not exists expires_at timestamptz, add column if not exists created_at timestamptz not null default now(), add column if not exists updated_at timestamptz not null default now();
create table if not exists public.announcement_recipients (id uuid primary key default gen_random_uuid(), announcement_id uuid not null references public.announcements(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), unique(announcement_id,profile_id));
create table if not exists public.announcement_reads (id uuid primary key default gen_random_uuid(), announcement_id uuid not null references public.announcements(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, read_at timestamptz not null default now(), unique(announcement_id,profile_id));
create index if not exists announcements_active_idx on public.announcements(status,published_at,is_pinned); create index if not exists announcement_recipients_profile_idx on public.announcement_recipients(profile_id,announcement_id); create index if not exists announcement_reads_profile_idx on public.announcement_reads(profile_id,announcement_id);
drop trigger if exists announcements_touch_updated_at on public.announcements; create trigger announcements_touch_updated_at before update on public.announcements for each row execute function public.touch_updated_at();
create or replace function public.announcement_manager_can_manage(target uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_management() or (public.current_role()='general_manager' and (target is null or public.in_management_tree(target))) $$;
alter table public.announcement_recipients enable row level security; alter table public.announcement_reads enable row level security;
drop policy if exists "announcements visible to signed in" on public.announcements; create policy "announcements visible to audience" on public.announcements for select to authenticated using(status='published' and published_at<=now() and (expires_at is null or expires_at>now()) and (audience_type='all' or (audience_type='department' and department_id=(select department_id from public.profiles where id=auth.uid())) or (audience_type='employees' and exists(select 1 from public.announcement_recipients r where r.announcement_id=id and r.profile_id=auth.uid()))) or public.is_management());
create policy "announcements manager write" on public.announcements for all to authenticated using(public.is_management() or (public.current_role()='general_manager' and public.announcement_manager_can_manage(department_id))) with check(public.is_management() or (public.current_role()='general_manager' and public.announcement_manager_can_manage(department_id)));
create policy "announcement recipients own or management" on public.announcement_recipients for select to authenticated using(profile_id=auth.uid() or public.is_management()); create policy "announcement recipients manager write" on public.announcement_recipients for all to authenticated using(public.is_management()) with check(public.is_management());
create policy "announcement reads own" on public.announcement_reads for select to authenticated using(profile_id=auth.uid()); create policy "announcement reads own write" on public.announcement_reads for insert to authenticated with check(profile_id=auth.uid() and exists(select 1 from public.announcements a where a.id=announcement_id)); create policy "announcement reads management" on public.announcement_reads for select to authenticated using(public.is_management());
