-- Extends the existing per-recipient notifications table with links and automatic event delivery.
alter table public.notifications add column if not exists sender_id uuid references public.profiles(id) on delete set null, add column if not exists related_entity_id uuid, add column if not exists deep_link text, add column if not exists updated_at timestamptz not null default now();
create index if not exists notifications_profile_created_idx on public.notifications(profile_id,created_at desc); create index if not exists notifications_profile_unread_idx on public.notifications(profile_id,read_at) where read_at is null;
drop trigger if exists notifications_touch_updated_at on public.notifications; create trigger notifications_touch_updated_at before update on public.notifications for each row execute function public.touch_updated_at();
drop policy if exists "notifications are private" on public.notifications; create policy "notifications own or management read" on public.notifications for select to authenticated using(profile_id=auth.uid() or public.is_management() or (public.current_role()='general_manager' and public.in_management_tree(profile_id))); create policy "notifications own read update" on public.notifications for update to authenticated using(profile_id=auth.uid()) with check(profile_id=auth.uid());
create or replace function public.notify_user(target uuid,heading text,message text,kind text,entity uuid default null,link text default null,sender uuid default auth.uid()) returns void language plpgsql security definer set search_path=public as $$ begin if target is not null then insert into public.notifications(profile_id,title,body,type,related_entity_id,deep_link,sender_id) values(target,heading,message,kind,entity,link,sender); end if; end $$;
create or replace function public.notify_task_assignment() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.notify_user(new.profile_id,'Task assigned','You have been assigned a new task.','task_assigned',new.task_id,'/employee/tasks'); return new; end $$;
drop trigger if exists task_assignment_notification on public.task_assignments; create trigger task_assignment_notification after insert on public.task_assignments for each row execute function public.notify_task_assignment();
create or replace function public.notify_task_update() returns trigger language plpgsql security definer set search_path=public as $$ declare owner uuid; begin if new.status is distinct from old.status then select created_by into owner from public.tasks where id=new.task_id; perform public.notify_user(owner,'Task updated','An employee updated task progress.','task_updated',new.task_id,'/admin/tasks',new.profile_id); end if; return new; end $$;
drop trigger if exists task_update_notification on public.task_assignments; create trigger task_update_notification after update on public.task_assignments for each row execute function public.notify_task_update();
create or replace function public.notify_leave_event() returns trigger language plpgsql security definer set search_path=public as $$ declare manager record; begin if TG_OP='INSERT' then for manager in select id from public.profiles where role in ('chairman','director','general_manager') loop perform public.notify_user(manager.id,'New leave request','An employee submitted a leave request.','leave_submitted',new.id,'/admin/leaves',new.profile_id); end loop; elsif new.status is distinct from old.status and new.status in ('approved','rejected') then perform public.notify_user(new.profile_id,'Leave request '||new.status,'Your leave request was '||new.status||'.','leave_'||new.status,new.id,'/employee/leaves',new.approver_id); end if; return new; end $$;
drop trigger if exists leave_notification on public.leave_requests; create trigger leave_notification after insert or update on public.leave_requests for each row execute function public.notify_leave_event();
create or replace function public.notify_document_event() returns trigger language plpgsql security definer set search_path=public as $$ declare req record; begin if TG_TABLE_NAME='document_requests' and TG_OP='INSERT' then perform public.notify_user(new.profile_id,'Document requested','A document has been requested from you.','document_requested',new.id,'/employee/documents',new.requested_by); elsif TG_TABLE_NAME='document_requests' and new.status is distinct from old.status and new.status in ('approved','rejected') then perform public.notify_user(new.profile_id,'Document '||new.status,'Your document submission was '||new.status||'.','document_'||new.status,new.id,'/employee/documents',new.reviewer_id); elsif TG_TABLE_NAME='document_submissions' then select * into req from public.document_requests where id=new.request_id; perform public.notify_user(req.requested_by,'Document submitted','An employee submitted a requested document.','document_submitted',new.request_id,'/admin/documents',new.submitted_by); end if; return new; end $$;
drop trigger if exists document_request_notification on public.document_requests; create trigger document_request_notification after insert or update on public.document_requests for each row execute function public.notify_document_event(); drop trigger if exists document_submission_notification on public.document_submissions; create trigger document_submission_notification after insert on public.document_submissions for each row execute function public.notify_document_event();
create or replace function public.notify_announcement_publish() returns trigger language plpgsql security definer set search_path=public as $$ declare recipient record; begin if new.status='published' and (TG_OP='INSERT' or old.status is distinct from 'published') then for recipient in select id from public.profiles p where new.audience_type='all' or (new.audience_type='department' and p.department_id=new.department_id) or (new.audience_type='employees' and exists(select 1 from public.announcement_recipients r where r.announcement_id=new.id and r.profile_id=p.id)) loop perform public.notify_user(recipient.id,'New announcement',new.title,'new_announcement',new.id,'/employee/announcements',new.author_id); end loop; end if; return new; end $$;
drop trigger if exists announcement_notification on public.announcements; create trigger announcement_notification after insert or update on public.announcements for each row execute function public.notify_announcement_publish();
