-- Extends the original chat tables for private personal/group messaging.
-- Normalize legacy/preliminary chat schemas before referring to their columns.
alter table public.chat_members add column if not exists conversation_id uuid references public.chat_conversations(id) on delete cascade, add column if not exists profile_id uuid references public.profiles(id) on delete cascade, add column if not exists last_read_at timestamptz;
alter table public.chat_messages add column if not exists conversation_id uuid references public.chat_conversations(id) on delete cascade, add column if not exists sender_id uuid references public.profiles(id) on delete cascade, add column if not exists body text not null default '', add column if not exists created_at timestamptz not null default now();
do $$ begin
 if exists(select 1 from information_schema.columns where table_schema='public' and table_name='chat_members' and column_name='conversationId') then execute 'update public.chat_members set conversation_id="conversationId" where conversation_id is null'; end if;
 if exists(select 1 from information_schema.columns where table_schema='public' and table_name='chat_members' and column_name='user_id') then execute 'update public.chat_members set profile_id=user_id where profile_id is null'; end if;
end $$;
alter table public.chat_conversations add column if not exists created_by uuid references public.profiles(id) on delete set null, add column if not exists group_admin_id uuid references public.profiles(id) on delete set null, add column if not exists updated_at timestamptz not null default now();
alter table public.chat_messages add column if not exists message_type text not null default 'text' check(message_type in ('text','attachment')), add column if not exists attachment_path text, add column if not exists attachment_name text, add column if not exists attachment_type text, add column if not exists attachment_size bigint check(attachment_size is null or attachment_size>=0);
create table if not exists public.chat_message_reads (message_id uuid not null references public.chat_messages(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, read_at timestamptz not null default now(), primary key(message_id,profile_id));
create index if not exists chat_members_profile_idx on public.chat_members(profile_id,conversation_id); create index if not exists chat_messages_conversation_created_idx on public.chat_messages(conversation_id,created_at); create index if not exists chat_reads_profile_idx on public.chat_message_reads(profile_id,message_id);
create or replace function public.is_chat_member(conversation uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.chat_members where conversation_id=conversation and profile_id=auth.uid()) $$;
alter table public.chat_conversations enable row level security; alter table public.chat_members enable row level security; alter table public.chat_messages enable row level security; alter table public.chat_message_reads enable row level security;
create policy "chat conversations own" on public.chat_conversations for select to authenticated using(public.is_chat_member(id)); create policy "chat conversations create" on public.chat_conversations for insert to authenticated with check(created_by=auth.uid()); create policy "chat groups admin update" on public.chat_conversations for update to authenticated using(group_admin_id=auth.uid()) with check(group_admin_id=auth.uid());
create policy "chat members own conversation" on public.chat_members for select to authenticated using(public.is_chat_member(conversation_id)); create policy "chat members group admin write" on public.chat_members for insert to authenticated with check(exists(select 1 from public.chat_conversations c where c.id=conversation_id and c.group_admin_id=auth.uid())); create policy "chat members leave" on public.chat_members for delete to authenticated using(profile_id=auth.uid() or exists(select 1 from public.chat_conversations c where c.id=conversation_id and c.group_admin_id=auth.uid()));
create policy "chat messages own conversation" on public.chat_messages for select to authenticated using(public.is_chat_member(conversation_id)); create policy "chat messages send" on public.chat_messages for insert to authenticated with check(sender_id=auth.uid() and public.is_chat_member(conversation_id));
create policy "chat reads own" on public.chat_message_reads for select to authenticated using(profile_id=auth.uid()); create policy "chat reads insert own" on public.chat_message_reads for insert to authenticated with check(profile_id=auth.uid() and exists(select 1 from public.chat_messages m where m.id=message_id and public.is_chat_member(m.conversation_id)));
insert into storage.buckets(id,name,public) values('chat-attachments','chat-attachments',false) on conflict(id) do nothing;
create policy "chat attachment upload" on storage.objects for insert to authenticated with check(bucket_id='chat-attachments' and owner_id=auth.uid()::text and (storage.foldername(name))[1]=auth.uid()::text); create policy "chat attachment member view" on storage.objects for select to authenticated using(bucket_id='chat-attachments' and owner_id=auth.uid()::text);
create or replace function public.notify_chat_message() returns trigger language plpgsql security definer set search_path=public as $$ declare member record; begin for member in select profile_id from public.chat_members where conversation_id=new.conversation_id and profile_id<>new.sender_id loop perform public.notify_user(member.profile_id,'New message',coalesce(new.body,'Attachment received'),'chat_message',new.id,'/employee/chat',new.sender_id); end loop; return new; end $$;
drop trigger if exists chat_message_notification on public.chat_messages; create trigger chat_message_notification after insert on public.chat_messages for each row execute function public.notify_chat_message();
alter publication supabase_realtime add table public.chat_messages, public.chat_members, public.chat_message_reads;
