-- Finance & Accounts MVP. Run after 0020 and 0021.
create table if not exists public.finance_accounts (
 id uuid primary key default gen_random_uuid(), name text not null unique, account_type text not null check(account_type in ('cash','bank','wallet','other')), opening_balance numeric(14,2) not null default 0, currency text not null default 'INR', is_active boolean not null default true, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.finance_income_categories (id uuid primary key default gen_random_uuid(), name text not null unique, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.finance_expense_categories (id uuid primary key default gen_random_uuid(), name text not null unique, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.finance_transactions (
 id uuid primary key default gen_random_uuid(), transaction_type text not null check(transaction_type in ('income','expense','adjustment','invoice_payment','payroll_payment')), account_id uuid not null references public.finance_accounts(id), income_category_id uuid references public.finance_income_categories(id), expense_category_id uuid references public.finance_expense_categories(id), amount numeric(14,2) not null check(amount>0), transaction_date date not null default current_date, payment_method text not null default 'cash', reference_number text, description text, client_id uuid references public.clients(id), sale_id uuid references public.crm_sales(id), receipt_path text, created_by uuid references public.profiles(id), archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check((transaction_type='income' and income_category_id is not null and expense_category_id is null) or (transaction_type='expense' and expense_category_id is not null and income_category_id is null) or transaction_type in ('adjustment','invoice_payment','payroll_payment'))
);
create table if not exists public.finance_invoices (id uuid primary key default gen_random_uuid(), invoice_number text not null unique, client_id uuid references public.clients(id), customer_name text not null, issue_date date not null default current_date, due_date date, discount numeric(14,2) not null default 0 check(discount>=0), tax numeric(14,2) not null default 0 check(tax>=0), notes text, status text not null default 'draft' check(status in ('draft','sent','partially_paid','paid','overdue','cancelled')), currency text not null default 'INR', created_by uuid references public.profiles(id), archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.finance_invoice_items (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.finance_invoices(id) on delete cascade, description text not null, quantity numeric(12,2) not null default 1 check(quantity>0), rate numeric(14,2) not null check(rate>=0), created_at timestamptz not null default now());
create table if not exists public.finance_invoice_payments (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.finance_invoices(id) on delete cascade, account_id uuid not null references public.finance_accounts(id), amount numeric(14,2) not null check(amount>0), payment_date date not null default current_date, payment_method text not null default 'cash', reference_number text, received_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table if not exists public.employee_salary_settings (id uuid primary key default gen_random_uuid(), profile_id uuid not null unique references public.profiles(id) on delete cascade, basic_salary numeric(14,2) not null default 0 check(basic_salary>=0), default_allowances numeric(14,2) not null default 0 check(default_allowances>=0), default_deductions numeric(14,2) not null default 0 check(default_deductions>=0), updated_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.payroll_runs (id uuid primary key default gen_random_uuid(), period_start date not null, period_end date not null, status text not null default 'draft' check(status in ('draft','approved','paid')), payment_date date, account_id uuid references public.finance_accounts(id), payment_method text, created_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(period_start,period_end), check(period_end>=period_start));
create table if not exists public.payroll_entries (id uuid primary key default gen_random_uuid(), payroll_run_id uuid not null references public.payroll_runs(id) on delete cascade, profile_id uuid not null references public.profiles(id), basic_salary numeric(14,2) not null default 0, allowances numeric(14,2) not null default 0, deductions numeric(14,2) not null default 0, payment_status text not null default 'draft' check(payment_status in ('draft','approved','paid')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(payroll_run_id,profile_id));
create index if not exists finance_transactions_account_date_idx on public.finance_transactions(account_id,transaction_date desc) where archived_at is null;
create index if not exists finance_transactions_type_date_idx on public.finance_transactions(transaction_type,transaction_date desc) where archived_at is null;
create index if not exists finance_invoice_payments_invoice_idx on public.finance_invoice_payments(invoice_id);

insert into public.finance_accounts(name,account_type,opening_balance,currency) values ('Cash','cash',0,'INR'),('Primary Bank','bank',0,'INR') on conflict(name) do nothing;
insert into public.finance_income_categories(name) values ('Consultation'),('Session'),('Service'),('Product'),('Other') on conflict(name) do nothing;
insert into public.finance_expense_categories(name) values ('Salary'),('Rent'),('Utilities'),('Marketing'),('Software'),('Travel'),('Office'),('Other') on conflict(name) do nothing;

create or replace function public.finance_account_balance(subject_account uuid) returns numeric language sql stable security definer set search_path=public as $$ select coalesce((select opening_balance from public.finance_accounts where id=subject_account),0)+coalesce((select sum(case when transaction_type in ('income','invoice_payment','adjustment') then amount else -amount end) from public.finance_transactions where account_id=subject_account and archived_at is null),0) $$;
create or replace function public.finance_invoice_total(subject_invoice uuid) returns numeric language sql stable security definer set search_path=public as $$ select coalesce((select sum(quantity*rate) from public.finance_invoice_items where invoice_id=subject_invoice),0)+coalesce((select tax-discount from public.finance_invoices where id=subject_invoice),0) $$;
create or replace function public.finance_invoice_paid(subject_invoice uuid) returns numeric language sql stable security definer set search_path=public as $$ select coalesce(sum(amount),0) from public.finance_invoice_payments where invoice_id=subject_invoice $$;
create or replace function public.finance_refresh_invoice_status() returns trigger language plpgsql security definer set search_path=public as $$ declare total numeric; paid numeric; begin select public.finance_invoice_total(coalesce(new.invoice_id,old.invoice_id)),public.finance_invoice_paid(coalesce(new.invoice_id,old.invoice_id)) into total,paid; update public.finance_invoices set status=case when status='cancelled' then 'cancelled' when paid>=total and total>0 then 'paid' when paid>0 then 'partially_paid' when due_date<current_date then 'overdue' else status end where id=coalesce(new.invoice_id,old.invoice_id); return coalesce(new,old); end $$;
drop trigger if exists finance_invoice_payment_status on public.finance_invoice_payments; create trigger finance_invoice_payment_status after insert or update or delete on public.finance_invoice_payments for each row execute function public.finance_refresh_invoice_status();

alter table public.finance_accounts enable row level security; alter table public.finance_income_categories enable row level security; alter table public.finance_expense_categories enable row level security; alter table public.finance_transactions enable row level security; alter table public.finance_invoices enable row level security; alter table public.finance_invoice_items enable row level security; alter table public.finance_invoice_payments enable row level security; alter table public.employee_salary_settings enable row level security; alter table public.payroll_runs enable row level security; alter table public.payroll_entries enable row level security;
create policy "finance accounts view" on public.finance_accounts for select to authenticated using(public.has_permission('finance.view') or public.has_permission('finance.manage')); create policy "finance accounts manage" on public.finance_accounts for all to authenticated using(public.has_permission('finance.manage')) with check(public.has_permission('finance.manage'));
create policy "finance income categories" on public.finance_income_categories for select to authenticated using(public.has_permission('finance.view') or public.has_permission('finance.manage')); create policy "finance expense categories" on public.finance_expense_categories for select to authenticated using(public.has_permission('finance.view') or public.has_permission('finance.manage'));
create policy "finance transactions access" on public.finance_transactions for all to authenticated using(public.has_permission('finance.view') or public.has_permission('finance.manage')) with check(public.has_permission('finance.manage'));
create policy "finance invoices access" on public.finance_invoices for select to authenticated using(public.has_permission('invoices.view') or public.has_permission('invoices.manage')); create policy "finance invoices manage" on public.finance_invoices for all to authenticated using(public.has_permission('invoices.manage')) with check(public.has_permission('invoices.manage'));
create policy "finance invoice items access" on public.finance_invoice_items for all to authenticated using(public.has_permission('invoices.view') or public.has_permission('invoices.manage')) with check(public.has_permission('invoices.manage')); create policy "finance invoice payments access" on public.finance_invoice_payments for all to authenticated using(public.has_permission('invoices.view') or public.has_permission('invoices.manage')) with check(public.has_permission('invoices.manage'));
create policy "salary settings access" on public.employee_salary_settings for all to authenticated using(public.has_permission('payroll.view') or public.has_permission('payroll.manage')) with check(public.has_permission('payroll.manage')); create policy "payroll runs access" on public.payroll_runs for all to authenticated using(public.has_permission('payroll.view') or public.has_permission('payroll.manage')) with check(public.has_permission('payroll.manage')); create policy "payroll entries access" on public.payroll_entries for all to authenticated using(public.has_permission('payroll.view') or public.has_permission('payroll.manage')) with check(public.has_permission('payroll.manage'));
