-- Patient records are deliberately separate from CRM leads and retain private storage objects.
insert into public.permissions(code,description) values
('patients.view','View permitted patient records'),('patients.create','Create patient records'),('patients.edit','Edit patient records'),('patients.archive','Archive patient records'),
('patient_documents.view','View permitted patient documents'),('patient_documents.upload','Upload patient documents'),('patient_documents.download','Download patient documents'),('patient_documents.replace','Replace patient documents'),('patient_documents.archive','Archive patient documents'),('patient_documents.delete','Soft delete patient documents'),
('patient_notes.view','View administrative patient notes'),('patient_notes.create','Create administrative patient notes'),('patient_notes.edit','Edit administrative patient notes'),('patient_notes.delete','Delete administrative patient notes'),
('clinical_notes.view','View clinical notes'),('clinical_notes.create','Create clinical notes'),('clinical_notes.edit','Edit clinical notes'),('clinical_notes.delete','Delete clinical notes'),('patient_activity.view','View patient activity') on conflict(code) do nothing;

create table if not exists public.patients (
 id uuid primary key default gen_random_uuid(), patient_number text unique not null, full_name text not null, date_of_birth date, gender text, phone text, email text, address text, nationality text, preferred_language text,
 emergency_contact_name text, emergency_contact_relationship text, emergency_contact_phone text, emergency_contact_alternative_phone text, assigned_psychologist_id uuid references public.profiles(id), source text check(source is null or source in ('Website','Walk-in','Referral','Social media','Google','Existing patient','Corporate','Other')), status text not null default 'active' check(status in ('active','inactive','discharged')), tags text[] not null default '{}', created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table if not exists public.patient_sessions (
 id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.patients(id), appointment_at timestamptz not null, assigned_psychologist_id uuid references public.profiles(id), session_type text not null default 'Initial consultation', session_number integer, duration_minutes integer check(duration_minutes is null or duration_minutes > 0), attendance_status text not null default 'scheduled' check(attendance_status in ('scheduled','completed','cancelled','no_show','rescheduled')), follow_up_at date, administrative_summary text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table if not exists public.patient_documents (
 id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.patients(id), document_name text not null, original_filename text not null, category text not null, storage_provider text not null default 'supabase', storage_bucket text not null default 'patient-documents', storage_key text not null unique, mime_type text not null, file_extension text, file_size_bytes bigint not null check(file_size_bytes > 0), document_date date, expiry_date date, visibility text not null default 'general_staff' check(visibility in ('general_staff','assigned_psychologist','clinical_team','management_only')), status text not null default 'active' check(status in ('active','archived','replaced','pending_review','rejected')), version integer not null default 1 check(version > 0), parent_document_id uuid references public.patient_documents(id), related_session_id uuid references public.patient_sessions(id), notes text, checksum text, uploaded_by uuid not null references public.profiles(id), uploaded_at timestamptz not null default now(), updated_by uuid references public.profiles(id), updated_at timestamptz not null default now(), archived_at timestamptz, archived_by uuid references public.profiles(id), deleted_at timestamptz, deleted_by uuid references public.profiles(id)
);
create table if not exists public.patient_notes (
 id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.patients(id), note_type text not null check(note_type in ('administrative','clinical')), content text not null, visibility text not null default 'general_staff', related_session_id uuid references public.patient_sessions(id), created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_by uuid references public.profiles(id), updated_at timestamptz, deleted_at timestamptz
);
create table if not exists public.patient_activity_logs (
 id uuid primary key default gen_random_uuid(), patient_id uuid not null references public.patients(id), document_id uuid references public.patient_documents(id), action text not null, entity_type text not null, entity_id uuid, performed_by uuid references public.profiles(id), metadata jsonb not null default '{}', ip_address text, user_agent text, created_at timestamptz not null default now()
);
create index if not exists patients_search_idx on public.patients(patient_number,status,created_at desc) where deleted_at is null;
create index if not exists patient_sessions_patient_idx on public.patient_sessions(patient_id,appointment_at desc) where deleted_at is null;
create index if not exists patient_documents_patient_idx on public.patient_documents(patient_id,uploaded_at desc) where deleted_at is null;
create index if not exists patient_documents_category_idx on public.patient_documents(category); create index if not exists patient_documents_status_idx on public.patient_documents(status); create index if not exists patient_documents_expiry_idx on public.patient_documents(expiry_date); create index if not exists patient_documents_uploader_idx on public.patient_documents(uploaded_by); create index if not exists patient_documents_parent_idx on public.patient_documents(parent_document_id); create index if not exists patient_activity_patient_idx on public.patient_activity_logs(patient_id,created_at desc);

create or replace function public.patient_access(patient uuid) returns boolean language sql stable security definer set search_path=public as $$
 select public.has_permission('patients.view') and exists(select 1 from public.patients p where p.id=patient and p.deleted_at is null and (p.assigned_psychologist_id is null or p.assigned_psychologist_id=auth.uid() or public.current_role()<>'general_manager' or public.in_management_tree(p.assigned_psychologist_id)))
$$;
create or replace function public.patient_document_access(doc public.patient_documents) returns boolean language sql stable security definer set search_path=public as $$
 select public.patient_access(doc.patient_id) and public.has_permission('patient_documents.view') and (doc.visibility='general_staff' or (doc.visibility='assigned_psychologist' and exists(select 1 from public.patients p where p.id=doc.patient_id and p.assigned_psychologist_id=auth.uid())) or (doc.visibility='clinical_team' and public.has_permission('clinical_notes.view')) or (doc.visibility='management_only' and public.is_management()))
$$;
create or replace function public.patient_activity_event() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if tg_table_name='patients' then insert into public.patient_activity_logs(patient_id,action,entity_type,entity_id,performed_by,metadata) values(coalesce(new.id,old.id),case when tg_op='INSERT' then 'patient_created' when tg_op='DELETE' then 'patient_deleted' else 'patient_updated' end,'patient',coalesce(new.id,old.id),auth.uid(),'{}');
 elsif tg_table_name='patient_documents' then insert into public.patient_activity_logs(patient_id,document_id,action,entity_type,entity_id,performed_by,metadata) values(coalesce(new.patient_id,old.patient_id),coalesce(new.id,old.id),case when tg_op='INSERT' then 'document_uploaded' when new.deleted_at is not null and old.deleted_at is null then 'document_deleted' when new.status='archived' then 'document_archived' when new.status='replaced' then 'document_replaced' else 'document_updated' end,'patient_document',coalesce(new.id,old.id),auth.uid(),jsonb_build_object('version',coalesce(new.version,old.version)));
 end if; return coalesce(new,old); end $$;
drop trigger if exists patients_patient_activity on public.patients; create trigger patients_patient_activity after insert or update or delete on public.patients for each row execute function public.patient_activity_event();
drop trigger if exists patient_documents_patient_activity on public.patient_documents; create trigger patient_documents_patient_activity after insert or update on public.patient_documents for each row execute function public.patient_activity_event();
do $$ declare t text; begin foreach t in array array['patients','patient_sessions','patient_documents','patient_notes','patient_activity_logs'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy "patient records access" on public.patients for select to authenticated using(public.patient_access(id)); create policy "patient records create" on public.patients for insert to authenticated with check(public.has_permission('patients.create')); create policy "patient records edit" on public.patients for update to authenticated using(public.patient_access(id) and public.has_permission('patients.edit')) with check(public.has_permission('patients.edit'));
create policy "patient sessions access" on public.patient_sessions for select to authenticated using(deleted_at is null and public.patient_access(patient_id)); create policy "patient sessions write" on public.patient_sessions for all to authenticated using(public.patient_access(patient_id) and public.has_permission('patients.edit')) with check(public.patient_access(patient_id) and public.has_permission('patients.edit'));
create policy "patient documents access" on public.patient_documents for select to authenticated using(deleted_at is null and public.patient_document_access(patient_documents)); create policy "patient documents write" on public.patient_documents for insert to authenticated with check(public.patient_access(patient_id) and public.has_permission('patient_documents.upload')); create policy "patient documents change" on public.patient_documents for update to authenticated using(public.patient_document_access(patient_documents)) with check(public.patient_access(patient_id) and (public.has_permission('patient_documents.archive') or public.has_permission('patient_documents.replace') or public.has_permission('patient_documents.delete')));
create policy "patient notes access" on public.patient_notes for select to authenticated using(deleted_at is null and public.patient_access(patient_id) and ((note_type='administrative' and public.has_permission('patient_notes.view')) or (note_type='clinical' and public.has_permission('clinical_notes.view')))); create policy "patient notes write" on public.patient_notes for all to authenticated using(public.patient_access(patient_id) and ((note_type='administrative' and public.has_permission('patient_notes.edit')) or (note_type='clinical' and public.has_permission('clinical_notes.edit')))) with check(public.patient_access(patient_id) and ((note_type='administrative' and public.has_permission('patient_notes.create')) or (note_type='clinical' and public.has_permission('clinical_notes.create'))));
create policy "patient activity access" on public.patient_activity_logs for select to authenticated using(public.patient_access(patient_id) and public.has_permission('patient_activity.view'));
insert into storage.buckets(id,name,public) values ('patient-documents','patient-documents',false) on conflict(id) do update set public=false;
create policy "patient storage upload" on storage.objects for insert to authenticated with check(bucket_id='patient-documents' and public.has_permission('patient_documents.upload')); create policy "patient storage read" on storage.objects for select to authenticated using(bucket_id='patient-documents' and exists(select 1 from public.patient_documents d where d.storage_key=name and public.patient_document_access(d)));
-- TODO: route new uploads through a malware/quarantine scanner before enabling any automated processing.
