insert into public.permissions(code,description) values
 ('patient_sessions.create','Create patient sessions'),('patient_sessions.edit','Edit patient sessions'),('patient_sessions.cancel','Cancel or reschedule patient sessions') on conflict(code) do nothing;
drop policy if exists "patient sessions write" on public.patient_sessions;
create policy "patient sessions create" on public.patient_sessions for insert to authenticated with check(public.patient_access(patient_id) and public.has_permission('patient_sessions.create'));
create policy "patient sessions edit" on public.patient_sessions for update to authenticated using(public.patient_access(patient_id) and (public.has_permission('patient_sessions.edit') or public.has_permission('patient_sessions.cancel'))) with check(public.patient_access(patient_id) and (public.has_permission('patient_sessions.edit') or public.has_permission('patient_sessions.cancel')));
create or replace function public.patient_action_activity_event() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if tg_table_name='patient_sessions' then insert into public.patient_activity_logs(patient_id,action,entity_type,entity_id,performed_by,metadata) values(coalesce(new.patient_id,old.patient_id),case when tg_op='INSERT' then 'session_created' when new.attendance_status in ('cancelled','rescheduled') then 'session_'||new.attendance_status else 'session_updated' end,'patient_session',coalesce(new.id,old.id),auth.uid(),jsonb_build_object('attendance_status',coalesce(new.attendance_status,old.attendance_status)));
 elsif tg_table_name='patient_notes' then insert into public.patient_activity_logs(patient_id,action,entity_type,entity_id,performed_by,metadata) values(coalesce(new.patient_id,old.patient_id),case when tg_op='INSERT' then 'note_created' when new.deleted_at is not null then 'note_deleted' else 'note_updated' end,'patient_note',coalesce(new.id,old.id),auth.uid(),jsonb_build_object('note_type',coalesce(new.note_type,old.note_type)));
 end if; return coalesce(new,old); end $$;
drop trigger if exists patient_sessions_action_activity on public.patient_sessions; create trigger patient_sessions_action_activity after insert or update on public.patient_sessions for each row execute function public.patient_action_activity_event();
drop trigger if exists patient_notes_action_activity on public.patient_notes; create trigger patient_notes_action_activity after insert or update on public.patient_notes for each row execute function public.patient_action_activity_event();
