'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { currentProfile } from '@/lib/auth';
import { employeeRepository } from '@/lib/employee-repository';

const emptyFilters = { query: '', status_id: '', source_id: '', temperature: '', date: '', profession: '', location: '' };
const dash = (value: any) => value === null || value === undefined || value === '' ? '—' : value;
function Clamp({ value, muted = false }: { value: any; muted?: boolean }) { const text = String(dash(value)); return <span title={text} className={muted ? 'block line-clamp-2 text-xs text-slate-500' : 'block line-clamp-2'}>{text}</span>; }
function nextFollowUp(lead: any) { const item = lead.crm_lead_followups?.find((followup: any) => followup.next_follow_up_at); return item?.next_follow_up_at ? new Date(item.next_follow_up_at).toLocaleDateString() : '—'; }

export default function MyLeadsPage() {
  const [profile, setProfile] = useState<any>(); const [leads, setLeads] = useState<any[]>([]); const [lookups, setLookups] = useState<any>({ sources: [], statuses: [] });
  const [filters, setFilters] = useState<any>(emptyFilters); const [add, setAdd] = useState(false); const [expanded, setExpanded] = useState<string | null>(null);
  const [form, setForm] = useState<any>({ full_name: '', phone: '', source_id: '', status_id: '', temperature: 'cold' }); const [error, setError] = useState(''); const [saving, setSaving] = useState<string | null>(null);
  const load = async (user = profile) => { if (!user) return; try { setLeads(await employeeRepository.myCrmLeads(user.id, filters)); } catch (caught: any) { setError(caught.message); } };
  useEffect(() => { const timer = setTimeout(() => void (async () => { try { const user = await currentProfile() as any; if (!user) throw Error('Please sign in again.'); const options = await employeeRepository.crmLookups(); setProfile(user); setLookups(options); setForm((old: any) => ({ ...old, source_id: old.source_id || options.sources[0]?.id || '', status_id: old.status_id || options.statuses[0]?.id || '' })); } catch (caught: any) { setError(caught.message); } })(), 0); return () => clearTimeout(timer); }, []);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [profile, filters]);
  const create = async (event: FormEvent) => { event.preventDefault(); if (!form.full_name.trim() || form.phone.replace(/\D/g, '').length < 7) { setError('Enter a lead name and a phone number with at least 7 digits.'); return; } setSaving('new'); setError(''); try { await employeeRepository.createMyCrmLead({ ...form, full_name: form.full_name.trim(), phone: form.phone.replace(/\D/g, '') }); setAdd(false); setForm({ ...form, full_name: '', phone: '' }); await load(); } catch (caught: any) { setError(caught.message || 'Lead could not be created.'); } finally { setSaving(null); } };
  const quickUpdate = async (leadId: string, patch: any) => { setSaving(leadId); setError(''); try { await employeeRepository.updateMyCrmLead(profile.id, leadId, patch); setLeads(current => current.map(item => item.id === leadId ? { ...item, ...patch } : item)); } catch (caught: any) { setError(caught.message); } finally { setSaving(null); } };
  const statusSelect = (lead: any) => <select aria-label={`Status for ${lead.full_name}`} className="input h-9 min-w-0 px-2 py-1 text-xs" value={lead.status_id || ''} disabled={saving === lead.id} onChange={event => void quickUpdate(lead.id, { status_id: event.target.value })}>{lookups.statuses.map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select>;
  const temperatureSelect = (lead: any) => <select aria-label={`Temperature for ${lead.full_name}`} className="input h-9 min-w-0 px-2 py-1 text-xs" value={lead.temperature} disabled={saving === lead.id} onChange={event => void quickUpdate(lead.id, { temperature: event.target.value })}><option value="cold">Cold</option><option value="warm">Warm</option><option value="hot">Hot</option></select>;
  return <section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">My Leads</h1><p className="text-slate-600">Review client details and update status or temperature directly.</p></div><button className="btn btn-primary" onClick={() => setAdd(!add)}>Add lead</button></div>{error && <p className="text-rose-700">{error}</p>}
    {add && <form className="card grid gap-3 p-5 md:grid-cols-2" onSubmit={create}><input required className="input" placeholder="Lead name" value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} /><input required className="input" placeholder="Phone" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /><select className="input" value={form.source_id} onChange={e => setForm({ ...form, source_id: e.target.value })}>{lookups.sources.map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select className="input" value={form.status_id} onChange={e => setForm({ ...form, status_id: e.target.value })}>{lookups.statuses.map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button disabled={saving === 'new'} className="btn btn-primary md:col-span-2">{saving === 'new' ? 'Saving…' : 'Save lead'}</button></form>}
    <div className="card grid gap-2 p-4 md:grid-cols-4"><input className="input" placeholder="Search name or phone" value={filters.query} onChange={e => setFilters({ ...filters, query: e.target.value })} /><select className="input" value={filters.status_id} onChange={e => setFilters({ ...filters, status_id: e.target.value })}><option value="">All statuses</option>{lookups.statuses.map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select className="input" value={filters.source_id} onChange={e => setFilters({ ...filters, source_id: e.target.value })}><option value="">All sources</option>{lookups.sources.map((item: any) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select className="input" value={filters.temperature} onChange={e => setFilters({ ...filters, temperature: e.target.value })}><option value="">All temperatures</option><option value="cold">Cold</option><option value="warm">Warm</option><option value="hot">Hot</option></select><input className="input" type="date" value={filters.date} onChange={e => setFilters({ ...filters, date: e.target.value })} /><input className="input" placeholder="Profession" value={filters.profession} onChange={e => setFilters({ ...filters, profession: e.target.value })} /><input className="input" placeholder="Location" value={filters.location} onChange={e => setFilters({ ...filters, location: e.target.value })} /><button className="btn border" onClick={() => setFilters(emptyFilters)}>Clear filters</button></div>
    <div className="space-y-3 md:hidden">{leads.map(lead => <article className="card space-y-3 p-4" key={lead.id}><div className="flex justify-between gap-3"><div><Link className="font-bold text-brand" href={`/employee/crm/leads/${lead.id}`}>{lead.full_name}</Link><p className="text-sm">{dash(lead.phone)} <span className="text-slate-500">· {dash(lead.gender)}</span></p></div><span className="text-xs text-slate-500">{dash(lead.source?.name)}</span></div><div className="grid grid-cols-2 gap-3 text-sm"><div><b>Profession</b><p>{dash(lead.profession)}</p></div><div><b>Next follow-up</b><p>{nextFollowUp(lead)}</p></div></div><div className="grid grid-cols-2 gap-2">{statusSelect(lead)}{temperatureSelect(lead)}</div><button className="text-left text-sm font-medium text-brand" onClick={() => setExpanded(expanded === lead.id ? null : lead.id)}>{expanded === lead.id ? 'Hide details' : 'More details'}</button>{expanded === lead.id && <div className="border-t pt-3 text-sm"><b>Reason for enquiry</b><Clamp value={lead.reason_for_enquiry} /><b className="mt-3 block">Remarks</b><Clamp value={lead.remarks} muted /><b className="mt-3 block">Location</b><p>{dash(lead.location)}</p></div>}<Link className="btn border text-sm" href={`/employee/crm/leads/${lead.id}`}>View</Link></article>)}</div>
    <div className="card hidden md:block"><table className="table w-full table-fixed"><thead><tr><th className="w-[18%]">Lead</th><th className="w-[16%]">Profile</th><th className="w-[25%]">Enquiry</th><th className="w-[10%]">Source</th><th className="w-[13%]">Status</th><th className="w-[9%]">Temperature</th><th className="w-[12%]">Next follow-up</th><th className="w-[7%]">Actions</th></tr></thead><tbody>{leads.map(lead => <tr className="align-top" key={lead.id}><td className="py-3"><Link className="font-bold text-brand" href={`/employee/crm/leads/${lead.id}`}>{lead.full_name}</Link><small className="block text-slate-600">{dash(lead.phone)}</small><small className="text-slate-500">{dash(lead.gender)}</small></td><td className="py-3"><Clamp value={lead.profession} /><small className="hidden text-slate-500 xl:block"><Clamp value={lead.location} muted /></small></td><td className="py-3"><Clamp value={lead.reason_for_enquiry} /><span className="hidden lg:block"><Clamp value={lead.remarks} muted /></span></td><td className="py-3 text-sm"><Clamp value={lead.source?.name} /></td><td className="py-3">{statusSelect(lead)}</td><td className="py-3">{temperatureSelect(lead)}</td><td className="py-3 text-sm">{nextFollowUp(lead)}</td><td className="py-3"><Link aria-label={`View ${lead.full_name}`} className="btn border px-2 py-1 text-xs" href={`/employee/crm/leads/${lead.id}`}>{saving === lead.id ? 'Saving…' : 'View'}</Link></td></tr>)}{!leads.length && <tr><td className="p-5 text-slate-500" colSpan={8}>No leads match these filters.</td></tr>}</tbody></table></div>
  </section>;
}
